import '../models/models.dart';

// ─── COURSES & FLASHCARDS ─────────────────────────────────────────────────────
List<Course> buildCourses() {
  return [
    Course(
      id: 'meningite_pneumo',
      name: 'Méningite à Pneumocoque',
      cards: [
        Flashcard(id: 'mp1', question: 'Définition de la méningite à pneumocoque', answer: 'Localisation du Streptococcus pneumoniae au niveau des méninges. 2ème cause de méningite bactérienne de l\'adulte, non contagieuse, grave et souvent mortelle.'),
        Flashcard(id: 'mp2', question: 'Germe responsable et sa classification ?', answer: 'Streptococcus pneumoniae (pneumocoque) — diplocoque Gram positif.'),
        Flashcard(id: 'mp3', question: 'Quels terrains sont prédisposés à la méningite à pneumocoque ?', answer: 'Aspléniques, traumatisés du crâne, âges extrêmes de la vie, patients avec otite/sinusite, bronchopneumopathie chronique.'),
        Flashcard(id: 'mp4', question: 'Présentation clinique typique ?', answer: 'Début brutal : fièvre 39–40°C, céphalées violentes en casque, vomissements en jet, raideur de la nuque, photophobie, phonophobie. Formes méningo-encéphalitiques fréquentes.'),
        Flashcard(id: 'mp5', question: 'Traitement antibiotique de 1ère intention ?', answer: 'C3G : céfotaxime 200–300 mg/kg/j ou ceftriaxone 70–100 mg/kg/j en monothérapie sans gravité.'),
        Flashcard(id: 'mp6', question: 'Association en cas de signes de gravité ?', answer: 'C3G + Vancomycine 40–60 mg/kg/j en 4 perfusions d\'au moins 1 heure.'),
        Flashcard(id: 'mp7', question: 'Durée du traitement antibiotique ?', answer: '10 à 14 jours.'),
        Flashcard(id: 'mp8', question: 'Traitement adjuvant indiqué ?', answer: 'Dexaméthasone 0,15 mg/kg/6h pendant 2 à 4 jours, surtout chez l\'enfant pour diminuer les séquelles.'),
        Flashcard(id: 'mp9', question: 'Prévention pour les sujets à risque ?', answer: 'Pénicilline V 1–2 MUI/j + Vaccination (Prevenar 13 pour enfant < 2 ans, Pneumovax 23 pour adulte à risque).'),
      ],
    ),
    Course(
      id: 'strepto',
      name: 'Infections à Streptocoques',
      cards: [
        Flashcard(id: 'st1', question: 'Deux grands groupes de maladies streptococciques ?', answer: '1) Streptococcies suppuratives (multiplication bactérienne directe). 2) Streptococcies non suppuratives (mécanisme immuno-allergique).'),
        Flashcard(id: 'st2', question: 'Classification des streptocoques selon l\'hémolyse ?', answer: 'β-hémolytiques (zones claires) ; α-hémolytiques/viridans (zone verte) ; γ-hémolytiques (non hémolytiques).'),
        Flashcard(id: 'st3', question: 'Traitement de l\'angine streptococcique (1ère intention) ?', answer: 'Extencilline 600 000–1 200 000 UI IM dose unique, ou Amoxicilline 2 g/j × 6 jours PO.'),
        Flashcard(id: 'st4', question: 'Traitement si allergie aux pénicillines ?', answer: 'Macrolides : Érythromycine 2 g/j × 10 j, ou Azithromycine, Rovamycine, Clarithromycine, Josamycine.'),
        Flashcard(id: 'st5', question: 'Traitement de la septicémie à streptocoque ?', answer: 'Amoxicilline 200 mg/kg/j IV × 6 semaines + Gentamycine 3 mg/kg/j × 5 j. Si allergie : Vancomycine 2 g/j + Gentamycine.'),
        Flashcard(id: 'st6', question: 'Traitement du RAA ?', answer: 'Prednisone 2 mg/kg/j (max 80 mg) ≥ 2 semaines + Pénicilline V ou G 10 j + Salicylés si rebond.'),
        Flashcard(id: 'st7', question: 'Traitement de l\'érysipèle ?', answer: 'Amoxicilline 50 mg/kg/j PO × 7 j. Si allergie : Pristinamycine 3 g/j ou Clindamycine 600 mg × 3/j.'),
      ],
    ),
    Course(
      id: 'sepsis_bgn',
      name: 'Sepsis à BGN',
      cards: [
        Flashcard(id: 'sb1', question: 'Définition du sepsis (critères actuels) ?', answer: 'Dysfonction d\'organe menaçant le pronostic vital causée par une réponse dérégulée à une infection. Score SOFA ≥ 2.'),
        Flashcard(id: 'sb2', question: 'Antibiotiques actifs sur BGN sensibles ?', answer: 'Ceftriaxone, céfotaxime, ciprofloxacine, aminosides.'),
        Flashcard(id: 'sb3', question: 'Traitement empirique du sepsis communautaire non compliqué ?', answer: 'Ceftriaxone ou Amoxicilline–Acide clavulanique ± Aminoside.'),
        Flashcard(id: 'sb4', question: 'Traitement du sepsis nosocomial ou BGN-MR ?', answer: 'Carbapénème (Imipénème ou Méropénème). Si Pseudomonas : Pipéracilline–Tazobactam + Aminoside.'),
        Flashcard(id: 'sb5', question: 'Durée habituelle de l\'antibiothérapie ?', answer: '7 à 10 jours. Réévaluation à 48–72h.'),
        Flashcard(id: 'sb6', question: 'Quand initier l\'antibiothérapie dans le sepsis sévère ?', answer: 'Dans l\'heure suivant le diagnostic, après hémocultures, en IV.'),
      ],
    ),
    Course(
      id: 'meningocoque',
      name: 'Infections à Méningocoques',
      cards: [
        Flashcard(id: 'mn1', question: 'Définition de la méningococcémie ?', answer: 'Choc septique par libération d\'endotoxines Gram-négatif. Forme la plus grave en infectiologie. Purpura fulminans de Henoch.'),
        Flashcard(id: 'mn2', question: 'Traitement antibiotique de la méningite à méningocoque ?', answer: 'Amoxicilline 200 mg/kg/j IV ou Céfotaxime 200 mg/kg/j ou Ceftriaxone 100 mg/kg/j. Durée : 7 jours.'),
        Flashcard(id: 'mn3', question: 'Traitement si allergie aux β-lactamines ?', answer: 'Ciprofloxacine 10–20 mg/kg ou Rifampicine 20–30 mg/kg.'),
        Flashcard(id: 'mn4', question: 'Prophylaxie des sujets contacts ?', answer: 'Rifampicine 600 mg/j × 2 j (adulte) ou Azithromycine 500 mg dose unique ou Spiramycine × 5 j. Déclaration obligatoire.'),
        Flashcard(id: 'mn5', question: 'Traitement adjuvant de la méningite ?', answer: 'Dexaméthasone 10 mg/6h × 4 j (adulte). Repos, antalgiques. Audiogramme de surveillance.'),
      ],
    ),
    Course(
      id: 'choc_septique',
      name: 'Choc Septique',
      cards: [
        Flashcard(id: 'cs1', question: 'Définition du choc septique ?', answer: 'Sepsis avec hypotension persistante malgré remplissage, nécessitant vasopresseurs pour PAM ≥ 65 mmHg + lactatémie > 2 mmol/L.'),
        Flashcard(id: 'cs2', question: 'Amine vasopressive de 1ère intention ?', answer: 'Noradrénaline 0,5–1 mg/kg/h IV. Objectif PAM ≥ 75 mmHg. Dobutamine si défaillance cardiaque.'),
        Flashcard(id: 'cs3', question: 'Antibiothérapie empirique communautaire ?', answer: 'Ceftriaxone 2 g/j + Gentamicine + Métronidazole 1,5 g/j.'),
        Flashcard(id: 'cs4', question: 'Antibiothérapie empirique nosocomiale ?', answer: 'Imipénème + Amikacine + Vancomycine.'),
        Flashcard(id: 'cs5', question: '4 grands principes du traitement ?', answer: '1) Remplissage vasculaire. 2) Amines pressives. 3) Antibiothérapie précoce adaptée. 4) Traitement des défaillances d\'organe.'),
        Flashcard(id: 'cs6', question: 'Place des corticoïdes dans le choc septique ?', answer: 'Discutée si choc persistant : Hydrocortisone 200 mg/j.'),
      ],
    ),
    Course(
      id: 'cholera',
      name: 'Choléra',
      cards: [
        Flashcard(id: 'ch1', question: 'Agent causal et mécanisme pathogène ?', answer: 'Vibrio cholerae — sécrétion d\'une entérotoxine → hypersécrétion de chlorure de sodium et d\'eau → diarrhée riziforme, sans fièvre ni douleur.'),
        Flashcard(id: 'ch2', question: 'Traitement primordial du choléra ?', answer: 'La réhydratation (SRO per os ou IV si DHA ≥ 10%). C\'est l\'essentiel du traitement. L\'antibiotique est accessoire.'),
        Flashcard(id: 'ch3', question: 'Traitement antibiotique de 1ère intention ?', answer: 'Doxycycline 300 mg dose unique ou Azithromycine 1 g dose unique.'),
        Flashcard(id: 'ch4', question: 'Alternative antibiotique ?', answer: 'Cotrimoxazole 2 cp × 2/j × 3 j ou Ciprofloxacine 1 g dose unique.'),
        Flashcard(id: 'ch5', question: 'Durée diarrhée avec vs sans traitement ?', answer: 'Avec ATB : 2 jours, volume 4–5 L. Sans ATB : 3–5 jours.'),
      ],
    ),
    Course(
      id: 'typhoide',
      name: 'Fièvre Typhoïde',
      cards: [
        Flashcard(id: 'ty1', question: 'Définition de la fièvre typhoïde ?', answer: 'Toxi-infection bactérienne à transmission hydro-fécale, endémo-épidémique, due à Salmonella Typhi. MDO.'),
        Flashcard(id: 'ty2', question: 'Évolution clinique en 3 septénaires ?', answer: '1er : céphalée fébrile progressive. 2ème : diarrhée en jus de melon. 3ème : complications toxiniques (hémorragiques, digestives).'),
        Flashcard(id: 'ty3', question: 'Traitement de 1ère intention (consensus maghrébin) ?', answer: 'Cotrimoxazole (SMX 400 mg + TMP 80 mg) 2 cp × 2/j × 14 j. CI : allergie sulfamides, grossesse.'),
        Flashcard(id: 'ty4', question: 'Traitement de 2ème intention ?', answer: 'Amoxicilline 75–100 mg/kg/j × 15 j post-apyrexie, à doses progressives.'),
        Flashcard(id: 'ty5', question: 'Alternatives modernes (traitements courts) ?', answer: 'Ciprofloxacine 500 mg × 2/j × 5–7 j (adulte) ; Ceftriaxone 60–75 mg/kg/j × 3–7 j ; Azithromycine 10 mg/kg/j × 7 j.'),
      ],
    ),
    Course(
      id: 'leptospirose',
      name: 'Leptospirose',
      cards: [
        Flashcard(id: 'lp1', question: 'Agent causal et réservoir principal ?', answer: 'Leptospira interrogans. Réservoir : rongeurs (rats) qui éliminent les leptospires dans les urines. Transmission par eau/sol contaminé.'),
        Flashcard(id: 'lp2', question: 'Triade du syndrome de Weil ?', answer: 'Ictère grave + Insuffisance rénale aiguë + Syndrome hémorragique diffus. Décès par défaillance multi-viscérale.'),
        Flashcard(id: 'lp3', question: 'Traitement des formes sévères ?', answer: 'Amoxicilline 100 mg/kg/j IV × 7–10 j ou Ceftriaxone 1 g/j IV ou Pénicilline G 6–10 MUI/j × 7–10 j.'),
        Flashcard(id: 'lp4', question: 'Traitement des formes non sévères ?', answer: 'Doxycycline 200 mg/j × 7 j ou Amoxicilline PO.'),
        Flashcard(id: 'lp5', question: 'Prophylaxie avant exposition à risque ?', answer: 'Doxycycline 200 mg/semaine (efficacité 95%). Pour groupes exposés (militaires, pompiers, etc.).'),
        Flashcard(id: 'lp6', question: 'Réaction de Jarisch-Herxheimer ?', answer: 'Réaction systémique (fièvre, frissons, hypotension) à l\'initiation de l\'antibiothérapie, due à la lyse bactérienne.'),
      ],
    ),
    Course(
      id: 'dhab',
      name: 'Dermohypodermites Bactériennes',
      cards: [
        Flashcard(id: 'dh1', question: 'Différence entre DHBNN et DHBN ?', answer: 'DHBNN (érysipèle) : bénigne, infection non nécrosante, traitement ambulatoire. DHBN (fasciite nécrosante) : urgence médico-chirurgicale grave.'),
        Flashcard(id: 'dh2', question: 'Agent causal principal de l\'érysipèle ?', answer: 'Streptocoque β-hémolytique groupe A (85%), rarement B, G ou C.'),
        Flashcard(id: 'dh3', question: 'Tableau clinique de l\'érysipèle ?', answer: 'Grosse jambe rouge aiguë fébrile. Placard érythémateux à bords nets, douloureux, chaud. Fièvre, frissons. Porte d\'entrée : intertrigo inter-orteil.'),
        Flashcard(id: 'dh4', question: 'Traitement de l\'érysipèle (1ère intention) ?', answer: 'Amoxicilline 50 mg/kg/j PO × 7 j en ambulatoire. Pas d\'ATB locale, pas de corticoïdes ni d\'AINS.'),
        Flashcard(id: 'dh5', question: 'Antibiothérapie de la fasciite nécrosante ?', answer: 'Amoxicilline + Acide clavulanique + Clindamycine (anti-toxinique). 14–21 j. Si SARM : + Vancomycine.'),
        Flashcard(id: 'dh6', question: 'Prévention des récidives d\'érysipèle ?', answer: 'Traiter la porte d\'entrée, contention veineuse. Si > 2 épisodes/an : Benzathine Benzyl-pénicilline G ou Pénicilline V.'),
      ],
    ),
    Course(
      id: 'coqueluche',
      name: 'Coqueluche',
      cards: [
        Flashcard(id: 'cq1', question: 'Agent causal et caractéristiques ?', answer: 'Bordetella pertussis — coccobacille Gram négatif, aérobie strict, strictement humain. Hautement contagieuse. MDO.'),
        Flashcard(id: 'cq2', question: 'Les 3 phases cliniques ?', answer: '1) Phase catarrhale (1–2 sem) : rhume banal. 2) Phase des quintes (2–4 sem) : quintes paroxystiques avec reprise inspiratoire sifflante. 3) Convalescence.'),
        Flashcard(id: 'cq3', question: 'Antibiotique de référence ?', answer: 'Érythromycine 50 mg/kg/j (enfant) ou 2 g/j (adulte) × 14 j.'),
        Flashcard(id: 'cq4', question: 'Alternative moderne plus courte ?', answer: 'Azithromycine : enfant 10 mg/kg J1 puis 5 mg/kg × 4 j. Adulte : 500 mg J1 puis 250 mg × 4 j.'),
        Flashcard(id: 'cq5', question: 'L\'ATB est-elle efficace sur la maladie elle-même ?', answer: 'Uniquement en phase catarrhale. En phase des quintes, l\'ATB réduit la contagiosité mais n\'atténue pas les quintes.'),
        Flashcard(id: 'cq6', question: 'Prophylaxie des sujets contacts ?', answer: 'Même schéma antibiotique que le traitement curatif, le plus tôt possible (max 21 j après dernier contact).'),
      ],
    ),
    Course(
      id: 'brucellose',
      name: 'Brucellose',
      cards: [
        Flashcard(id: 'br1', question: 'Définition et synonymes ?', answer: 'Anthropozoonose bactérienne = Fièvre de Malte = Fièvre méditerranéenne. Due à Brucella (coccobacille). MDO.'),
        Flashcard(id: 'br2', question: 'Espèces de Brucella ?', answer: 'B. melitensis (chèvres, moutons) — la plus pathogène. B. abortus (bovins). B. suis (porcs). B. canis (chiens).'),
        Flashcard(id: 'br3', question: 'Tableau clinique de la brucellose aiguë ?', answer: 'Fièvre ondulante vespérale, sudations profuses malodorantes, arthralgies, asthénie. « Maladie aux cent visages ».'),
        Flashcard(id: 'br4', question: 'Traitement de 1ère intention ?', answer: 'Doxycycline 200 mg/j + Rifampicine 600–900 mg/j PO pendant 6 semaines minimum.'),
        Flashcard(id: 'br5', question: 'Autre association possible ?', answer: 'Doxycycline + Gentamycine 5 mg/kg/j × 7 j (ou Streptomycine). Plus efficace sur les rechutes.'),
        Flashcard(id: 'br6', question: 'Pourquoi 2 ATB pendant 6 semaines ?', answer: 'Brucella est intracellulaire obligatoire. Il faut une bonne diffusion tissulaire et cellulaire, en association pour éviter les rechutes.'),
      ],
    ),
    Course(
      id: 'fbm',
      name: 'Fièvre Boutonneuse Méditerranéenne',
      cards: [
        Flashcard(id: 'fb1', question: 'Agent causal et vecteur ?', answer: 'Rickettsia conorii, transmise par la tique du chien (Rhipicephalus sanguineus). Saison : printemps–été–début automne.'),
        Flashcard(id: 'fb2', question: 'Triade clinique classique ?', answer: 'Fièvre + Exanthème maculo-papuleux (paumes et plantes incluses) + Tache de Pieri (escarre noire au site de morsure de tique).'),
        Flashcard(id: 'fb3', question: 'Traitement de 1ère intention ?', answer: 'Doxycycline 200 mg/j × 5–7 jours (ou 2 jours après apyrexie).'),
        Flashcard(id: 'fb4', question: 'Alternative si contre-indication aux cyclines ?', answer: 'Azithromycine (notamment chez l\'enfant).'),
        Flashcard(id: 'fb5', question: 'Pourquoi les β-lactamines sont-elles inefficaces ?', answer: 'Rickettsia est intracellulaire obligatoire. Seuls les ATB à bonne pénétration intracellulaire sont actifs (tétracyclines, macrolides).'),
        Flashcard(id: 'fb6', question: 'Facteurs de mauvais pronostic de la FBM ?', answer: 'Alcoolisme, diabète, déficit en G6PD, âge avancé, retard au traitement, ATB inefficaces.'),
      ],
    ),
    Course(
      id: 'diphterie',
      name: 'Diphtérie',
      cards: [
        Flashcard(id: 'dp1', question: 'Définition de la diphtérie ?', answer: 'Toxi-infection bactérienne hautement contagieuse due à Corynebacterium diphtheriae (Gram positif). MDO. Urgence thérapeutique.'),
        Flashcard(id: 'dp2', question: 'Tableau clinique de l\'angine diphtérique ?', answer: 'Fausses membranes blanc-grisâtres adhérentes débordant les amygdales, fièvre modérée 38°C, adénopathies cervicales (« cou proconsulaire »).'),
        Flashcard(id: 'dp3', question: 'Traitement spécifique principal ?', answer: 'Sérothérapie antidiphtérique (SAD) en urgence, sans attendre les résultats biologiques. C\'est le traitement principal contre la toxine.'),
        Flashcard(id: 'dp4', question: 'Rôle de l\'antibiothérapie ?', answer: 'Éradication du foyer bactérien toxinogène (rôle secondaire mais indispensable). Débuté en même temps que la sérothérapie.'),
        Flashcard(id: 'dp5', question: 'Protocole antibiotique ?', answer: 'Pénicilline G IV → relais Pénicilline V orale, ou Amoxicilline 50 mg/kg/j (enfant) / 3 g/j (adulte). Si allergie : Érythromycine. Durée : 14 jours.'),
        Flashcard(id: 'dp6', question: 'Prophylaxie des sujets contacts ?', answer: 'Antibioprophylaxie 7 j (Amoxicilline ou Macrolide) + vérification vaccination. Isolement jusqu\'à 2 prélèvements négatifs.'),
      ],
    ),
    Course(
      id: 'paludisme',
      name: 'Paludisme',
      cards: [
        Flashcard(id: 'pa1', question: 'Agent causal et espèces pathogènes ?', answer: 'Plasmodium (protozoaire). 5 espèces : P. falciparum (plus grave), P. vivax, P. ovale, P. malariae, P. knowlesi. Vecteur : anophèle femelle.'),
        Flashcard(id: 'pa2', question: 'Traitement de l\'accès simple à P. falciparum ?', answer: 'Artéméther-Luméfantrine (Coartem) × 3 jours + Primaquine dose unique à J1.'),
        Flashcard(id: 'pa3', question: 'Traitement de l\'accès simple à P. vivax / ovale ?', answer: 'Artéméther-Luméfantrine × 3 j + Primaquine × 14 jours (éradication des hypnozoïtes hépatiques).'),
        Flashcard(id: 'pa4', question: 'Traitement du paludisme grave ?', answer: 'Artésunate injectable IV/IM 2,4 mg/kg à H0, H12, H24 puis 1×/j → relais Artéméther-Luméfantrine × 3 j.'),
        Flashcard(id: 'pa5', question: 'Alternative pour le paludisme grave ?', answer: 'Quinine base IV : charge 16 mg/kg puis entretien 8 mg/kg/8h (max 7 j). Surveillance hypoglycémie et troubles du rythme.'),
        Flashcard(id: 'pa6', question: 'Conditions de prise en charge du paludisme grave ?', answer: 'USI obligatoire. Voie parentérale au moins 24h. Traitement symptomatique : équilibre hydroélectrolytique, ventilation, dialyse si IR.'),
        Flashcard(id: 'pa7', question: 'Fièvre bilieuse hémoglobinurique ?', answer: 'Hémolyse aiguë chez sujets sous prophylaxie ou traitement incomplets/répétés par quinine ou méfloquine.'),
      ],
    ),
    Course(
      id: 'toxoplasmose',
      name: 'Toxoplasmose',
      cards: [
        Flashcard(id: 'tx1', question: 'Définition de la toxoplasmose ?', answer: 'Anthropozoonose cosmopolite due à Toxoplasma gondii (protozoaire intracellulaire). Hôte définitif : chat. Asymptomatique chez l\'immunocompétent.'),
        Flashcard(id: 'tx2', question: '3 formes de Toxoplasma gondii ?', answer: 'Tachyzoïtes (phase aiguë) ; Bradyzoïtes dans des kystes (phase chronique) ; Oocystes (forme sexuée, excrétés par le chat).'),
        Flashcard(id: 'tx3', question: 'Traitement chez l\'immunodéprimé (1ère ligne) ?', answer: 'Pyriméthamine + Sulfadiazine + Acide folinique × 6 semaines puis traitement d\'entretien.'),
        Flashcard(id: 'tx4', question: 'Alternative si intolérance à la sulfadiazine ?', answer: 'Pyriméthamine + Clindamycine 2,4 g/j × 6 semaines + Acide folinique.'),
        Flashcard(id: 'tx5', question: 'Traitement chez la femme enceinte (avant 18 SA) ?', answer: 'Spiramycine 6–9 MUI/j jusqu\'à l\'accouchement. Si PCR positive : Pyriméthamine + Sulfamide + Acide folinique.'),
        Flashcard(id: 'tx6', question: 'Prophylaxie primaire chez le patient VIH (CD4 < 200) ?', answer: 'Cotrimoxazole 1 cp/j jusqu\'à restauration immunitaire (CD4 > 200).'),
      ],
    ),
    Course(
      id: 'amoebiase',
      name: 'Amoebose',
      cards: [
        Flashcard(id: 'am1', question: 'Agent causal et formes cliniques ?', answer: 'Entamoeba histolytica. 2 formes : amibiase-infection (asymptomatique) et amibiase-maladie (symptomatique, forme hématophage).'),
        Flashcard(id: 'am2', question: 'Principales localisations de l\'amoebose-maladie ?', answer: 'Intestinale (colique) : dysenterie amibienne. Extra-intestinale : abcès hépatique (le plus fréquent), pleuropulmonaire, cérébral.'),
        Flashcard(id: 'am3', question: 'Traitement de l\'amoebose colique aiguë ?', answer: 'Métronidazole 500 mg × 3/j PO × 7–10 j, puis Intetrix × 10 j pour éradiquer les formes kystiques.'),
        Flashcard(id: 'am4', question: 'Traitement de l\'abcès hépatique amibien ?', answer: 'Métronidazole IV ou PO 1,5–2 g/j × 7–10 j ± ponctions échoguidées. Chirurgie si non réponse.'),
        Flashcard(id: 'am5', question: 'Alternatives aux nitro-5-imidazolés ?', answer: 'Ornidazole (Tibéral), Secnidazole (Secnol), Tinidazole (Fasigyne).'),
        Flashcard(id: 'am6', question: 'Traitement éradicateur de contact ?', answer: 'Tiliquinol + Tilbroquinol (Intetrix) 2 gélules × 2/j × 10 j ou Paromomycine 25–35 mg/kg/j × 5–10 j.'),
      ],
    ),
    Course(
      id: 'herpes',
      name: 'Herpès Viroses',
      cards: [
        Flashcard(id: 'he1', question: 'Classification des 8 herpesvirus humains ?', answer: 'α-herpes : HSV-1, HSV-2, VZV. β-herpes : CMV, HHV-6, HHV-7. γ-herpes : EBV (MNI), HHV-8.'),
        Flashcard(id: 'he2', question: 'Traitement de la méningo-encéphalite herpétique ?', answer: 'Urgence ! Aciclovir 10 mg/kg/8h IV × 10–15 jours. Une simple suspicion suffit à initier sans attendre les résultats.'),
        Flashcard(id: 'he3', question: 'Traitement de la gingivostomatite herpétique sévère ?', answer: 'Aciclovir IV si PO impossible, ou Valaciclovir 2 cp/j × 8–10 jours. Réhydratation + bains de bouche bicarbonatés.'),
        Flashcard(id: 'he4', question: 'Traitement chez immunodéprimé, nouveau-né, femme enceinte ?', answer: 'Aciclovir 10 mg/kg/8h IV × 10–15 jours (dose élevée ou durée allongée selon gravité).'),
        Flashcard(id: 'he5', question: 'Qu\'est-ce que la latence virale herpétique ?', answer: 'Après la primo-infection, le virus persiste à vie dans les ganglions sensitifs et peut se réactiver (stress, immunodéficience, UV, fièvre).'),
      ],
    ),
    Course(
      id: 'mni',
      name: 'MNI (Mononucléose Infectieuse)',
      cards: [
        Flashcard(id: 'mi1', question: 'Agent causal de la MNI ?', answer: 'Virus Epstein-Barr (EBV) — herpesvirus de type 4. Souvent asymptomatique chez l\'enfant, symptomatique chez l\'adolescent/adulte.'),
        Flashcard(id: 'mi2', question: 'Triade clinique de la MNI ?', answer: 'Fièvre + Angine pseudo-membraneuse + Adénopathies cervicales + Splénomégalie fréquente.'),
        Flashcard(id: 'mi3', question: 'Piège diagnostique avec les aminopénicillines ?', answer: 'Amoxicilline/ampicilline provoque une éruption cutanée dans 90% des cas au 9ème–11ème jour. Les pénicillines A sont à proscrire.'),
        Flashcard(id: 'mi4', question: 'Quel est le traitement de la MNI ?', answer: 'Traitement symptomatique (repos, antiseptiques, hydratation). Les antibiotiques sont inutiles.'),
        Flashcard(id: 'mi5', question: 'Quand utiliser les corticoïdes dans la MNI ?', answer: 'Si tuméfaction amygdalienne importante avec gêne respiratoire ou à la déglutition.'),
      ],
    ),
    Course(
      id: 'rage',
      name: 'Rage',
      cards: [
        Flashcard(id: 'ra1', question: 'Agent causal et transmission ?', answer: 'Lyssavirus (Rhabdoviridae). Transmission par morsure d\'animal enragé (chien++, chauve-souris, renard). Incubation 1–3 mois. Mortelle une fois déclarée.'),
        Flashcard(id: 'ra2', question: 'Conduite à tenir immédiate après morsure ?', answer: '1) Nettoyage abondant eau + savon. 2) Antiseptique. 3) Immunoglobulines anti-rabiques. 4) ATB préventif. 5) Sérovaccination anti-rabique.'),
        Flashcard(id: 'ra3', question: 'Antibiotique prophylactique après morsure ?', answer: 'Cyclines ou Amoxicilline–Acide clavulanique × 5–10 jours (prévention surinfection bactérienne).'),
        Flashcard(id: 'ra4', question: 'Traitement spécifique de la rage ?', answer: 'Sérovaccination anti-rabique (OMS). La rage cliniquement déclarée est mortelle à 100% sans traitement préventif.'),
      ],
    ),
    Course(
      id: 'meningite_claire',
      name: 'Méningite à Liquide Clair',
      cards: [
        Flashcard(id: 'mc1', question: 'Principales étiologies d\'une méningite à LCR clair ?', answer: '1) Méningite virale (la plus fréquente). 2) Méningite tuberculeuse. 3) Méningite à Listeria. 4) Méningite décapitée. 5) Leptospires. 6) Syphilitique.'),
        Flashcard(id: 'mc2', question: 'Quand traiter en urgence sans attendre le diagnostic ?', answer: 'Si signes de sévérité ou doute bactérien : ATB probabiliste. Si suspicion encéphalite herpétique : Aciclovir IV immédiatement.'),
        Flashcard(id: 'mc3', question: 'Traitement de la méningite tuberculeuse ?', answer: '2 ERHZ (Éthambutol + Rifampicine + Isoniazide + Pyrazinamide) × 2 mois, puis 7 RH × 7 mois + Prédnisone 2 mg/kg/j × 4 sem.'),
        Flashcard(id: 'mc4', question: 'Traitement de la méningite à Listeria ?', answer: 'Amoxicilline 200 mg/kg/j IV × 21 jours + Gentamycine.'),
      ],
    ),
    Course(
      id: 'diarrhees',
      name: 'Diarrhées Infectieuses / TIAC',
      cards: [
        Flashcard(id: 'di1', question: 'Définition d\'une TIAC ?', answer: 'Toxi-Infection Alimentaire Collective : ≥ 2 cas similaires de symptômes digestifs chez des personnes ayant partagé le même repas.'),
        Flashcard(id: 'di2', question: 'Traitement prioritaire des diarrhées infectieuses ?', answer: 'La réhydratation orale (SRO). C\'est l\'essentiel du traitement. IV si DHA ≥ 10%, vomissements, collapsus ou troubles de la conscience.'),
        Flashcard(id: 'di3', question: 'Antibiothérapie de la fièvre typhoïde ?', answer: 'Fluoroquinolones (adulte), Cotrimoxazole (enfant), Ampicilline (femme enceinte).'),
        Flashcard(id: 'di4', question: 'Traitement du Clostridium difficile ?', answer: 'Métronidazole × 10 jours. Alternative : Vancomycine PO.'),
        Flashcard(id: 'di5', question: 'Traitement du Vibrio cholerae (antibiotique) ?', answer: 'Doxycycline × 3 jours. Alternative : Cotrimoxazole.'),
      ],
    ),
  ];
}

// ─── ANTIBIOTIC TABLE DATA ────────────────────────────────────────────────────
const List<AntibioticEntry> antibioticData = [
  AntibioticEntry(
    disease: 'Méningite à Pneumocoque',
    category: 'bacterial',
    agent: 'Streptococcus pneumoniae',
    firstLine: 'Céfotaxime 200–300 mg/kg/j IV\nCeftriaxone 70–100 mg/kg/j IV\n± Vancomycine 40–60 mg/kg/j si signes de gravité',
    alternative: 'Méropénème\nRifampicine + Fosfomycine',
    duration: '10–14 jours',
    notes: 'Dexaméthasone 0,15 mg/kg/6h × 4 j (enfant). Urgence thérapeutique.',
  ),
  AntibioticEntry(
    disease: 'Infections à Streptocoques',
    category: 'bacterial',
    agent: 'Streptococcus (groupe A, B, C, G)',
    firstLine: 'Pénicilline G IV (50 000 UI/kg/j)\nAmoxicilline 2 g/j PO (adulte)\nExtencilline 600 000–1 200 000 UI IM (1 injection)',
    alternative: 'Érythromycine 2 g/j × 10 j\nAzithromycine / Roxithromycine',
    duration: '6–10 jours (selon forme)',
    notes: 'Streptocoques très sensibles aux β-lactamines. Septicémie : Amoxicilline + Gentamycine.',
  ),
  AntibioticEntry(
    disease: 'Sepsis à BGN',
    category: 'bacterial',
    agent: 'Bacilles Gram négatif (E. coli, Klebsiella, Pseudomonas…)',
    firstLine: 'Communautaire : Ceftriaxone ou Amoxicilline-clavulanique ± Aminoside\nNosocomial/MR : Carbapénème (Imipénème / Méropénème)',
    alternative: 'Pipéracilline-Tazobactam + Aminoside (si Pseudomonas)',
    duration: '7–10 jours',
    notes: 'ATB dans l\'heure. Probabiliste → adapté à 48–72h selon hémocultures.',
  ),
  AntibioticEntry(
    disease: 'Infections à Méningocoques',
    category: 'bacterial',
    agent: 'Neisseria meningitidis',
    firstLine: 'Amoxicilline 200 mg/kg/j IV\nCéfotaxime 200 mg/kg/j IV\nCeftriaxone 100 mg/kg/j IV',
    alternative: 'Ciprofloxacine 10–20 mg/kg\nRifampicine 20–30 mg/kg',
    duration: '7 jours',
    notes: 'Prophylaxie contacts : Rifampicine 2j ou Azithromycine 500 mg dose unique. Déclaration obligatoire.',
  ),
  AntibioticEntry(
    disease: 'Infections à Staphylocoques',
    category: 'bacterial',
    agent: 'Staphylococcus aureus (SASM / SARM)',
    firstLine: 'SASM : Oxacilline / Cloxacilline IV',
    alternative: 'SARM : Vancomycine IV\nLinézolide\nDaptomycine\nRifampicine + Acide fusidique',
    duration: 'Selon localisation (14–42 j)',
    notes: 'Fasciite nécrosante : β-lactamine + inhibiteur + clindamycine ± vancomycine.',
  ),
  AntibioticEntry(
    disease: 'Choc Septique',
    category: 'bacterial',
    agent: 'Polymicrobien selon porte d\'entrée',
    firstLine: 'Communautaire : Ceftriaxone 2g/j + Gentamicine + Métronidazole 1,5 g/j\nNosocomial : Imipénème + Amikacine + Vancomycine',
    alternative: 'Pipéracilline-Tazobactam',
    duration: 'Réévaluation à 48–72h',
    notes: 'Urgence absolue : ATB dans l\'heure, bactéricide, IV, large spectre.',
  ),
  AntibioticEntry(
    disease: 'Choléra',
    category: 'bacterial',
    agent: 'Vibrio cholerae',
    firstLine: 'Doxycycline 300 mg dose unique (adulte)\nAzithromycine 1 g dose unique',
    alternative: 'Cotrimoxazole 2 cp × 2/j × 3 j\nCiprofloxacine 1 g dose unique',
    duration: '1–3 jours',
    notes: 'ATB accessoire — la réhydratation est primordiale (SRO/IV). MDO.',
  ),
  AntibioticEntry(
    disease: 'Fièvre Typhoïde',
    category: 'bacterial',
    agent: 'Salmonella Typhi / Paratyphi',
    firstLine: 'Cotrimoxazole 2 cp × 2/j × 14 j\nAmoxicilline 75–100 mg/kg/j × 15 j\nCiprofloxacine 500 mg × 2/j × 5–7 j (adulte)',
    alternative: 'Ceftriaxone 60–75 mg/kg/j × 3–7 j\nAzithromycine 10 mg/kg/j × 7 j',
    duration: '5–14 jours',
    notes: 'CI ciprofloxacine : enfant < 15 ans, femme enceinte. MDO.',
  ),
  AntibioticEntry(
    disease: 'Leptospirose',
    category: 'bacterial',
    agent: 'Leptospira interrogans',
    firstLine: 'Amoxicilline 100 mg/kg/j IV × 7–10 j\nCeftriaxone 1 g/j IV\nPénicilline G 6–10 MUI/j',
    alternative: 'Doxycycline 200 mg/j × 7 j (formes légères)\nAzithromycine',
    duration: '7–10 jours',
    notes: 'Efficace si traitement avant J4. Prophylaxie : Doxycycline 200 mg/semaine.',
  ),
  AntibioticEntry(
    disease: 'Dermohypodermite Bactérienne (Érysipèle)',
    category: 'bacterial',
    agent: 'Streptocoque β-hémolytique A (85%)',
    firstLine: 'Amoxicilline 50 mg/kg/j PO × 7 j',
    alternative: 'Pristinamycine 3 g/j\nClindamycine 600 mg × 3/j',
    duration: '7 jours',
    notes: 'Pas d\'ATB locale ni AINS. Fasciite nécrosante : Amoxicilline-clavulanique + Clindamycine ± Aminoside, 14–21 j.',
  ),
  AntibioticEntry(
    disease: 'Coqueluche',
    category: 'bacterial',
    agent: 'Bordetella pertussis',
    firstLine: 'Érythromycine 50 mg/kg/j (E) / 2 g/j (A) × 14 j\nAzithromycine 10 mg/kg J1 puis 5 mg/kg × 4 j (E)',
    alternative: 'Clarithromycine 15 mg/kg/j × 7 j (E)\nJosamycine',
    duration: '7–14 jours',
    notes: 'ATB efficace surtout en phase catarrhale. Antibioprophylaxie de l\'entourage : même schéma. MDO.',
  ),
  AntibioticEntry(
    disease: 'Brucellose',
    category: 'bacterial',
    agent: 'Brucella melitensis / abortus',
    firstLine: 'Doxycycline 200 mg/j + Rifampicine 600–900 mg/j × 6 sem\nDoxycycline + Gentamycine × 7 j',
    alternative: 'Cotrimoxazole\nCiprofloxacine 500 mg × 2/j × 6 sem',
    duration: '≥ 6 semaines',
    notes: 'Au moins 2 ATB à bonne diffusion intracellulaire. MDO.',
  ),
  AntibioticEntry(
    disease: 'Fièvre Boutonneuse Méditerranéenne',
    category: 'bacterial',
    agent: 'Rickettsia conorii (tiques)',
    firstLine: 'Doxycycline 200 mg/j × 5–7 j',
    alternative: 'Azithromycine (enfant ou CI aux cyclines)',
    duration: '5–7 jours',
    notes: 'Résistance aux β-lactamines. Pénétration intracellulaire indispensable.',
  ),
  AntibioticEntry(
    disease: 'Diphtérie',
    category: 'bacterial',
    agent: 'Corynebacterium diphtheriae (toxinogène)',
    firstLine: 'Pénicilline G IV → relais Pénicilline V orale\nAmoxicilline 50 mg/kg/j (E) / 3 g/j (A)',
    alternative: 'Érythromycine 50 mg/kg/j (E) / 2–3 g/j (A) × 14 j (si allergie)',
    duration: '14 jours',
    notes: 'Sérothérapie antidiphtérique en urgence (traitement principal). MDO.',
  ),
  AntibioticEntry(
    disease: 'Méningite Tuberculeuse',
    category: 'bacterial',
    agent: 'Mycobacterium tuberculosis',
    firstLine: '2 ERHZ : Éthambutol 15 mg/kg + Rifampicine 10 mg/kg + Isoniazide 5 mg/kg + Pyrazinamide 30 mg/kg',
    alternative: 'Puis 7 RH (phase continuation)',
    duration: '9 mois (2 + 7)',
    notes: 'Corticoïdes : Prédnisone 2 mg/kg/j × 4 sem. Pronostic selon précocité.',
  ),
  AntibioticEntry(
    disease: 'Méningite à Listéria',
    category: 'bacterial',
    agent: 'Listeria monocytogenes',
    firstLine: 'Amoxicilline 200 mg/kg/j × 21 j + Gentamycine',
    alternative: 'Cotrimoxazole + Rifampicine + Gentamycine',
    duration: '21 jours',
    notes: 'LCR clair à prédominance lymphocytaire. Immunodéprimé et femme enceinte.',
  ),
  AntibioticEntry(
    disease: 'Diarrhées Infectieuses Bactériennes',
    category: 'bacterial',
    agent: 'Salmonella, Shigella, Campylobacter, C. difficile, V. cholerae',
    firstLine: 'Salmonella : Fluoroquinolone × 5 j\nC. difficile : Métronidazole × 10 j\nV. cholerae : Doxycycline × 3 j',
    alternative: 'Vancomycine PO (C. difficile)\nAzithromycine (Campylobacter/Shigella)',
    duration: '3–14 j selon germe',
    notes: 'Réhydratation primordiale. Adulte : FLQ ; Enfant : Bactrim ; Femme enceinte : Ampicilline.',
  ),
  AntibioticEntry(
    disease: 'Paludisme — Accès Simple',
    category: 'parasitic',
    agent: 'Plasmodium falciparum / vivax / ovale / malariae',
    firstLine: 'P. falciparum : Artéméther-Luméfantrine × 3 j + Primaquine J1\nP. vivax/ovale : Artéméther-Luméfantrine × 3 j + Primaquine × 14 j',
    alternative: 'Quinine cp × 7 j + Primaquine\nChloroquine × 3 j (P. vivax si sensible)',
    duration: '3–7 jours',
    notes: 'Urgence médicale. MDO. Extension des résistances à la chloroquine.',
  ),
  AntibioticEntry(
    disease: 'Paludisme Grave',
    category: 'parasitic',
    agent: 'Plasmodium falciparum (essentiellement)',
    firstLine: 'Artésunate IV/IM 2,4 mg/kg à H0, H12, H24 puis 1×/j → relais Artéméther-Luméfantrine × 3 j',
    alternative: 'Quinine base IV : charge 16 mg/kg → entretien 8 mg/kg/8h',
    duration: 'Quinine max 7 j',
    notes: 'USI obligatoire. Surveillance hypoglycémie et troubles du rythme sous quinine.',
  ),
  AntibioticEntry(
    disease: 'Toxoplasmose (Immunodéprimé)',
    category: 'parasitic',
    agent: 'Toxoplasma gondii',
    firstLine: 'Pyriméthamine + Sulfadiazine + Acide folinique × 6 sem',
    alternative: 'Pyriméthamine + Clindamycine 2,4 g/j × 6 sem\nAzithromycine + Pyriméthamine',
    duration: '6 semaines + entretien',
    notes: 'Prophylaxie : Cotrimoxazole 1 cp/j (CD4 < 200). Femme enceinte : Spiramycine 6–9 MUI/j.',
  ),
  AntibioticEntry(
    disease: 'Amoebose',
    category: 'parasitic',
    agent: 'Entamoeba histolytica',
    firstLine: 'Amoebose colique : Métronidazole 500 mg × 3/j × 7–10 j\nAbcès hépatique : Métronidazole 1,5–2 g/j × 10 j',
    alternative: 'Ornidazole (Tibéral)\nSecnidazole (Secnol)\nTinidazole (Fasigyne)',
    duration: '7–20 j selon localisation',
    notes: 'Traitement de contact : Intetrix × 10 j. Forme maligne : Métronidazole IV + ATB large spectre.',
  ),
  AntibioticEntry(
    disease: 'Herpès — Méningo-encéphalite (HSV1)',
    category: 'viral',
    agent: 'Herpes Simplex Virus type 1',
    firstLine: 'Aciclovir 10 mg/kg/8h IV × 10–15 j',
    alternative: 'Valaciclovir PO (relais)',
    duration: '10–15 jours',
    notes: 'Urgence ! Simple suspicion suffit à initier le traitement.',
  ),
  AntibioticEntry(
    disease: 'Herpès cutanéo-muqueux / Gingivostomatite',
    category: 'viral',
    agent: 'HSV-1, HSV-2',
    firstLine: 'Aciclovir IV si PO impossible\nValaciclovir 2 cp/j × 8–10 j',
    alternative: 'Traitement symptomatique (bains de bouche, réhydratation)',
    duration: '8–10 jours',
    notes: 'Immunodéprimé / NN / enceinte : Aciclovir 10 mg/kg/8h IV.',
  ),
  AntibioticEntry(
    disease: 'MNI (Mononucléose Infectieuse)',
    category: 'viral',
    agent: 'Virus Epstein-Barr (EBV)',
    firstLine: 'Traitement symptomatique uniquement\n⚠ Les antibiotiques sont inutiles',
    alternative: '⚠ Pénicillines A CONTRE-INDIQUÉES\n(éruption cutanée dans 90% des cas)',
    duration: 'Symptomatique',
    notes: 'Repos strict. Corticoïdes si tuméfaction amygdalienne importante.',
  ),
  AntibioticEntry(
    disease: 'Rage',
    category: 'viral',
    agent: 'Lyssavirus (virus de la rage)',
    firstLine: 'ATB prophylactique : Cyclines ou Amoxicilline-clavulanique × 5–10 j\n(prévention surinfection bactérienne)',
    alternative: '—',
    duration: '5–10 jours (ATB)',
    notes: 'Traitement spécifique = sérovaccination anti-rabique. Soins locaux + vérification antitétanique.',
  ),
];
