import '../models/models.dart';

List<Course> buildCourses() {
  return [
    Course(
      id: 'meningite_a_pneumocoque',
      name: 'Méningite à Pneumocoque',
      cards: [
        Flashcard(id: 'meningite_a_pneumocoque_1', question: 'Quel est l\'agent causal de la méningite à pneumocoque ?', answer: 'Streptococcus pneumoniae (diplocoque Gram positif, en flamme de bougie)'),
        Flashcard(id: 'meningite_a_pneumocoque_2', question: 'Quelle est la place du pneumocoque parmi les causes de méningite bactérienne de l\'adulte ?', answer: 'Deuxième cause après le méningocoque'),
        Flashcard(id: 'meningite_a_pneumocoque_3', question: 'Quels sont les terrains prédisposants à la méningite à pneumocoque ?', answer: 'Aspléniques, traumatisés crâniens, âges extrêmes, BPC, cirrhose'),
        Flashcard(id: 'meningite_a_pneumocoque_4', question: 'Quelles sont les portes d\'entrée classiques ?', answer: 'Oto-mastoïdite, sinusite, infection respiratoire basse, traumatisme crânien'),
        Flashcard(id: 'meningite_a_pneumocoque_5', question: 'Quelle est la durée de la phase d\'invasion ?', answer: '24 à 48 heures'),
        Flashcard(id: 'meningite_a_pneumocoque_6', question: 'Quels sont les signes du syndrome méningé ?', answer: 'Céphalées en casque, vomissements en jet, photophobie, phonophobie, raideur de nuque'),
        Flashcard(id: 'meningite_a_pneumocoque_7', question: 'Qu\'est-ce que le signe de Kernig ?', answer: 'Impossibilité de fléchir à angle droit les MI sur le tronc sans provoquer douleur lombaire + flexion des genoux'),
        Flashcard(id: 'meningite_a_pneumocoque_8', question: 'Qu\'est-ce que le signe de Brudzinski ?', answer: 'La flexion antérieure de la nuque provoque la flexion des hanches et des genoux'),
        Flashcard(id: 'meningite_a_pneumocoque_9', question: 'Quel est l\'aspect du LCR dans la méningite à pneumocoque ?', answer: 'Trouble ou purulent, hypertendu, >1000 PNA/mm3, albumine >2g/l, hypoglycorrachie'),
        Flashcard(id: 'meningite_a_pneumocoque_10', question: 'Quel est l\'aspect direct du pneumocoque au LCR ?', answer: 'Diplocoque Gram positif en flamme de bougie, encapsulé, en paires'),
        Flashcard(id: 'meningite_a_pneumocoque_11', question: 'Quelles sont les complications mécaniques de la méningite à pneumocoque ?', answer: 'Cloisonnement, HTIC, hydrocéphalie, épanchement sous-dural'),
        Flashcard(id: 'meningite_a_pneumocoque_12', question: 'Quelle est la complication neurosensorielle la plus fréquente ?', answer: 'Surdité (souvent bilatérale)'),
        Flashcard(id: 'meningite_a_pneumocoque_13', question: 'Quelles sont les particularités cliniques chez le nourrisson ?', answer: 'Tableau incomplet, fièvre inexpliquée, troubles digestifs, gémissements, bombement de la fontanelle'),
        Flashcard(id: 'meningite_a_pneumocoque_14', question: 'Quelles sont les particularités chez le sujet âgé ?', answer: 'Signes trompeurs, céphalées banales, tableau psychiatrique fébrile, syndrome méningé inconstant'),
        Flashcard(id: 'meningite_a_pneumocoque_15', question: 'Quel taux de méningites récidivantes est dû au pneumocoque ?', answer: '90%'),
      ],
    ),
    Course(
      id: 'infections_a_streptocoques',
      name: 'Infections à Streptocoques',
      cards: [
        Flashcard(id: 'infections_a_streptocoques_1', question: 'Quels sont les 2 groupes de maladies dues aux streptocoques ?', answer: '1) Streptococcies suppuratives (multiplication bactérienne) 2) Streptococcies non suppuratives (mécanisme immuno-allergique)'),
        Flashcard(id: 'infections_a_streptocoques_2', question: 'Quelle est la morphologie du streptocoque ?', answer: 'Coccies Gram positif, arrondies, groupées en paires ou chaînettes, aéro-anaérobies facultatives'),
        Flashcard(id: 'infections_a_streptocoques_3', question: 'Quelle est la classification de Lancefield ?', answer: 'Classification sérologique basée sur l\'Ag polysaccharide C de la paroi, 20 groupes de A à H et K à T'),
        Flashcard(id: 'infections_a_streptocoques_4', question: 'Quelles toxines sécrètent les streptocoques β-hémolytiques du groupe A ?', answer: 'Exotoxines érythrogènes A, B, C (responsables de la scarlatine) + enzymes : streptolysines O et S, hyaluronidases, streptokinases'),
        Flashcard(id: 'infections_a_streptocoques_5', question: 'Qu\'est-ce que les ASLO et quand sont-ils significatifs ?', answer: 'Antistreptolysines O. Taux >200 UI/ml = infection récente ou séroconversion (2 prélèvements à 15 jours)'),
        Flashcard(id: 'infections_a_streptocoques_6', question: 'Quelle est la présentation clinique de l\'angine streptococcique ?', answer: 'Début brutal, fièvre 39-40°C, dysphagie intense, amygdales tuméfiées, enduit pultacé facilement détachable'),
        Flashcard(id: 'infections_a_streptocoques_7', question: 'Quel traitement de l\'angine à streptocoque en 1ère intention ?', answer: 'Bêta-lactamines : Pénicilline V 3 Mui/j en 3 prises pendant 8 jours ou Amoxicilline 2g/j pendant 6 jours'),
        Flashcard(id: 'infections_a_streptocoques_8', question: 'Quelles sont les complications tardives de l\'angine streptococcique ?', answer: 'Syndromes post-streptococciques (RAA, GNA)'),
        Flashcard(id: 'infections_a_streptocoques_9', question: 'Comment se transmet la scarlatine ?', answer: 'Contamination directe par voie aérienne à partir d\'un scarlatin, porteur sain ou sujet atteint d\'angine streptococcique'),
        Flashcard(id: 'infections_a_streptocoques_10', question: 'Quelles sont les caractéristiques de l\'exanthème scarlatineux ?', answer: 'Érythème diffus en nappe sans intervalle de peau saine, aspect granité à la palpation, signe de Pastia aux plis'),
        Flashcard(id: 'infections_a_streptocoques_11', question: 'Qu\'est-ce que le signe de Pastia ?', answer: 'Aspect ecchymotique au niveau des plis de flexion lors de la scarlatine'),
        Flashcard(id: 'infections_a_streptocoques_12', question: 'Comment évolue la langue dans la scarlatine ?', answer: 'Initialement saburrale → rouge avec papilles saillantes (langue framboisée au 5-6ème jour) → lisse et vernissée'),
        Flashcard(id: 'infections_a_streptocoques_13', question: 'Quelle est la phase de desquamation dans la scarlatine ?', answer: 'Débute au tronc (petites écailles), puis visage, puis membres en lambeaux (aspect en doigt de gant aux extrémités)'),
        Flashcard(id: 'infections_a_streptocoques_14', question: 'Quelles sont les complications toxiniques précoces de la scarlatine ?', answer: 'Néphrite (protéinurie, hyperazotémie) et rhumatisme (poly-arthralgies)'),
      ],
    ),
    Course(
      id: 'sepsis_a_bgn',
      name: 'Sepsis à BGN',
      cards: [
        Flashcard(id: 'sepsis_a_bgn_1', question: 'Définition du sepsis à BGN ?', answer: 'Dysfonction d\'organe menaçant le pronostic vital causée par une réponse inappropriée de l\'hôte à une infection par un BGN'),
        Flashcard(id: 'sepsis_a_bgn_2', question: 'Critères diagnostiques du sepsis (Sepsis-3) ?', answer: 'Infection suspectée ou documentée + augmentation du score SOFA ≥ 2 points'),
        Flashcard(id: 'sepsis_a_bgn_3', question: 'Qu\'est-ce que le qSOFA et quand est-il positif ?', answer: 'Quick SOFA : FR ≥ 22/min + altération conscience (GCS<15) + PAS ≤ 100 mmHg. Positif si ≥ 2 points'),
        Flashcard(id: 'sepsis_a_bgn_4', question: 'Critères du choc septique à BGN ?', answer: 'Sepsis + hypotension persistante nécessitant vasopresseurs pour PAM ≥ 65 mmHg + lactatémie > 2 mmol/L'),
        Flashcard(id: 'sepsis_a_bgn_5', question: 'Quels sont les principaux BGN responsables de sepsis ?', answer: 'E. coli, Klebsiella pneumoniae, Enterobacter, Serratia, Pseudomonas aeruginosa, Acinetobacter baumannii'),
        Flashcard(id: 'sepsis_a_bgn_6', question: 'Quelle est la porte d\'entrée la plus fréquente dans les sepsis à BGN ?', answer: 'Urinaire (pyélonéphrite, obstacle, sondage vésical)'),
        Flashcard(id: 'sepsis_a_bgn_7', question: 'Quels sont les 2 signes cliniques évocateurs d\'étiologie BGN ?', answer: 'Diarrhée et hyperventilation'),
        Flashcard(id: 'sepsis_a_bgn_8', question: 'Qu\'est-ce que l\'ecthyma gangreneux d\'Ehlers ?', answer: 'Lésion pathognomonique des septicémies à Pseudomonas : macule → papule → vésicule → escarre noirâtre entourée d\'halo érythémateux'),
        Flashcard(id: 'sepsis_a_bgn_9', question: 'Quels mécanismes physiopathologiques sont impliqués dans le choc à BGN ?', answer: 'LPS activent TLR4 → cytokines pro-inflammatoires (TNF-α, IL-1, IL-6) → activation coagulation (CIVD) → ischémie tissulaire'),
        Flashcard(id: 'sepsis_a_bgn_10', question: 'Que contient le LPS des BGN et quel est son rôle ?', answer: 'Lipopolysaccharide de la membrane externe → active le système immunitaire et induit le SIRS et le choc'),
        Flashcard(id: 'sepsis_a_bgn_11', question: 'Quel est le traitement du choc septique dans les premières 6h ?', answer: 'Remplissage 30 mL/kg cristalloïdes + noradrénaline (vasopresseur de 1ère ligne) + antibiothérapie empirique < 1h'),
        Flashcard(id: 'sepsis_a_bgn_12', question: 'Quels sont les BGN multirésistants à connaître ?', answer: 'Producteurs de BLSE, carbapénémases (KPC, NDM, OXA-48), AmpC hyperproducteurs'),
      ],
    ),
    Course(
      id: 'meningococcies',
      name: 'Méningococcies',
      cards: [
        Flashcard(id: 'meningococcies_1', question: 'Définition des méningococcies ?', answer: 'Infections invasives à Neisseria meningitidis : méningites cérébro-spinales, septicémies, rarement arthrites/péricardites/bronchopneumonies'),
        Flashcard(id: 'meningococcies_2', question: 'Caractères bactériologiques de Neisseria meningitidis ?', answer: 'Diplocoque Gram négatif en grain de café, encapsulé, très fragile dans le milieu extérieur, 13 sérogroupes'),
        Flashcard(id: 'meningococcies_3', question: 'Quels sérogroupes sont responsables des épidémies en Afrique ?', answer: 'A, C, W135, X (90% des méningococcies épidémiques en Afrique sub-saharienne)'),
        Flashcard(id: 'meningococcies_4', question: 'Quel sérogroupe est fréquent en Europe et en Algérie ?', answer: 'B (fréquent en Europe/France et USA). En Algérie : B, C, A, W135'),
        Flashcard(id: 'meningococcies_5', question: 'Quel est le réservoir et le mode de transmission ?', answer: 'Humain (malades, porteurs sains - 10-20% portage rhino-pharyngé). Transmission par gouttelettes de salive (Pflügge)'),
        Flashcard(id: 'meningococcies_6', question: 'Quelle est la durée de l\'incubation de la MCS ?', answer: 'Silencieuse, 2 à 4 jours'),
        Flashcard(id: 'meningococcies_7', question: 'Quels sont les signes d\'orientation (SHARP) ?', answer: 'SPM, Herpès labial, Arthralgies/arthrites, Rash morbilliforme, Purpura punctiforme ou généralisé'),
        Flashcard(id: 'meningococcies_8', question: 'Quels sont les signes cliniques de gravité dans la MCS ?', answer: 'Purpura généralisé extensif, choc septique, troubles neurologiques (convulsions, trouble de conscience, coma)'),
        Flashcard(id: 'meningococcies_9', question: 'Comment est le LCR dans la méningite à méningocoque ?', answer: 'Hypertendu, trouble/eau de riz/purulent, >1000 PNA/mm3, albumine >1g/l, hypoglycorrachie'),
        Flashcard(id: 'meningococcies_10', question: 'À l\'examen direct du LCR, comment apparaît le méningocoque ?', answer: 'Cocci Gram négatif en grain de café, intra et extracellulaire'),
        Flashcard(id: 'meningococcies_11', question: 'Quelle est l\'évolution sous traitement de la MCS ?', answer: 'Favorable dans 99% : apyrexie en 2-3 jours, disparition vomissements en 2j, guérison en 8-10 jours'),
        Flashcard(id: 'meningococcies_12', question: 'Quelle est la complication neurosensorielle la plus fréquente de la MCS ?', answer: 'Surdité bilatérale définitive'),
        Flashcard(id: 'meningococcies_13', question: 'Quelles sont les complications immuno-allergiques de la méningococcémie ?', answer: 'Péricardite, arthrites, iridocyclite (vers J5-J8 sous amoxicilline) → traitement par corticoïdes'),
        Flashcard(id: 'meningococcies_14', question: 'Comment se manifeste la méningite à méningocoque chez le nourrisson ?', answer: 'Atypique : fièvre inexpliquée, GEA, convulsion fébrile, refus de téter, FA bombante, nuque molle, hypotonie'),
      ],
    ),
    Course(
      id: 'choc_septique',
      name: 'Choc Septique',
      cards: [
        Flashcard(id: 'choc_septique_1', question: 'Définition du choc septique (Sepsis-3, 2016) ?', answer: 'Sepsis + vasopresseurs pour PAM ≥ 65 mmHg + lactates > 2 mmol/l (18 mg/dl) malgré remplissage adéquat'),
        Flashcard(id: 'choc_septique_2', question: 'Quelle est la différence entre les définitions de 1992 et 2016 du sepsis ?', answer: '1992: SIRS + infection. 2016 (Sepsis-3): dysfonction d\'organe (SOFA ≥ 2) + réponse dérégulée à infection. SIRS et \'sepsis sévère\' abandonnés'),
        Flashcard(id: 'choc_septique_3', question: 'Quels organes explore le score SOFA ?', answer: 'Respiratoire (PaO2), coagulation (plaquettes), hépatique (bilirubine), rénal (créatinine), cardiovasculaire (TA), neurologique (Glasgow)'),
        Flashcard(id: 'choc_septique_4', question: 'Quelle est la mortalité du choc septique ?', answer: 'Environ 40% (mortalité hospitalière du sepsis : 15-30%)'),
        Flashcard(id: 'choc_septique_5', question: 'Quelles bactéries sont les plus fréquentes dans le choc septique ?', answer: 'BGN (62%), Cocci Gram positif (46%), Candida (15%), Anaérobies (4%)'),
        Flashcard(id: 'choc_septique_6', question: 'Qu\'est-ce que la phase hyperkinétique (choc chaud) ?', answer: 'PA systolique normale ou peu abaissée, tachycardie, extrémités chaudes, premiers signes viscéraux (polypnée, oligurie)'),
        Flashcard(id: 'choc_septique_7', question: 'Qu\'est-ce que la phase hypokinétique (choc froid) ?', answer: 'PA systolique basse, tachycardie avec pouls filant, extrémités froides/cyanosées, marbrures, trouble conscience'),
        Flashcard(id: 'choc_septique_8', question: 'Quelles sont les conséquences rénales du choc septique ?', answer: 'Insuffisance rénale aiguë fonctionnelle évoluant vers l\'organicité dans 10% des cas'),
        Flashcard(id: 'choc_septique_9', question: 'Qu\'est-ce que le SDRA dans le choc septique ?', answer: 'Syndrome de détresse respiratoire aiguë : polypnée, cyanose, agitation → OAP lésionnel, hypoxémie, hypocapnie'),
        Flashcard(id: 'choc_septique_10', question: 'Quels sont les signes cliniques traduisant l\'hypoperfusion tissulaire ?', answer: 'Marbrures (genoux), froideur des extrémités, pâleur/teint livide, TRC > 3 secondes, oligurie < 0.5 ml/kg/h'),
        Flashcard(id: 'choc_septique_11', question: 'Quel est le premier vasopresseur à utiliser dans le choc septique ?', answer: 'Noradrénaline en 1ère intention (adrénaline ou vasopressine en 2ème ligne)'),
        Flashcard(id: 'choc_septique_12', question: 'Quelles anomalies hématologiques peut-on voir dans le choc septique ?', answer: 'Thrombopénie + TP < 50% + fibrinogène < 3g/l = CIVD induite par l\'endotoxine'),
      ],
    ),
    Course(
      id: 'cholera',
      name: 'Choléra',
      cards: [
        Flashcard(id: 'cholera_1', question: 'Qu\'est-ce que le choléra ?', answer: 'Toxi-infection intestinale aiguë, strictement humaine, hautement contagieuse, à transmission hydrique (péril fécal), déclaration obligatoire'),
        Flashcard(id: 'cholera_2', question: 'Quel est l\'agent causal du choléra ?', answer: 'Vibrion cholérique (Vibrio cholerae), Bacille Gram négatif, très mobile (flagelle), sérogroupes O1 et O139'),
        Flashcard(id: 'cholera_3', question: 'Quels sont les 2 biotypes du sérogroupe O1 ?', answer: 'Classique (6 premières pandémies) et El Tor (7ème pandémie actuelle)'),
        Flashcard(id: 'cholera_4', question: 'Quels sont les 3 sérotypes du vibrion cholérique O1 ?', answer: 'Ogawa (ab), Inaba (ac), Hikojima (abc)'),
        Flashcard(id: 'cholera_5', question: 'Comment le vibrion produit-il la diarrhée ?', answer: 'Exotoxine entérotoxinique → stimulation adénylcyclase → ↑ AMPcyclique → ↑ sécrétion Cl- → fuite d\'eau (diarrhée sécrétoire)'),
        Flashcard(id: 'cholera_6', question: 'Quelle est la durée de l\'incubation du choléra ?', answer: '4H à 5 jours (selon l\'inoculum)'),
        Flashcard(id: 'cholera_7', question: 'Quelles sont les caractéristiques des selles dans le choléra ?', answer: 'Profuses, aqueuses, afécales, couleur eau de riz, flocons blanchâtres, 50-100 selles/j, 0.5-1L/h, sans glaires ni sang ni pus'),
        Flashcard(id: 'cholera_8', question: 'Quels sont les éléments cardinaux du choléra ?', answer: '1. Conscient 2. Apyrétique 3. Pas de glaires 4. Pas de pus 5. Pas de sang'),
        Flashcard(id: 'cholera_9', question: 'Comment se présentent les signes de déshydratation dans le choléra ?', answer: 'Globes oculaires excavés, joues creuses, lèvres crispées, langue rôtie, peau atone avec pli cutané, voix bitonale'),
        Flashcard(id: 'cholera_10', question: 'Comment évolue le choléra sans traitement ?', answer: 'Toujours mortel par déshydratation (15-20%)'),
        Flashcard(id: 'cholera_11', question: 'Quelle est la complication métabolique principale du choléra ?', answer: 'Perte de bicarbonate → acidose métabolique ; perte de K+ → troubles du rythme cardiaque'),
        Flashcard(id: 'cholera_12', question: 'Quelle épidémie de choléra a touché l\'Algérie récemment ?', answer: '2018 : Blida, Bouira, Tipaza (74 cas, 2 décès, O1 sérotype Ogawa)'),
      ],
    ),
    Course(
      id: 'fievre_typhoïde',
      name: 'Fièvre Typhoïde',
      cards: [
        Flashcard(id: 'fievre_typhoïde_1', question: 'Qu\'est-ce que la fièvre typhoïde ?', answer: 'Toxi-infection à transmission hydrique endémo-épidémique due à Salmonella typhi ou paratyphi A, B, C'),
        Flashcard(id: 'fievre_typhoïde_2', question: 'Quelles sont les caractéristiques de Salmonella typhi ?', answer: 'BGN mobile aéroanaérobie facultatif, 3 antigènes : LPS somatique (O), flagellaire (H), capsulaire (Vi)'),
        Flashcard(id: 'fievre_typhoïde_3', question: 'Quel est le réservoir de la fièvre typhoïde ?', answer: 'Strictement humain : malades durant toute la maladie, convalescents, porteurs sains'),
        Flashcard(id: 'fievre_typhoïde_4', question: 'Quelle est la durée de l\'incubation ?', answer: 'Silencieuse, variable, en moyenne 15 jours (7-21 jours)'),
        Flashcard(id: 'fievre_typhoïde_5', question: 'Comment progresse la fièvre au 1er septénaire ?', answer: 'Augmente par oscillations ascendantes de 1°C/jour (matin-soir), remonte à 39-40°C en fin de semaine'),
        Flashcard(id: 'fievre_typhoïde_6', question: 'Qu\'est-ce que l\'angine de Duguet ?', answer: 'Exulcération indolore, ovalaire, longitudinale, grand axe vertical, au niveau du pilier antérieur du voile du palais. Pathognomonique mais inconstante'),
        Flashcard(id: 'fievre_typhoïde_7', question: 'Qu\'est-ce que le tuphos ?', answer: 'Obnubilation + stupeur, prostration, indifférence, insomnie nocturne et somnolence diurne avec délire vespéral, mouvements carphologiques'),
        Flashcard(id: 'fievre_typhoïde_8', question: 'Qu\'est-ce que les taches rosées lenticulaires (TRL) ?', answer: 'Macules rosées de quelques mm, sans prurit, s\'effaçant à la vitropression, siège : base du thorax, abdomen supérieur. Pathognomoniques'),
        Flashcard(id: 'fievre_typhoïde_9', question: 'Qu\'est-ce que le signe de Faget ?', answer: 'Dissociation pouls/température (fièvre élevée sans tachycardie correspondante)'),
        Flashcard(id: 'fievre_typhoïde_10', question: 'Quand et comment se font les hémorragies intestinales dans la FT ?', answer: '3ème septénaire. Minimes (pâleur, anémie) ou abondantes (melæna)'),
        Flashcard(id: 'fievre_typhoïde_11', question: 'Comment diagnostiquer une perforation intestinale dans la FT en tuphos ?', answer: 'NFS : hyperleucocytose à PNN + ASP : croissant clair gazeux sous diaphragmatique (pneumopéritoine)'),
        Flashcard(id: 'fievre_typhoïde_12', question: 'Quel examen diagnostique au 1er septénaire ?', answer: 'Hémoculture (positive dans 80-90% au 1er septénaire)'),
        Flashcard(id: 'fievre_typhoïde_13', question: 'Quel examen diagnostique au 2ème septénaire ?', answer: 'Coproculture (bactéries présentes dans les selles)'),
        Flashcard(id: 'fievre_typhoïde_14', question: 'Quelle est l\'incidence de la FT en Algérie (2023) ?', answer: '0.06 cas pour 100 000 habitants = 22 cas (2023)'),
      ],
    ),
    Course(
      id: 'fievre_typhoïde_paratyphoïde',
      name: 'Fièvre Typhoïde - Paratyphoïde',
      cards: [
        Flashcard(id: 'fievre_typhoïde_paratyphoïde_1', question: 'Différence entre FT et fièvre paratyphoïde ?', answer: 'Paratyphoïde (S. paratyphi) : moins de signes toxiniques, tableau de TIAC, pas de TRL'),
        Flashcard(id: 'fievre_typhoïde_paratyphoïde_2', question: 'Quelle est la physiopathologie de la FT (résumé) ?', answer: 'Inoculum ≥ 10⁵ → intestin grêle (plaques de Peyer, 1ère multiplication) → canal thoracique → bactériémie + 2ème multiplication (foie, rate, MO) → libération endotoxines'),
        Flashcard(id: 'fievre_typhoïde_paratyphoïde_3', question: 'Quelles sont les formes selon le terrain ?', answer: 'Nourrisson : gastroentérite + déshydratation; Enfant : début brutal, NFS hyperleucocytose; Femme enceinte : avortements si non traitée; Vieillard : manifestations CV et pulmonaires'),
        Flashcard(id: 'fievre_typhoïde_paratyphoïde_4', question: 'Quelle est la mortalité de la FT selon le contexte ?', answer: '< 1% si diagnostic et traitement précoces dans les pays développés. Jusqu\'à 30% dans les PED avec retard diagnostique'),
      ],
    ),
    Course(
      id: 'leptospirose',
      name: 'Leptospirose',
      cards: [
        Flashcard(id: 'leptospirose_1', question: 'Qu\'est-ce que la leptospirose ?', answer: 'Anthropozoonose bactérienne due à des spirochètes du genre Leptospira, transmise par l\'urine d\'animaux infectés, tropisme hépatique, rénal et méningé'),
        Flashcard(id: 'leptospirose_2', question: 'Quelle espèce de Leptospira est pathogène pour l\'homme ?', answer: 'Leptospira interrogans (saprophyte : Leptospira biflexa)'),
        Flashcard(id: 'leptospirose_3', question: 'Quel sérogroupe est responsable des formes les plus graves ?', answer: 'Leptospira ictero-haemorrhagiae'),
        Flashcard(id: 'leptospirose_4', question: 'Quel est le principal réservoir de la leptospirose ?', answer: 'Le rat et les rongeurs sauvages (porteurs sains). Aussi : chiens, bovins, porcs, moutons, chèvres'),
        Flashcard(id: 'leptospirose_5', question: 'Comment se fait la contamination chez l\'homme ?', answer: 'Indirecte via excoriations cutanées ou muqueuses au contact d\'eau/sol souillé par urines d\'animaux infectés'),
        Flashcard(id: 'leptospirose_6', question: 'Quels sont les facteurs de risque professionnels ?', answer: 'Agriculteurs, égoutiers, employés abattoirs, pisciculteurs, jardiniers, éboueurs, loisirs aquatiques (kayak, rafting, pêche)'),
        Flashcard(id: 'leptospirose_7', question: 'Quelle est la sex-ratio de la leptospirose ?', answer: '9/1 (prédominance masculine)'),
        Flashcard(id: 'leptospirose_8', question: 'Qu\'est-ce que la leptospirose ictéro-hémorragique (maladie de Weil) ?', answer: 'Forme typique grave : fièvre + ictère \'flamboyant\' (orangé) + syndrome rénal + syndrome hémorragique + syndrome méningé'),
        Flashcard(id: 'leptospirose_9', question: 'Qu\'est-ce que la mnémotechnique RIMIS ?', answer: 'Les 5 syndromes de la leptospirose : Rénal, Ictère, Méningé, Infectieux, Sang (hémorragique)'),
        Flashcard(id: 'leptospirose_10', question: 'Comment est l\'injection conjonctivale dans la leptospirose ?', answer: 'Bilatérale et très caractéristique (hyperhémie conjonctivale bilatérale)'),
        Flashcard(id: 'leptospirose_11', question: 'Quelle est la physiopathologie de la leptospirose ?', answer: '2 phases : 1) Phase septicémique (bactériémie, dissémination foie/reins/LCR) 2) Phase immunologique (apparition IgM dès J8, élimination urinaire dès J12)'),
        Flashcard(id: 'leptospirose_12', question: 'Quels sont les marqueurs biologiques spécifiques ?', answer: 'Hyperleucocytose PNN, thrombopénie, hyperbilirubinémie conjuguée, transaminases élevées, CPK élevées (rhabdomyolyse), insuffisance rénale'),
        Flashcard(id: 'leptospirose_13', question: 'Quelle est la méthode de référence sérologique ?', answer: 'MAT (Microscopic Agglutination Test) ou Réaction de Martin et Petit. Positive dès J10, seuil 1/100'),
        Flashcard(id: 'leptospirose_14', question: 'Quels sont les facteurs de mauvais pronostic ?', answer: 'Ictère, insuffisance rénale aiguë, atteinte pulmonaire grave, troubles du rythme à l\'ECG, altération conscience, âge > 60 ans'),
      ],
    ),
    Course(
      id: 'dermohypodermites_dhab',
      name: 'Dermohypodermites (DHAB)',
      cards: [
        Flashcard(id: 'dermohypodermites_dhab_1', question: 'Qu\'est-ce qu\'une dermohypodermite bactérienne ?', answer: 'Infection cutanée aiguë atteignant le derme et l\'hypoderme, due principalement au streptocoque β-hémolytique du groupe A (85%)'),
        Flashcard(id: 'dermohypodermites_dhab_2', question: 'Quelle est la différence entre DHBNN et DHBN ?', answer: 'DHBNN (érysipèle) = non nécrosante, fréquente, bénigne, traitement ATB. DHBN (fasciite nécrosante) = urgence médico-chirurgicale, mortalité 30%'),
        Flashcard(id: 'dermohypodermites_dhab_3', question: 'Quels sont les facteurs de risque de l\'érysipèle ?', answer: 'ATCD d\'érysipèle, obésité, œdème (insuffisance veineuse/lymphatique), porte d\'entrée cutanée (intertrigo inter-orteil +++)'),
        Flashcard(id: 'dermohypodermites_dhab_4', question: 'Quelle est la présentation classique de l\'érysipèle ?', answer: 'Grosse jambe rouge aiguë fébrile : placard inflammatoire unilatéral avec bourrelet périphérique, début brutal, extension rapide'),
        Flashcard(id: 'dermohypodermites_dhab_5', question: 'Quelle est la localisation la plus fréquente de l\'érysipèle ?', answer: 'Membres inférieurs (90%), puis visage (5-10%)'),
        Flashcard(id: 'dermohypodermites_dhab_6', question: 'Quel traitement de l\'érysipèle en 1ère intention ?', answer: 'Amoxicilline 50 mg/kg/j en 3 prises pendant 7 jours per os. Si allergie : Pristinamycine 3g/j ou Clindamycine 600mg×3/j'),
        Flashcard(id: 'dermohypodermites_dhab_7', question: 'Quelles sont les complications à court terme de l\'érysipèle ?', answer: 'Suppurations locales, sepsis, fasciite nécrosante (placards purpuriques, bulles hémorragiques, nécrose)'),
        Flashcard(id: 'dermohypodermites_dhab_8', question: 'Quelle complication à moyen terme après érysipèle ?', answer: 'Syndrome post-streptococcique : GNA (glomérulonéphrite aiguë) +++ , RAA'),
        Flashcard(id: 'dermohypodermites_dhab_9', question: 'Quels sont les critères d\'hospitalisation urgente pour érysipèle ?', answer: 'Signes de gravité locaux ou généraux, risque décompensation comorbidité, obésité morbide (IMC>40), âge >75 ans poly-pathologique'),
        Flashcard(id: 'dermohypodermites_dhab_10', question: 'Comment prévenir les récidives d\'érysipèle ?', answer: 'Traiter la porte d\'entrée, contention veinoymphathique, antibioprophylaxie (benzathine benzyl-pénicilline G) si ≥2 épisodes/an'),
        Flashcard(id: 'dermohypodermites_dhab_11', question: 'Quels sont les facteurs de risque de la fasciite nécrosante ?', answer: 'Âge >60 ans, diabète déséquilibré, obésité (IMC>30), AOMI, toxicomanie IV, maladies cardiovasculaires, immunodépression'),
        Flashcard(id: 'dermohypodermites_dhab_12', question: 'Qu\'est-ce que la gangrène de Fournier ?', answer: 'Fasciite nécrosante périnéale, favorisée par infections urinaires, sténose urétrale, infections dermatologiques périnéales'),
        Flashcard(id: 'dermohypodermites_dhab_13', question: 'Quel est le traitement de la fasciite nécrosante ?', answer: 'URGENCE médico-chirurgicale : débridement chirurgical large + ATB IV à fortes doses (14-21j) + réanimation'),
      ],
    ),
    Course(
      id: 'infection_a_vih',
      name: 'Infection à VIH',
      cards: [
        Flashcard(id: 'infection_a_vih_1', question: 'Définition de l\'infection à VIH ?', answer: 'Infection chronique par un rétrovirus (ARN) qui s\'attaque aux LT CD4+. Transmission sexuelle (80%), sanguine, mère-enfant'),
        Flashcard(id: 'infection_a_vih_2', question: 'Définition du SIDA ?', answer: 'Ensemble de pathologies secondaires à un déficit immunitaire en rapport avec le VIH : infections opportunistes + cancers'),
        Flashcard(id: 'infection_a_vih_3', question: 'Quelle est la différence entre VIH-1 et VIH-2 ?', answer: 'VIH-1 = pandémique (mondial). VIH-2 = principalement en Afrique de l\'Ouest'),
        Flashcard(id: 'infection_a_vih_4', question: 'Quel est le risque relatif de transmission par rapports homosexuels ?', answer: '×22 (très haut risque)'),
        Flashcard(id: 'infection_a_vih_5', question: 'Quelle est la structure du VIH ?', answer: 'Virus enveloppé à ARN monocaténaire, famille des rétrovirus, cycle : attachement/fusion → transcription inverse → intégration → transcription/traduction → assemblage'),
        Flashcard(id: 'infection_a_vih_6', question: 'Quelles sont les modes de transmission mère-enfant ?', answer: 'In-utéro T2-T3 (5%), accouchement/voie basse (15%), allaitement naturel (10%). Prévention : ARV précoce + césarienne'),
        Flashcard(id: 'infection_a_vih_7', question: 'Quelle est l\'IST qui multiplie le risque de transmission par 30 ?', answer: 'Les IST ulcérantes (×30). Multiplicité des partenaires ×13'),
        Flashcard(id: 'infection_a_vih_8', question: 'Quelle est la prévalence mondiale du VIH en 2023 ?', answer: '39 millions de personnes vivant avec le VIH. 1.3 million nouvelles infections. 630 000 décès liés au SIDA'),
        Flashcard(id: 'infection_a_vih_9', question: 'Quel continent concentre le plus de cas de VIH ?', answer: 'Afrique orientale et australe (20.8 millions de personnes)'),
        Flashcard(id: 'infection_a_vih_10', question: 'Pourquoi n\'y a-t-il pas de guérison avec le traitement ARV ?', answer: 'Le traitement réduit la charge virale et la transmission mais ne permet pas la guérison (réservoir viral persistant)'),
      ],
    ),
    Course(
      id: 'coqueluche',
      name: 'Coqueluche',
      cards: [
        Flashcard(id: 'coqueluche_1', question: 'Qu\'est-ce que la coqueluche ?', answer: 'Toxi-infection bactérienne de l\'arbre respiratoire, strictement humaine, hautement contagieuse, déclaration obligatoire. Agent : Bordetella pertussis'),
        Flashcard(id: 'coqueluche_2', question: 'Caractères de Bordetella pertussis ?', answer: 'Coccobacille Gram négatif, encapsulé, aérobie strict, extracellulaire (sécrète toxines et adhésines), culture sur milieu Bordet-Gengou'),
        Flashcard(id: 'coqueluche_3', question: 'Quel est le mécanisme de la paralysie ciliaire dans la coqueluche ?', answer: 'Toxine cyto-trachéale : détruit le mécanisme de clairance ciliaire et empêche sa réparation'),
        Flashcard(id: 'coqueluche_4', question: 'Quelle est la durée de l\'incubation ?', answer: 'En moyenne 10 jours (7 à 21 jours), silencieuse'),
        Flashcard(id: 'coqueluche_5', question: 'Qu\'est-ce que la phase catarrhale ?', answer: 'Très contagieuse ! Durée 1-2 semaines. Toux banale, rhinorrhée, fièvre modérée < 38.5°C (ressemble à une infection virale)'),
        Flashcard(id: 'coqueluche_6', question: 'Comment se définit une quinte de coqueluche ?', answer: 'Secousses expiratoires répétées (cyanose) → apnée → reprise inspiratoire profonde (chant du coq) → expectoration → répétition 4-5 fois'),
        Flashcard(id: 'coqueluche_7', question: 'Quelle est la fréquence maximale des quintes ?', answer: 'Jusqu\'à 50 fois par jour, à prédominance nocturne'),
        Flashcard(id: 'coqueluche_8', question: 'Quel est le tableau biologique caractéristique de la coqueluche ?', answer: 'FNS : hyperleucocytose avec hyperlymphocytose (60-90%). CRP normale ou peu élevée (maladie toxinique)'),
        Flashcard(id: 'coqueluche_9', question: 'Comment confirmer le diagnostic biologique de coqueluche ?', answer: 'Écouvillonnage nasopharyngé pour : culture (PCR+++), ou sérologie (anticorps spécifiques anti-Bordetella pertussis)'),
        Flashcard(id: 'coqueluche_10', question: 'Quelle est la forme grave chez le nourrisson < 3 mois ?', answer: 'Forme maligne apneisante : tachycardie >200 bpm, détresse respiratoire, hyperlymphocytose majeure, mortalité 75%'),
        Flashcard(id: 'coqueluche_11', question: 'Quelles sont les complications respiratoires de la coqueluche ?', answer: 'Pneumo-coqueluche, bronchopneumonie suraiguë, emphysème, dilatation des bronches, laryngite, pleurésie'),
        Flashcard(id: 'coqueluche_12', question: 'Quelles sont les complications mécaniques de la coqueluche ?', answer: 'Ulcération frein de langue, purpura cervico-facial, hémorragies conjonctivales, prolapsus rectal, hernie ombilicale'),
        Flashcard(id: 'coqueluche_13', question: 'L\'antibiothérapie est-elle efficace dans toutes les phases ?', answer: 'Non, efficace seulement en phase catarrhale. En phase de quintes, elle réduit la contagiosité mais pas la durée des quintes'),
      ],
    ),
    Course(
      id: 'paludisme',
      name: 'Paludisme',
      cards: [
        Flashcard(id: 'paludisme_1', question: 'Quelles sont les 5 espèces de Plasmodium pathogènes pour l\'homme ?', answer: 'P. falciparum, P. vivax, P. malariae, P. ovale, P. knowlesi'),
        Flashcard(id: 'paludisme_2', question: 'Quelle espèce est la plus grave et pourquoi ?', answer: 'P. falciparum : schizogonie dans les capillaires viscéraux (notamment cérébraux), parasite toutes les hématies, parasitémie potentiellement élevée'),
        Flashcard(id: 'paludisme_3', question: 'Comment se transmet le paludisme ?', answer: 'Piqûre de l\'anophèle femelle (indolore, nocturne). Rarement : transfusion, greffe, transplacentaire, toxicomanie IV'),
        Flashcard(id: 'paludisme_4', question: 'Quelle est la durée d\'incubation selon l\'espèce ?', answer: 'P. falciparum : 7-14j, P. vivax : 10-20j, P. ovale : 15-18j, P. malariae : 18-40j, P. knowlesi : 10-15j'),
        Flashcard(id: 'paludisme_5', question: 'Qu\'est-ce que l\'accès palustre de reviviscence ?', answer: 'Trilogie stéréotypée : frissons (1h) → chaleur 40-41°C (3-4h) → sueurs abondantes (2-4h). Se répète selon un rythme régulier'),
        Flashcard(id: 'paludisme_6', question: 'Quelle est la périodicité des accès selon l\'espèce ?', answer: 'Tierce (J1-J3-J5) pour P. falciparum, P. vivax, P. ovale. Quarte (J1-J4-J7) pour P. malariae. Tous les jours pour P. knowlesi'),
        Flashcard(id: 'paludisme_7', question: 'Qu\'est-ce que le paludisme grave ?', answer: 'Apanage de P. falciparum. Au moins 1 critère OMS : coma (neuropaludisme), convulsions, hypoglycémie, insuffisance rénale, SDRA, anémie sévère...'),
        Flashcard(id: 'paludisme_8', question: 'Qu\'est-ce que la prémunition ?', answer: 'Immunité relative acquise progressivement en 5-10 ans, labile (disparaît en 12-24 mois si quitte la zone). Équilibre hôte-parasite'),
        Flashcard(id: 'paludisme_9', question: 'Comment diagnostique-t-on le paludisme ?', answer: 'Frottis sanguin + goutte épaisse (visualisation du plasmodium). TDR (test diagnostic rapide). PCR'),
        Flashcard(id: 'paludisme_10', question: 'Qu\'est-ce que la fièvre bilieuse hémoglobinurique ?', answer: 'Complication rare d\'hémolyse aiguë chez sujets vivant en zone endémique sous prophylaxie incomplète par quinine/méfloquine'),
        Flashcard(id: 'paludisme_11', question: 'Quel est le risque du paludisme chez la femme enceinte ?', answer: 'Fréquent surtout au 3ème trimestre, grave : avortement, accouchement prématuré, hypotrophie fœtale'),
        Flashcard(id: 'paludisme_12', question: 'Quelle est la situation du paludisme en Algérie ?', answer: 'Quelques foyers résiduels autochtones (Djanet, Ain Defla, Ouargla). La majorité des cas sont des paludismes d\'importation (98%)'),
      ],
    ),
    Course(
      id: 'toxoplasmose',
      name: 'Toxoplasmose',
      cards: [
        Flashcard(id: 'toxoplasmose_1', question: 'Qu\'est-ce que la toxoplasmose ?', answer: 'Anthropozoonose cosmopolite due à Toxoplasma gondii (protozoaire intracellulaire). Hôte définitif : chat. Bénigne chez l\'immunocompétent, grave chez l\'immunodéprimé et la femme enceinte séronégative'),
        Flashcard(id: 'toxoplasmose_2', question: 'Quelles sont les 3 formes de Toxoplasma gondii ?', answer: '1) Tachyzoïte (trophozoïte) : phase aiguë, fragile. 2) Bradyzoïte dans kyste : phase chronique, tissus nerveux/musculaire/rétine. 3) Oocyste : forme sexuée résistante, dans l\'intestin du chat'),
        Flashcard(id: 'toxoplasmose_3', question: 'Quelles sont les voies de contamination de l\'homme ?', answer: '1) Ingestion oocystes (crudités, eau souillée, litière de chat) 2) Ingestion de kystes (viande crue/mal cuite) 3) Voie transplacentaire (primo-infection maternelle)'),
        Flashcard(id: 'toxoplasmose_4', question: 'Comment se présente la toxoplasmose chez l\'immunocompétent ?', answer: '80% asymptomatique. Si symptomatique : fièvre modérée 38°C, polyadénopathies cervicales, asthénie, myalgies. Biologie : syndrome mononucléosique. Évolution bénigne'),
        Flashcard(id: 'toxoplasmose_5', question: 'À quel taux de CD4 survient la neurotoxoplasmose chez le VIH ?', answer: 'CD4 < 200/mm³'),
        Flashcard(id: 'toxoplasmose_6', question: 'Quel est l\'aspect typique de la neurotoxoplasmose à l\'imagerie ?', answer: 'Image en cocarde : centre hypodense (nécrose) entouré d\'hyperdensité prenant le contraste, halo hypodense périphérique (œdème) à la TDM/IRM'),
        Flashcard(id: 'toxoplasmose_7', question: 'Comment la toxoplasmose congénitale varie-t-elle selon le trimestre ?', answer: '1er trimestre : rare mais très grave (encéphalomyélite, calcifications intracrâniennes, hydrocéphalie). 3ème trimestre : fréquent mais moins grave, souvent latent'),
        Flashcard(id: 'toxoplasmose_8', question: 'Quand les IgM et IgG apparaissent-ils dans la toxoplasmose ?', answer: 'IgM : dès J7 (disparaissent en 12 mois). IgA : disparaissent en 3-6 mois. IgG : J7-21 après IgM, maximum à 2 mois, persistent à vie'),
        Flashcard(id: 'toxoplasmose_9', question: 'Quelle est la triade de la toxoplasmose congénitale grave ?', answer: 'Hydrocéphalie + choriorétinite + calcifications intracrâniennes'),
        Flashcard(id: 'toxoplasmose_10', question: 'Quel est le principal moyen de prévention chez la femme enceinte séronégative ?', answer: 'Hygiène alimentaire : éviter viande crue, laver les crudités, éviter contact litière de chat, se laver les mains'),
      ],
    ),
    Course(
      id: 'fievre_boutonneuse_mediterraneenne_fbm',
      name: 'Fièvre Boutonneuse Méditerranéenne (FBM)',
      cards: [
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_1', question: 'Qu\'est-ce que la FBM ?', answer: 'Infection due à Rickettsia conorii (cocco-bacille Gram négatif intracellulaire strict), transmise par la tique du chien Rhipicephalus sanguineus'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_2', question: 'Quel est le vecteur de la FBM ?', answer: 'La tique du chien Rhipicephalus sanguineus (acarien hématophage), transmission après 20h de fixation'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_3', question: 'Quelle est la période de survenue de la FBM ?', answer: 'Estivale (mai à septembre), pourtour méditerranéen'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_4', question: 'Quelle est la physiopathogénie de la FBM ?', answer: 'Inoculation par la tique → pénétration dans les cellules endothéliales des petits vaisseaux → multiplication → vascularite + bactériémie'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_5', question: 'Quelle est la durée de l\'incubation ?', answer: '3 à 16 jours (6 jours en moyenne)'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_6', question: 'Qu\'est-ce que la tache noire de Pieri ?', answer: 'Escarre d\'inoculation : papule avec croûte noirâtre entourée d\'un halo congestif (brûlure de cigarette). Retrouvée dans 50% des cas, indolore'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_7', question: 'Quelles sont les caractéristiques de l\'éruption dans la FBM ?', answer: 'Constante, débute aux membres inférieurs, n\'épargne pas les paumes ni plantes, éléments arrondis 0.5-1.5 cm séparés par peau saine, couleur rose → rouge → violet → brun'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_8', question: 'Quel est le score de diagnostic de la FBM ? Quand est-il positif ?', answer: '> 25 points = compatible avec un diagnostic présomptif de FBM. Points importants : fièvre >39°C (5pts), escarre (5pts), éruption (5pts), isolement R. conorii (25pts)'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_9', question: 'Quelle est l\'évolution sous traitement ?', answer: 'Température normale en 2-3 jours, éruption pâlit rapidement, guérison en une semaine, convalescence très courte'),
        Flashcard(id: 'fievre_boutonneuse_mediterraneenne_fbm_10', question: 'Quelles sont les formes cliniques graves ?', answer: 'Formes traitées tardivement ou sur terrain affaibli (sujet âgé, diabétique, immunodéprimé) : complications cardiaques, rénales, pulmonaires, neurologiques, ophtalmologiques'),
      ],
    ),
    Course(
      id: 'diarrhees_infectieuses_et_tiac',
      name: 'Diarrhées Infectieuses et TIAC',
      cards: [
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_1', question: 'Définition de la TIAC ?', answer: 'Toxi-Infection Alimentaire Collective : apparition d\'au moins 2 cas similaires de symptomatologie digestive (parfois neurologique) chez des personnes ayant partagé le même repas'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_2', question: 'Définition de la diarrhée selon l\'OMS ?', answer: '> 3 selles par jour. Ou émission > 300g/j d\'eau dans les selles'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_3', question: 'Qu\'est-ce que le syndrome cholériforme ?', answer: 'Diarrhée aqueuse profuse \'eau de riz\', vomissements, déshydratation, PAS de fièvre. Mécanisme : toxinogène (ex: Vibrio cholerae, ETEC, Staph. aureus)'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_4', question: 'Qu\'est-ce que le syndrome dysentérique ?', answer: 'Diarrhée sanglante, fausses membranes, épreintes, ténesme, FIEVRE. Mécanisme : invasion/destruction (ex: Shigelles, EIEC)'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_5', question: 'Qu\'est-ce que le syndrome gastro-entéritique ?', answer: 'Signes d\'invasion + fièvre + douleurs abdominales. Mécanisme : invasion sans destruction (ex: Salmonella)'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_6', question: 'Quels agents produisent des entérotoxines dans les TIAC ?', answer: 'ECET, Aeromonas hydrophila, Campylobacter, Salmonella typhimurium → ↑ AMPc → ↑ sécrétion Cl- → fuite d\'eau'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_7', question: 'Quelles bactéries ont le plus faible inoculum minimum pour provoquer une infection ?', answer: 'Shigelles (inoculum très bas)'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_8', question: 'Quelle est la démarche diagnostique devant une diarrhée infectieuse ?', answer: '1) Rechercher les signes de gravité 2) Affirmer le diagnostic par interrogatoire et examen clinique 3) Approche étiologique'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_9', question: 'Quelle est l\'incidence des TIAC en Algérie (2023) ?', answer: '1000 à 3000 cas/an, une dizaine de décès, 80% en été (juin-août), fréquents dans fast-food/restaurants/fêtes'),
        Flashcard(id: 'diarrhees_infectieuses_et_tiac_10', question: 'Quels germes causent des diarrhées invasives avec ulcération ?', answer: 'Par mécanisme direct : Shigelles, EIEC. Par toxines : EHEC, Clostridium difficile'),
      ],
    ),
    Course(
      id: 'brucellose',
      name: 'Brucellose',
      cards: [
        Flashcard(id: 'brucellose_1', question: 'Qu\'est-ce que la brucellose ?', answer: 'Anthropozoonose bactérienne cosmopolite (= Fièvre de Malte) due à des coccobacilles du genre Brucella. Homme = hôte accidentel'),
        Flashcard(id: 'brucellose_2', question: 'Quelles sont les 4 espèces pathogènes pour l\'homme ?', answer: 'B. melitensis (caprins/ovins, la plus grave), B. abortus (bovins), B. suis (porcins), B. canis (chiens)'),
        Flashcard(id: 'brucellose_3', question: 'Quelle est l\'incidence mondiale de la brucellose ?', answer: '500 000 nouveaux cas/an (OMS). Mortalité < 2%'),
        Flashcard(id: 'brucellose_4', question: 'Quels sont les groupes à risque ?', answer: 'Éleveurs, vétérinaires, personnel d\'abattoirs, laborantins, ruraux consommant du lait cru ou produits laitiers non pasteurisés'),
        Flashcard(id: 'brucellose_5', question: 'Comment se fait la contamination directe ?', answer: 'Au contact d\'animaux infectés ou leurs sécrétions (placentas, produits d\'avortement, urine, lait, sécrétions vaginales) → pénétration transcutanée, conjonctivale ou aérienne'),
        Flashcard(id: 'brucellose_6', question: 'Quelle est la triade classique de la brucellose aiguë ?', answer: 'Fièvre ondulante + sueurs nocturnes abondantes (odeur de paille pourri) + syndrome algique (arthralgies genoux, myalgies, talalgie)'),
        Flashcard(id: 'brucellose_7', question: 'Quels sont les signes à l\'examen clinique de la brucellose aiguë ?', answer: 'Splénomégalie molle indolore, hépatomégalie (1/3), adénopathies, orchite/orchi-épididymite très douloureuse, sacro-iléite'),
        Flashcard(id: 'brucellose_8', question: 'Qu\'est-ce que la sacro-iléite brucellosique ?', answer: 'Très évocatrice de brucellose chez le sujet jeune, unilatérale (parfois bilatérale), carie de la berge iliaque à la radiologie'),
        Flashcard(id: 'brucellose_9', question: 'Qu\'est-ce que la brucellose subaiguë focalisée ?', answer: 'Succède à une brucellose aiguë non/incorrectement traitée. Fébricule + sueurs + asthénie + localisations ostéo-articulaires (10-85%) ou neurologiques'),
        Flashcard(id: 'brucellose_10', question: 'Quelle est la particularité bactériologique de Brucella ?', answer: 'Intracellulaire facultatif (survit dans monocytes/macrophages toute la vie) → quasi impossible de stériliser les foyers profonds'),
        Flashcard(id: 'brucellose_11', question: 'Pourquoi ne peut-on pas affirmer la guérison définitive de la brucellose ?', answer: 'Capacité des brucelles à survivre à l\'intérieur des macrophages toute la vie → rechutes possibles'),
        Flashcard(id: 'brucellose_12', question: 'Quelle est la situation épidémiologique en Algérie ?', answer: 'Endémo-épidémique, incidence 20.61/100 000 (2024). Pic mai-juillet. Wilayas : Djelfa, M\'sila, El Bayadh, Laghouat, Biskra, Médéa'),
      ],
    ),
    Course(
      id: 'amoebose',
      name: 'Amoebose',
      cards: [
        Flashcard(id: 'amoebose_1', question: 'Qu\'est-ce que l\'amoebose ?', answer: 'Infection parasitaire du côlon par Entamoeba histolytica (protozoaire). Maladie du péril fécal. MDO en Algérie'),
        Flashcard(id: 'amoebose_2', question: 'Quelles sont les 2 formes de trophozoïtes ?', answer: '1) Minuta (non hématophage, non pathogène) = amibiase-infection. 2) Histolytica (hématophage, pathogène) = amibiase-maladie'),
        Flashcard(id: 'amoebose_3', question: 'Comment se transmet l\'amibiase ?', answer: 'Via les kystes (mains sales, sol/eau/aliments souillés par excréta, mouches). Réservoir : porteur asymptomatique'),
        Flashcard(id: 'amoebose_4', question: 'Quelle est la prévalence mondiale de l\'amoebose ?', answer: '50 millions de cas avec 40 000 décès par an'),
        Flashcard(id: 'amoebose_5', question: 'Quelle est la triade de la dysenterie amibienne ?', answer: 'Ténesme (tension douloureuse anale avec faux besoins) + Épreintes (douleurs abdominales paroxystiques du cadre colique) + Diarrhée glairo-sanglante afécale'),
        Flashcard(id: 'amoebose_6', question: 'Quelles sont les caractéristiques des selles dans la dysenterie amibienne ?', answer: '10-15 selles/jour, afécales, glairo-sanglantes \'crachat rectal sans pus\', SANS fièvre, SANS déshydratation, EG conservé'),
        Flashcard(id: 'amoebose_7', question: 'Quelle est la triade de l\'amoebose hépatique (triade de Fontan) ?', answer: 'Fièvre élevée (>39°C) + Hépatomégalie douloureuse + ébranlement hépatique à la percussion'),
        Flashcard(id: 'amoebose_8', question: 'Quel examen de première intention pour l\'abcès amibien du foie ?', answer: 'Échographie abdominale +++ : image hypodense liquidienne. TDM si échographie non contributive (abcès du dôme)'),
        Flashcard(id: 'amoebose_9', question: 'Quels sont les marqueurs biologiques de l\'amoebose hépatique ?', answer: 'Hyperleucocytose à PNN, CRP > 150 mg/L, VS très accélérée'),
        Flashcard(id: 'amoebose_10', question: 'Quelle est l\'évolution de l\'amoebose hépatique sous traitement ?', answer: 'Fièvre et douleurs disparaissent en 3j, VS réduite de moitié en 72H, les images échographiques se normalisent en 1 an'),
        Flashcard(id: 'amoebose_11', question: 'Quelles sont les localisations extra-intestinales autres que le foie ?', answer: 'Pleuro-pulmonaire (couple hépato-pulmonaire), cérébrale (rare), péricardique (urgence), cutanée (ano-génitale)'),
        Flashcard(id: 'amoebose_12', question: 'Quel est le traitement de l\'amibiase ?', answer: 'Anti-amibiens tissulaires (métronidazole) + anti-amibiens de contact (tiliquinol, tibroquinol)'),
      ],
    ),
    Course(
      id: 'diphterie',
      name: 'Diphtérie',
      cards: [
        Flashcard(id: 'diphterie_1', question: 'Qu\'est-ce que la diphtérie ?', answer: 'Toxi-infection bactérienne hautement contagieuse, strictement humaine, due à Corynebacterium diphtheriae (bacille de Klebs-Loëffler, Gram positif)'),
        Flashcard(id: 'diphterie_2', question: 'Quelles sont les 3 espèces de Corynebacterium pathogènes pour l\'homme ?', answer: 'C. diphtheriae (+++), C. ulcerans, C. pseudotuberculosis (ces 2 dernières sont des zoonoses)'),
        Flashcard(id: 'diphterie_3', question: 'Quel est le mécanisme de la gravité de la diphtérie ?', answer: 'La toxine diphtérique (exotoxine diffusant dans le sang) est responsable des complications : myocardite, paralysies, néphrite. Seules les bactéries \'tox+\' la produisent'),
        Flashcard(id: 'diphterie_4', question: 'Quelles sont les 4 caractéristiques des fausses membranes diphtériques ?', answer: '1) Extensives 2) Adhérentes (arrachement saignant) 3) Cohérentes (résistent à l\'écrasement) 4) Récidivantes (rapidement reproductibles)'),
        Flashcard(id: 'diphterie_5', question: 'Quelle est la fièvre dans la diphtérie ?', answer: 'Modérée : 38-38.5°C (contrastant avec la gravité locale)'),
        Flashcard(id: 'diphterie_6', question: 'Quelle est la complication cardiaque de la diphtérie ?', answer: 'Myocardite (Syndrome malin secondaire de Marfan) : précoce (4-10j), grave, tachycardie/bradycardie/troubles du rythme, cause de décès si avant le 15ème jour'),
        Flashcard(id: 'diphterie_7', question: 'Quelles sont les paralysies diphtériques ?', answer: 'Syndrome malin tardif de Grenet et Mazard : précoces (2-3 semaines) ou tardives (2-3 mois), réversibles, gravité si atteinte respiratoire'),
        Flashcard(id: 'diphterie_8', question: 'Quel est le traitement urgent de la diphtérie ?', answer: 'Sérothérapie + antibiothérapie (pénicilline G ou amoxicilline ou érythromycine) SANS attendre les résultats biologiques'),
        Flashcard(id: 'diphterie_9', question: 'Quelle est la situation épidémiologique en Algérie ?', answer: 'Depuis PEV 1970. Épidémie 1993-1996 (>1900 cas, 50 décès). En 2024 : recrudescence dans le sud (Tamanrasset) : 115 cas, 28 décès'),
        Flashcard(id: 'diphterie_10', question: 'Quelle est la situation mondiale en 2025 ?', answer: 'OMS : 25 millions n\'ont pas reçu le VAD. Épidémie en Somalie (1616 cas/87 décès). Europe : 536 cas en 2022 (surtout migrants)'),
        Flashcard(id: 'diphterie_11', question: 'Quelle est la durée de convalescence sous traitement ?', answer: 'Surveillance de 90 jours (fausses membranes tombent en 48h-5j, fièvre disparaît en 3j, mais complications toxiniques entre 8j et 3 mois)'),
      ],
    ),
    Course(
      id: 'rage',
      name: 'Rage',
      cards: [
        Flashcard(id: 'rage_1', question: 'Qu\'est-ce que la rage ?', answer: 'Zoonose à transmission accidentelle à l\'homme. Encéphalomyélite constamment fatale une fois déclarée. Priorité de santé publique. MDO'),
        Flashcard(id: 'rage_2', question: 'Quel est l\'agent causal de la rage ?', answer: 'Lyssavirus de la famille des Rhabdoviridae. Virus à ARN monocaténaire enveloppé, fragile (détruit par savon, antiseptiques, chaleur, lumière)'),
        Flashcard(id: 'rage_3', question: 'Quels sont les 3 cycles épidémiologiques de la rage ?', answer: '1) Rage canine (pays d\'Afrique, Asie, Amérique latine) 2) Rage selvatique (renards, loups, ratons laveurs) 3) Rage des chiroptères (chauves-souris)'),
        Flashcard(id: 'rage_4', question: 'Quel animal est responsable de 99% des cas de rage humaine ?', answer: 'Le chien errant'),
        Flashcard(id: 'rage_5', question: 'Comment évolue la rage dans le système nerveux ?', answer: 'Point d\'inoculation → multiplication dans muscle strié → fixation aux terminaisons nerveuses → transport rétrograde axonal (8-22 mm/j) → SNC → diffusion centrifuge vers SN périphérique et glandes salivaires'),
        Flashcard(id: 'rage_6', question: 'Pourquoi la durée d\'incubation varie-t-elle ?', answer: 'D\'autant plus courte que la morsure est : proche du SNC (visage), dans une zone richement innervée (doigts, organes génitaux), ou que l\'inoculum est massif'),
        Flashcard(id: 'rage_7', question: 'Quelles sont les caractéristiques de la phase prodromique de la rage ?', answer: '2 à 10 jours : douleurs/paresthésies au niveau de la région mordue + troubles du comportement (anxiété, insomnie) + fièvre 38-39°C'),
        Flashcard(id: 'rage_8', question: 'Qu\'est-ce que l\'hydrophobie et l\'aérophobie dans la rage ?', answer: 'Spasmes pharyngo-laryngés violents et douloureux déclenchés par la vue de l\'eau (hydrophobie) ou par un courant d\'air (aérophobie)'),
        Flashcard(id: 'rage_9', question: 'Quelle est l\'évolution de la rage déclarée ?', answer: 'Constamment fatale : coma → paralysie cardiorespiratoire en 3-4 jours (rage furieuse) ou 5-6 jours (rage paralytique)'),
        Flashcard(id: 'rage_10', question: 'Quel est le traitement local immédiat d\'une morsure animale ?', answer: 'Lavage au savon de Marseille + rinçage jet d\'eau 15 min + eau javellisée + alcool 70° ou povidone iodée. Éviter la suture si possible'),
        Flashcard(id: 'rage_11', question: 'Quels sont les 2 schémas vaccinaux antirabiques reconnus par l\'OMS (verorab) ?', answer: 'Essen : J0-J3-J7-J14-J28 (IM). Zagreb : 2 injections J0 + J7 + J21 (IM)'),
        Flashcard(id: 'rage_12', question: 'Quelle est la durée d\'observation vétérinaire de l\'animal mordeur ?', answer: '14 jours (animaux contaminants 5-7 jours avant les 1ers symptômes)'),
        Flashcard(id: 'rage_13', question: 'Qu\'est-ce que l\'immunodéprimé doit obligatoirement recevoir en post-exposition ?', answer: 'Immunoglobulines antirabiques + vaccin selon protocole Essen obligatoirement'),
      ],
    ),
    Course(
      id: 'herpes_viroses',
      name: 'Herpès Viroses',
      cards: [
        Flashcard(id: 'herpes_viroses_1', question: 'Quels sont les 8 types de virus herpétiques ?', answer: 'HHV1 (HSV-1), HHV2 (HSV-2), HHV3 (VZV), HHV4 (EBV), HHV5 (CMV), HHV6, HHV7, HHV8 (Sarcome de Kaposi)'),
        Flashcard(id: 'herpes_viroses_2', question: 'Quels sont les gîtes de latence des herpesvirus ?', answer: 'HSV et VZV : ganglions sensitifs (sacrés et de Gasser). CMV : macrophages. EBV : lymphocytes B. HV6 : glandes salivaires'),
        Flashcard(id: 'herpes_viroses_3', question: 'Quelle est la différence de topographie entre HSV-1 et HSV-2 ?', answer: 'HSV-1 : oro-facial (gingivo-stomatite, kératite, encéphalite). HSV-2 : herpès génital. Mais croisements possibles'),
        Flashcard(id: 'herpes_viroses_4', question: 'Quels sont les signes de la gingivo-stomatite aiguë herpétique ?', answer: 'Enfant 1-4 ans, dysphagie ++ arrêt alimentation, ulcérations diffuses (muqueuses, lèvres), fièvre 39-40°C, ADP sous angulo-maxillaires'),
        Flashcard(id: 'herpes_viroses_5', question: 'Quelles sont les complications de la kératite herpétique ?', answer: 'Opacité définitive de la cornée. Contre-indication aux corticoïdes'),
        Flashcard(id: 'herpes_viroses_6', question: 'Comment se présente l\'encéphalite herpétique ?', answer: 'Début brutal <48h : fièvre 40°C + céphalées → troubles conscience/coma, crises comitiales, troubles du caractère et mémoire, troubles phasiques, hémiplégie. Mortalité spontanée 80%'),
        Flashcard(id: 'herpes_viroses_7', question: 'Quels sont les facteurs déclenchant les récurrences herpétiques ?', answer: 'Stress, menstruations, fatigue, fièvre, infections (méningocoque, pneumocoque, paludisme, grippe)'),
        Flashcard(id: 'herpes_viroses_8', question: 'Quel est le risque de l\'herpès génital maternel lors de l\'accouchement ?', answer: 'Infection néonatale par contamination lors du passage dans la filière génitale (herpes neonatal grave)'),
        Flashcard(id: 'herpes_viroses_9', question: 'Quand faut-il traiter par antiviraux dans l\'encéphalite herpétique ?', answer: 'Traitement antiviral d\'urgence dès la moindre suspicion (aciclovir IV) sans attendre la confirmation diagnostique'),
        Flashcard(id: 'herpes_viroses_10', question: 'Quel est le risque de transmission du VZV pendant la grossesse ?', answer: 'Varicelle : risque fœtal surtout en dernière semaine de grossesse. CMV primo-infection = risque infection fœtale grave'),
      ],
    ),
    Course(
      id: 'mononucleose_infectieuse_mni',
      name: 'Mononucléose Infectieuse (MNI)',
      cards: [
        Flashcard(id: 'mononucleose_infectieuse_mni_1', question: 'Qu\'est-ce que la MNI ?', answer: 'Maladie virale due au virus Epstein-Barr (EBV = HHV4). Représente la forme clinique de la primo-infection symptomatique à EBV'),
        Flashcard(id: 'mononucleose_infectieuse_mni_2', question: 'Comment se transmet l\'EBV ?', answer: 'Directe par salive (maladie du baiser). Rarement : aliments souillés, gouttelettes, transfusion, greffe. Réservoir : sujet séropositif EBV'),
        Flashcard(id: 'mononucleose_infectieuse_mni_3', question: 'Quelle est la durée d\'incubation de la MNI ?', answer: '4 à 6 semaines (voire plus)'),
        Flashcard(id: 'mononucleose_infectieuse_mni_4', question: 'Quels sont les 4 signes cardinaux de la MNI ?', answer: 'Fièvre + Angine (érythémato-pultacée ou pseudo-membraneuse) + Polyadénopathies (cervicales postérieures +++) + Splénomégalie'),
        Flashcard(id: 'mononucleose_infectieuse_mni_5', question: 'Comment est l\'angine dans la MNI ?', answer: 'Érythémateuse ou érythémato-pultacée bilatérale, peut être pseudo-membraneuse (fausses membranes respectant la luette et le voile, se détachent facilement)'),
        Flashcard(id: 'mononucleose_infectieuse_mni_6', question: 'Quel est le signe provoqué par les aminopénicillines dans la MNI ?', answer: 'Éruption morbilliforme au 9ème-11ème jour dans 90% des cas (grande valeur diagnostique, mais n\'est PAS une allergie vraie aux β-lactamines)'),
        Flashcard(id: 'mononucleose_infectieuse_mni_7', question: 'Quel est le tableau biologique de la MNI ?', answer: 'Hyperlymphocytose avec grands lymphocytes hyperbasophiles (LT CD8 cytotoxiques) ± neutropénie'),
        Flashcard(id: 'mononucleose_infectieuse_mni_8', question: 'Qu\'est-ce que la réaction de Paul-Bunnell-Davidsohn (PBD) ?', answer: 'Présence d\'IgM anti-VCA en l\'absence d\'anti-EBNA (qui apparaissent tardivement à 3 mois). IgG anti-VCA et anti-EBNA persistent à vie'),
        Flashcard(id: 'mononucleose_infectieuse_mni_9', question: 'Qu\'est-ce que le MNI test ?', answer: 'Test d\'agglutination rapide recherchant IgM agglutinant hématies hétérologues. Positif dans 90% des cas à la fin du 1er mois. Sensibilité 98%'),
        Flashcard(id: 'mononucleose_infectieuse_mni_10', question: 'Quelles sont les complications graves de la MNI ?', answer: 'Rupture spontanée de la rate, myocardite, asphyxie (œdème VAS), encéphalite, hépatite fulminante, aplasie médullaire'),
        Flashcard(id: 'mononucleose_infectieuse_mni_11', question: 'Quel est le traitement de la MNI ?', answer: 'Essentiellement symptomatique. Proscrire les aminopénicillines. Corticothérapie (prednisone 1mg/kg/j) si tuméfaction amygdalienne gênante ou complications graves'),
        Flashcard(id: 'mononucleose_infectieuse_mni_12', question: 'Comment différencier MNI et diphtérie devant une angine à pseudo-membranes ?', answer: 'Diphtérie : membranes adhérentes, grisâtres, étendues, patient non vacciné. MNI : membranes moins adhérentes + adénopathies + splénomégalie'),
      ],
    ),
    Course(
      id: 'meningite_a_liquide_clair',
      name: 'Méningite à Liquide Clair',
      cards: [
        Flashcard(id: 'meningite_a_liquide_clair_1', question: 'Quelles sont les caractéristiques du LCR d\'une méningite à liquide clair ?', answer: 'Clair, pléiocytose modérée <500 cellules/mm3 à prédominance lymphocytaire, hyperprotéinorachie 1-2g/l, glycorachie normale'),
        Flashcard(id: 'meningite_a_liquide_clair_2', question: 'Quelle est la règle d\'or concernant la glycorachie dans les MLC ?', answer: 'Toute méningite à liquide clair avec HYPOGLYCORACHIE oriente vers une cause tuberculeuse jusqu\'à preuve du contraire'),
        Flashcard(id: 'meningite_a_liquide_clair_3', question: 'Quelles sont les 3 grandes étiologies des MLC avec hypoglycorachie ?', answer: '1) Méningite tuberculeuse 2) Listériose méningée 3) Méningite bactérienne décapitée'),
        Flashcard(id: 'meningite_a_liquide_clair_4', question: 'Qu\'est-ce qu\'une méningite bactérienne décapitée ?', answer: 'Méningite bactérienne partiellement traitée par ATB à dose insuffisante ou durée trop courte. LCR : pléiocytose lymphocytes/PN non altérés, hypoglycorachie modérée, examen direct négatif'),
        Flashcard(id: 'meningite_a_liquide_clair_5', question: 'Quels sont les signes cliniques de la méningite tuberculeuse ?', answer: 'Installation subaiguë, AEG, amaigrissement, fièvre prolongée, syndrome méningé peu franc, troubles comportement, signes d\'atteinte basilaire (paralysie nerfs crâniens)'),
        Flashcard(id: 'meningite_a_liquide_clair_6', question: 'Quel est le tableau du LCR dans la méningite tuberculeuse ?', answer: 'Pléiocytose lymphocytaire, protéinorachie >2g/L, hypoglycorachie, examen direct rarement positif, culture sur Löwenstein-Jensen (3 prélèvements sur 3 jours), PCR BK'),
        Flashcard(id: 'meningite_a_liquide_clair_7', question: 'Quelles sont les complications de la méningite tuberculeuse visibles à l\'imagerie ?', answer: 'Prise de contraste de la base du crâne (arachnoïdite basilaire), hydrocéphalie, zones d\'infarctus cérébral, tuberculomes cérébraux'),
        Flashcard(id: 'meningite_a_liquide_clair_8', question: 'Quel est le traitement de la méningite tuberculeuse ?', answer: '2 ERHZ + 7 RH. E(Ethambutol 15mg/kg/j) + R(Rifampicine 10mg/kg/j) + H(Isoniazide 5mg/kg/j) + Z(Pyrazinamide 30mg/kg/j). Corticoïdes : prednisone 2mg/kg/j × 4 semaines'),
        Flashcard(id: 'meningite_a_liquide_clair_9', question: 'Quel est le terrain typique de la listériose méningée ?', answer: 'Sujet âgé, femme enceinte, immunodéprimé. BGP (Listeria monocytogenes)'),
        Flashcard(id: 'meningite_a_liquide_clair_10', question: 'Quel est le traitement de la méningite à Listeria ?', answer: 'Amoxicilline 200 mg/kg/j pendant 21 jours + gentamicine'),
        Flashcard(id: 'meningite_a_liquide_clair_11', question: 'Quand faut-il traiter empiriquement sans attendre l\'étiologie ?', answer: 'Situations d\'urgence avec signes de gravité, doute sur méningite bactérienne → ATB probabiliste orienté selon l\'âge + antiviral si suspicion MEH'),
        Flashcard(id: 'meningite_a_liquide_clair_12', question: 'Qu\'est-ce que la cryptococcose méningée ?', answer: 'Méningite mycosique sur terrain immunodéprimé, subaiguë, syndrome méningé peu marqué. Diagnostic : encre de Chine + culture sur Sabouraud + Ag cryptococcique'),
      ],
    ),
    Course(
      id: 'tetanos',
      name: 'Tétanos',
      cards: [
        Flashcard(id: 'tetanos_1', question: 'Qu\'est-ce que le tétanos ?', answer: 'Toxi-infection due à Clostridium tetani (bacille anaérobie strict, Gram positif, sporulé). Non contagieuse, non immunisante, déclaration obligatoire, évitable par vaccination'),
        Flashcard(id: 'tetanos_2', question: 'Comment le bacille tétanique produit-il la maladie ?', answer: 'Spores → conditions d\'anaérobiose (nécrose, ischémie, corps étranger) → germination → sécrétion de tétanospasmine (neurotoxine)'),
        Flashcard(id: 'tetanos_3', question: 'Quel est le mécanisme de la tétanospasmine ?', answer: 'Transport rétrograde axonal → moelle épinière → migration transsynaptique → blocage des neurotransmetteurs INHIBITEURS des motoneurones alpha → contractures incontrôlées'),
        Flashcard(id: 'tetanos_4', question: 'Quel est le réservoir du tétanos ?', answer: 'Tellurique : sol contaminé par matières fécales d\'animaux (chevaux, moutons). Spores très résistantes (plusieurs mois à années)'),
        Flashcard(id: 'tetanos_5', question: 'Quelles sont les portes d\'entrée du tétanos ?', answer: 'Plaies souillées (même minimes), plaies chroniques/profondes, fractures ouvertes, morsures, ulcères, brûlures, interventions chirurgicales non stériles'),
        Flashcard(id: 'tetanos_6', question: 'Quels sont les groupes à risque ?', answer: 'Personnes non/mal vaccinées, milieu rural, agriculteurs, jardiniers, personnes âgées (>90% des cas chez >60 ans), femmes (plus exposées)'),
        Flashcard(id: 'tetanos_7', question: 'Quel est le symptôme inaugural du tétanos ?', answer: 'Trismus : contracture des masséters limitant l\'ouverture buccale, irréductible, douloureuse, permanente'),
        Flashcard(id: 'tetanos_8', question: 'Quelle est la durée de l\'incubation du tétanos ?', answer: '3 à 30 jours (moyenne 8 jours). Plus l\'incubation est courte, plus la maladie est sévère'),
        Flashcard(id: 'tetanos_9', question: 'Quelles sont les 3 conditions nécessaires au développement du tétanos ?', answer: '1) Absence de vaccination correcte 2) Introduction de spores dans une effraction cutanée/muqueuse 3) Faible potentiel d\'oxydoréduction (tissus nécrosés, ischémie, corps étranger)'),
        Flashcard(id: 'tetanos_10', question: 'Quels sont les différents types de tétanos selon la porte d\'entrée ?', answer: 'Post-partum, post-abortum, ombilical, chirurgical, iatrogène (injections IM, vaccinoations par scarification)'),
        Flashcard(id: 'tetanos_11', question: 'Quel est le traitement curatif du tétanos (principes) ?', answer: 'Immunoglobulines antitétaniques + ATB (pénicilline ou métronidazole) + sédation/myorelaxants + réanimation + traitement de la porte d\'entrée'),
        Flashcard(id: 'tetanos_12', question: 'Comment prévenir le tétanos ?', answer: 'Vaccination (anatoxine tétanique) très efficace. Mise à jour vaccinale systématique. Soins locaux des plaies. Séro-vaccination si plaie et vaccination insuffisante'),
      ],
    ),
  ];
}