import '../models/models.dart';

List<Course> buildCourses() {
  return [
    Course(
      id: 'fievre',
      name: 'Fièvre',
      cards: [
        Flashcard(id: 'fievre_1', question: 'Définition de la fièvre ?', answer: 'Fébricule = T° entre 37,5° et 38° / Fièvre = T° > 38° le matin et > 38,3° le soir / Fièvre élevée = 39° / Hyperthermie = > 41°'),
        Flashcard(id: 'fievre_2', question: 'Principales causes de fièvre ?', answer: 'Maladies infectieuses+++ (virales bénignes prédominantes), maladies inflammatoires, MAI, maladies de système, néoplasies/hémopathies malignes, MTE'),
        Flashcard(id: 'fievre_3', question: 'Physiopathologie de la fièvre ?', answer: 'Pyrogènes (exogènes : toxines bactériennes / endogènes : cytokines inflammatoires) → stimulation synthèse PGE2 → dérèglement thermostat hypothalamique'),
        Flashcard(id: 'fievre_4', question: 'Fièvre continue ou en plateau : définition et causes ?', answer: 'T° à 40° avec faible rémission de 0,5° le matin. Causes : FT 2e semaine, septicémies, palu primo-invasion'),
        Flashcard(id: 'fievre_5', question: 'Fièvre rémittente : définition et causes ?', answer: 'T° subnormale le matin avec élévation progressive max le soir. Causes : TBC, suppurations profondes'),
        Flashcard(id: 'fievre_6', question: 'Fièvre intermittente : définition et causes ?', answer: 'Accès de fièvre séparés par intervalles d\'apyrexie totale régulièrement (accès palustre) ou irrégulièrement espacés (cholécystite)'),
        Flashcard(id: 'fievre_7', question: 'Fièvre ondulante : définition et causes ?', answer: 'Poussées de fièvre à début et fin progressifs alternant avec rémissions thermiques complètes sur semaines/mois. Causes : Hodgkin, brucellose, endocardite'),
        Flashcard(id: 'fievre_8', question: 'Classification de la fièvre selon la durée ?', answer: 'Aiguë récente < 5 jrs / Persistante entre 5 et 20 jrs / Prolongée ou au long cours > 20 jrs'),
        Flashcard(id: 'fievre_9', question: 'Quand utiliser les antipyrétiques ?', answer: 'Hyperthermie mettant en jeu le pronostic vital, extrêmes d\'âge (NRS : risque CVS / vieillard : risque DSH, troubles comportement), infection bénigne. Sinon le trt étiologique suffit'),
      ],
    ),
    Course(
      id: 'sd_meningee',
      name: 'Syndrome Méningé',
      cards: [
        Flashcard(id: 'sd_meningee_1', question: 'Définition du syndrome méningé ?', answer: 'Ensemble des manifestations cliniques en rapport avec l\'irritation des enveloppes méningées. Urgence diagnostique et thérapeutique. 2 étiologies : méningite infectieuse et HM'),
        Flashcard(id: 'sd_meningee_2', question: 'Syndrome méningé fonctionnel ?', answer: 'Céphalées (+++) : intense, en casque, rebelle aux antalgiques, paroxystiques avec photophobie et phonophobie / VMS : faciles en jet, répétés, rythmés par les céphalées / Constipation inconstante'),
        Flashcard(id: 'sd_meningee_3', question: 'Syndrome méningé physique ?', answer: 'Raideur de la nuque (+++) : signe cst et précoce, antéflexion limitée / Signe de Brudzinski / Signe de Kernig / Position en chien de fusil / Hyperesthésie cutanée'),
        Flashcard(id: 'sd_meningee_4', question: 'Signes encéphalitiques : signification et exemples ?', answer: 'Témoignent de la gravité → TDM cérébrale obligatoire. Exemples : signes de focalisation, CVS, troubles psychiques, troubles de conscience, troubles neuro-végétatifs'),
        Flashcard(id: 'sd_meningee_5', question: 'Ponction lombaire : point de ponction et technique ?', answer: 'Entre L4-L5 ou L3-L4 ou L5-S1 (intersection ligne horizontale crêtes iliaques et ligne verticale des épineuses). DL ou assis le dos rond. Piquer de manière ascendante. 3 tubes : bioch/cyto/bactério'),
        Flashcard(id: 'sd_meningee_6', question: 'Contre-indications à la PL ?', answer: 'Neurologiques : suspicion processus intracrânien, signes d\'HIC/engagement, CVS persistantes / Non neurologiques : infection cutanée du site, instabilité hémodynamique/respi, troubles hémostase (plaquettes < 25-50.000)'),
        Flashcard(id: 'sd_meningee_7', question: 'LCS normal : caractéristiques ?', answer: 'Clair "eau de roche" et stérile, albumine < 0,5 g/l, glucose ≥ ½ glycémie, chlore 110-130 mEq/ml, lactate < 3 µmol/ml, < 10 éléments/mm3 (lymphocytes, absence de PN)'),
        Flashcard(id: 'sd_meningee_8', question: 'Qu\'est-ce que le méningisme ?', answer: 'Syndrome méningé + LCS normal. Causes : PFLA, palu, otite, FT'),
      ],
    ),
    Course(
      id: 'meningite_pneumo',
      name: 'Méningite à Pneumocoque',
      cards: [
        Flashcard(id: 'mpneumo_1', question: 'Microbiologie du pneumocoque ?', answer: 'Streptococcus pneumoniae, CGP (diplocoque, forme lancéolée en "flamme de bougie", encapsulé, aéro-anaérobie facultatif), hémolyse α (partielle), culture sur gélose de sang, sensible à l\'optochine'),
        Flashcard(id: 'mpneumo_2', question: 'Epidémiologie et transmission de la méningite à pneumocoque ?', answer: '2e après la MCS, grave et mortelle sans trt. Infections fréquentes et essentiellement communautaires. Réservoir : VAS des sujets sains et malades. Transmission : interhumaine directe aérienne'),
        Flashcard(id: 'mpneumo_3', question: 'Facteurs favorisants la méningite à pneumocoque ?', answer: 'Saison hivernale, infection de voisinage (trauma base crâne, mastoïdite, sinusite)+++ , altération clairance ciliaire (BPCO, asthme, tabagisme), ID (VIH, diabète, splénectomie+++, myélome), maladies chroniques'),
        Flashcard(id: 'mpneumo_4', question: 'Clinique de la méningite à pneumocoque ?', answer: 'Début brutal explosif (avec ATCD d\'infection ORL ou pneumonie). SG : fièvre élevée 39-40°C, frissons, AEG. SF : syndrome méningé fonctionnel et signes encéphalitiques+++ (CVS, obnubilation, agitation). SP : syndrome méningé physique, herpès naso-labial'),
        Flashcard(id: 'mpneumo_5', question: 'Complications infectieuses de la méningite à pneumocoque ?', answer: 'Abcès cérébral, empyème, ventriculite'),
        Flashcard(id: 'mpneumo_6', question: 'Complications mécaniques (NRS+++) ?', answer: 'HTIC, hypotension intracrânienne, cloisonnement méningé, hématome sous-dural'),
        Flashcard(id: 'mpneumo_7', question: 'Séquelles de la méningite à pneumocoque ?', answer: 'Moyen terme : hydrocéphalie ou déficit moteur / Long terme : surdité+++, cécité, mutité, comitialité, troubles psychomoteurs, paralysie des nerfs crâniens (oculomoteurs et facial)'),
        Flashcard(id: 'mpneumo_8', question: 'Examens de certitude de la méningite à pneumocoque ?', answer: 'PL : liquide hypertendu, trouble ou purulent (peut être clair si débutante), cyto >1000 PNA/mm3, albumine >2-3 g/l, glucose diminuée <½ glycémie, examen direct (diplocoque GP). Recherche Ag solubles si ATB préalable'),
        Flashcard(id: 'mpneumo_9', question: 'Traitement curatif sans signes de gravité ?', answer: 'C3G (céfotaxime ou ceftriaxone) + CTC en IV pdt 15-21 jrs. Trt adjuvant : dexaméthasone IV pdt 4 jrs (doit débuter en même temps que l\'ATB)'),
        Flashcard(id: 'mpneumo_10', question: 'Traitement curatif avec signes de gravité ou facteurs prédisposants à PSDP ?', answer: 'C3G + glycopeptide (vancomycine) + CTC. Si allergie β-lactamines : remplacer C3G par phénicolés. Si CI vancomycine : remplacer par rifampicine'),
        Flashcard(id: 'mpneumo_11', question: 'Facteurs prédisposants à un PSDP ?', answer: 'Âges extrêmes, prise de β-lactamines dans les 3-6 mois, ATCD de pneumopathies, terrain favorisant (VIH)'),
        Flashcard(id: 'mpneumo_12', question: 'Prévention de la méningite à pneumocoque ?', answer: 'Déclaration de la maladie. Vaccination chez sujets prédisposés : Prevenar13 puis 2 mois après Pneumo23, avec rappel tous les 5 ans'),
      ],
    ),
    Course(
      id: 'pneumonie_pneumo',
      name: 'Pneumonie à Pneumocoque (PFLA)',
      cards: [
        Flashcard(id: 'pfla_1', question: 'Epidémiologie de la pneumonie à pneumocoque ?', answer: 'Responsable de 30-50% des PAC, les plus graves et les plus fréquemment hospitalisées. Incubation 2-4 jrs avec parfois syndrome pseudo-grippal'),
        Flashcard(id: 'pfla_2', question: 'Phase d\'invasion de la PFLA ?', answer: 'Début brutal explosif. SG : fièvre élevée 39-40°C et UN SEUL frisson (intense et prolongé, dit "solennel"). SF : DT de type pleurale (point de côté), toux sèche, polypnée superficielle. SP : herpès naso-labial, discret syndrome de condensation'),
        Flashcard(id: 'pfla_3', question: 'Phase d\'état de la PFLA ?', answer: 'SG : fièvre 39-40°C. SF : toux avec expectorations muco-purulentes ou hémoptoïques (crachats rouillés de Laennec). SP : syndrome de condensation franc, faciès vultueux avec rougeur unilatérale de la pommette, langue saburrale'),
        Flashcard(id: 'pfla_4', question: 'Complications de la PFLA ?', answer: 'Pleurésie purulente, suppurations à distance (otite, méningite), sepsis, décompensation d\'une pathologie sous-jacente'),
        Flashcard(id: 'pfla_5', question: 'Examens complémentaires de la PFLA ?', answer: 'Orientation : NFS (hyperleucocytose à PNN), bilan inflammatoire (VS élevée, CRP+). Certitude : TLT (foyer de condensation), hémoculture (positive dans 20-30%), recherche Ag solubles urinaires'),
        Flashcard(id: 'pfla_6', question: 'Score CRB-65 pour décider l\'hospitalisation ?', answer: 'C : confusion mentale / R : FR > 30 cycles/min / B : hypotension artérielle / 65 : âge > 65 ans. 1 critère ou + → hospitalisation'),
        Flashcard(id: 'pfla_7', question: 'Traitement ambulatoire de la PFLA ?', answer: 'Amoxicilline PO pdt 10-15 jrs (érythromycine ou pristinamycine si allergie aux β-lactamines)'),
        Flashcard(id: 'pfla_8', question: 'Traitement hospitalier de la PFLA ?', answer: 'Ampicilline ou céfotaxime/ceftriaxone IV (lévofloxacine si allergie aux β-lactamines)'),
      ],
    ),
    Course(
      id: 'meningococcies',
      name: 'Méningococcies (MCS)',
      cards: [
        Flashcard(id: 'mcs_1', question: 'Microbiologie du méningocoque ?', answer: 'Neisseria meningitidis, CGN (diplocoque, en "grain de café", aérobie strict). Sérogroupes pathogènes les plus fréquents : A, B, C, X, Y et W135. Fragile/exigeant : ne cultive que sur milieux riches sous atmosphère enrichie en CO2'),
        Flashcard(id: 'mcs_2', question: 'Répartition géographique des sérogroupes ?', answer: 'Afrique et Moyen-Orient → A et W135 / Europe → B et C'),
        Flashcard(id: 'mcs_3', question: 'Réservoir et transmission du méningocoque ?', answer: 'Réservoir : VAS des sujets sains et malades (strictement humaine). Transmission : interhumaine directe aérienne (contagiosité+++ → notion de cas similaires). Épidémies et cas sporadiques'),
        Flashcard(id: 'mcs_4', question: 'Facteurs favorisants la MCS ?', answer: 'Recrudescence hiverno-printanière, déficit en complément, hypogammaglobulinémie, splénectomie. Terrain : tous les âges, surtout enfant et adulte jeune'),
        Flashcard(id: 'mcs_5', question: 'Phase d\'incubation et d\'invasion de la MCS ?', answer: 'Incubation : 2-5 jrs, silencieuse ou rhinopharyngite. Invasion : début brutal avec fièvre 39-40°C, frissons, AEG, syndrome méningé fonctionnel, syndrome méningé physique discret, +/- pharyngite'),
        Flashcard(id: 'mcs_6', question: 'Phase d\'état de la MCS : signes SHARP ?', answer: 'S : SPM / H : Herpès naso-labial / A : Arthralgies/arthrites / R : Rash morbiliforme / P : Purpura punctiforme localisé (face int cuisses, abdomen, MI) ou généralisé'),
        Flashcard(id: 'mcs_7', question: 'Complications immuno-allergiques de la MCS (J8-J10) ?', answer: 'Péricardite, arthrite, uvéite/iridocyclite'),
        Flashcard(id: 'mcs_8', question: 'Examens de certitude de la MCS ?', answer: 'PL : liquide hypertendu, trouble ou purulent (peut être clair si débutante), cyto >1000 PNA/mm3, albumine >1 g/l, glucose diminuée <½ glycémie. Examen direct : CGN en grain de café. PL de contrôle à J8'),
        Flashcard(id: 'mcs_9', question: 'Traitement curatif de la MCS ?', answer: 'ATB IV pdt 7-10 jrs : ampicilline/amoxicilline ou céfotaxime/ceftriaxone (thiamphénicol, ciprofloxacine ou rifampicine si allergie β-lactamines). Trt adjuvant : dexaméthasone IV pdt 4 jrs'),
        Flashcard(id: 'mcs_10', question: 'Traitement préventif de la MCS ?', answer: 'Déclaration, isolement, éviction scolaire. Chimioprophylaxie contacts : spiramycine 5 jrs ou rifampicine 2 jrs. Vaccination en cas d\'épidémie, voyage zone endémie, ID, personnel soignant. Immunité 3 ans'),
      ],
    ),
    Course(
      id: 'septicemie_meningococcique',
      name: 'Septicémie Méningococcique (Purpura Fulminans)',
      cards: [
        Flashcard(id: 'sfulmf_1', question: 'Définition du purpura fulminans ?', answer: 'Choc septique par libération d\'endotoxines (LPS), le plus souvent à point de départ méningé. Urgence absolue'),
        Flashcard(id: 'sfulmf_2', question: 'Clinique du purpura fulminans ?', answer: 'SG : syndrome infectieux sévère (fièvre, AEG). SF : signes de choc (céphalées, arthralgies, troubles de la conscience). SP : défaillance circulatoire aiguë (hypotension, tachycardie, polypnée, oligurie) + purpura généralisé ecchymotique nécrotique par CIVD'),
        Flashcard(id: 'sfulmf_3', question: 'Examens para-cliniques du purpura fulminans ?', answer: 'PL : LCS clair voire normal (mauvais pronostic). NFS : hyperleucocytose ou leucopénie (mauvais pc). Bilan hémostase : CIVD (thrombopénie, fibrinogène bas, D-dimères élevés). Hémoculture : isole le germe. Bilan rénal : IRA. Ionogramme : acidose métabolique, hyperkaliémie'),
        Flashcard(id: 'sfulmf_4', question: 'Traitement du purpura fulminans ?', answer: 'Hospitalisation en réa. Trt choc : remplissage vasculaire, transfusion PFC, drogues vasoactives, héparinothérapie si CIVD. ATB IV (amoxicilline) le plus tôt possible. ATTENTION : CTC absolument CI'),
      ],
    ),
    Course(
      id: 'staphylococcie',
      name: 'Staphylococcie',
      cards: [
        Flashcard(id: 'staph_1', question: 'Microbiologie du staphylocoque ?', answer: 'Staphylococcus aureus, CGP (regroupés en "grappes de raisin", coagulase+, oxydase-), non capsulé, résistant dans le milieu ext, cultive facilement sur milieux usuels et riches en NaCl, métabolise le mannitol (gélose de Chapman)'),
        Flashcard(id: 'staph_2', question: 'Réservoir et transmission du staphylocoque ?', answer: 'Réservoir : homme (peau, fosses nasales, tube digestif, annexes glandulaires), surfaces, air, aliments. Transmission : directe (humaine manu-portée) ou indirecte (contact objets souillés)'),
        Flashcard(id: 'staph_3', question: 'Portes d\'entrée et facteurs favorisants ?', answer: 'Communautaire : cutanée+++, urinaire, génitale, ORL, dentaire. Nosocomiale : KT, prothèse, chir. Terrain : femme enceinte, vieillard, NRS, diabète, ATBthérapie large spectre, acte chir long, matériel prothétique, séjour en réa'),
        Flashcard(id: 'staph_4', question: 'Staphylococcies épidermiques ?', answer: 'Impétigo (dermatose bulleuse contagieuse, auto-inoculable, visage et membres, bulles → pustules → croûte mélicérique), onyxis/périonyxis, panaris'),
        Flashcard(id: 'staph_5', question: 'Staphylococcies du follicule pilosébacé ?', answer: 'Folliculites aiguës superficielles (pustule douloureuse centrée par un poil), furoncles (risque staphylococcie maligne de la face), anthrax (conglomérat de furoncles), orgelet, sycocis'),
        Flashcard(id: 'staph_6', question: 'Traitement des staphylococcies cutanées ?', answer: 'Furoncle : antiseptique local uniquement. Furonculose : ATB local + synergistine. Panaris ou abcès : antiseptique local + synergistine + trt chir'),
        Flashcard(id: 'staph_7', question: 'Définition de la septicémie staphylococcique ?', answer: 'Infection généralisée avec décharges massives et répétées de bactéries dans le sang, issues d\'un foyer septique thrombophlébitique. Mécanisme : coagulase → microthromboses → fibrinolyse → métastases septiques'),
        Flashcard(id: 'staph_8', question: 'Localisations secondaires de la staphylococcémie ?', answer: 'Pleuropulmonaire (polymorphisme et labilité radio), ostéo-articulaire (ostéomyélite+++), cardiaque (endocardite+++), cutanée (purpura vésiculo-pustuleux pathognomonique), urogénitale (PNA, abcès rénal), neuro-méningée (abcès cérébral+++)'),
        Flashcard(id: 'staph_9', question: 'Examens de certitude de la staphylococcémie ?', answer: 'Hémoculture (au moins 3, + ATBgramme+++). Prélèvements au niveau porte d\'entrée et localisations secondaires. Bilan retentissement : rénal, hépatique, ionogramme. Extension : TLT, radio squelette, scinti osseuse, échocardio, scanner cérébral'),
        Flashcard(id: 'staph_10', question: 'Traitement de la staphylococcémie ?', answer: 'Double ATB précoce et synergique, fortes doses, parentérale, toutes les 4-6h. SASM : oxacilline + gentamicine / SARM : vancomycine + gentamicine. Durée : sans localisations = 2 sem / avec localisations = 3-6 sem. Gentamicine max 7 jrs'),
        Flashcard(id: 'staph_11', question: 'Staphylococcie maligne de la face : clinique ?', answer: 'Secondaire à manipulation d\'un furoncle. Début brutal avec fièvre 40°C, frissons, AEG. Cellulite diffuse de face : placard unilatéral rouge violacé, froid, peu douloureux, sans bourrelet, parsemé de vésiculo-pustules. Signes de malignité : extension périorbitaire, exophtalmie, chémosis, thrombose veines frontales'),
        Flashcard(id: 'staph_12', question: 'Staphylococcies toxiniques ?', answer: 'Syndrome d\'exfoliation généralisée (exfoliatine, NRS : sd peau ébouillantée). Choc toxinique staphylococcique (TSST-1 : atteinte multi-viscérale, éruption scarlatiniforme). Entérocolite staphylococcique (entérotoxines A et B : toxi-infection alimentaire, courte incubation 1-6h, non fébrile)'),
      ],
    ),
    Course(
      id: 'streptococcie',
      name: 'Streptococcie',
      cards: [
        Flashcard(id: 'strep_1', question: 'Microbiologie du streptocoque pyogène ?', answer: 'Streptococcus pyogenes, CGP (groupés en chaînettes), hémolyse β (complète), anaérobie aéro-tolérante, milieu de choix : gélose au sang. Réservoir : naso-pharyngé, aussi GI, anal ou génital'),
        Flashcard(id: 'strep_2', question: 'Formes cliniques des streptococcies ?', answer: 'Suppressives : angine, streptococcies cutanées (impétigo, érysipèle), sepsis, endocardite, méningite, pneumonie. Toxiniques : scarlatine. Séquellaires : RAA, GNA, érythème noueux, chorée de Sydenham'),
        Flashcard(id: 'strep_3', question: 'Clinique de l\'angine streptococcique ?', answer: 'Terrain 5-15 ans, hiver-printemps. Début brutal après incubation 2-4 jrs. SG : fièvre >38,5°C. SF : douleur pharyngée, dysphagie. SP : angine érythémateuse ou érythémato-pultacée, ADP sous-angulo-maxillaires douloureuses, ABSENCE de coryza et toux'),
        Flashcard(id: 'strep_4', question: 'Examens complémentaires de l\'angine streptococcique ?', answer: 'NFS (hyperleucocytose à PNN), CRP+, dosage des ASLO (positif dans 60%), culture sur écouvillonnage de gorge'),
        Flashcard(id: 'strep_5', question: 'Traitement de l\'angine streptococcique ?', answer: 'ATB pdt 10 jrs : extencilline (IM) ou amoxicilline PO (érythromycine si allergie β-lactamines)'),
        Flashcard(id: 'strep_6', question: 'Impétigo streptococcique : clinique et traitement ?', answer: 'Terrain 2-5 ans, climat chaud. Impétigo de Fox : péri-orificiel (nez et bouche), évolution identique au staphylococcique, ADP satellites. Trt : antiseptique local + ATB local pour formes localisées / amoxicilline-acide clavulanique ou pristinamycine PO 10 jrs pour formes généralisées'),
        Flashcard(id: 'strep_7', question: 'Érysipèle des extrémités : clinique ?', answer: 'Forme la plus fréquente. Tableau classique : grosse jambe rouge, aiguë et fébrile. Début brutal : syndrome infectieux + ADP inguinale satellite. Placard inflammatoire distal "en chaussettes" mal délimité avec lymphangite. Parfois pétéchies, vésicules, phlyctènes'),
        Flashcard(id: 'strep_8', question: 'Traitement de l\'érysipèle ?', answer: 'Curatif : ATB pdt 10 jrs (péni G ou amoxicilline, érythromycine si allergie). Trt porte d\'entrée. Trt symptomatique (paracétamol, AINS et CTC CI). Préventif récidives : extencilline toutes 3-4 semaines pdt 1 an'),
        Flashcard(id: 'strep_9', question: 'Scarlatine : pathophysiologie et terrain ?', answer: 'Maladie toxinique aiguë contagieuse due à toxine érythrogène sécrétée par S. pyogenes. Maladie immunisante (immunité anatoxinique, absence ATCD de scarlatine). Fait suite à une angine streptococcique'),
        Flashcard(id: 'strep_10', question: 'Exanthème de la scarlatine ?', answer: 'Éruption maculopapuleuse confluente sans espaces de peau saine, peau rugueuse "en peau de chagrin". Lignes de Pastia aux plis. Débute thorax/abdomen/racines cuisses → se généralise "en caleçon" épargnant paumes/plantes. Une seule poussée'),
        Flashcard(id: 'strep_11', question: 'Énanthème (évolution de la langue) dans la scarlatine ?', answer: 'J4 : V lingual (V rouge limitant triangle blanc) / J6 : langue rouge sombre et dépapillée "framboisée" / J10 : réapparition épithélium / J14 : normal'),
        Flashcard(id: 'strep_12', question: 'Traitement et éviction scolaire de la scarlatine ?', answer: 'Trt de l\'angine streptococcique + éviction scolaire de 15 jrs. Desquamation entre J8 et J15 en large lambeaux palmo-plantaires "en doigts de gants et en chaussettes"'),
      ],
    ),
    Course(
      id: 'diphterie',
      name: 'Diphtérie',
      cards: [
        Flashcard(id: 'diph_1', question: 'Microbiologie de la diphtérie ?', answer: 'Corynebacterium diphtheriae (bacille de Klebs Löffler), BGP (groupés en palissade). Réservoir : strictement humain. Transmission : aérienne (contagiosité+++). Incubation : silencieuse, 2-5 jrs'),
        Flashcard(id: 'diph_2', question: 'Angine diphtérique commune : clinique ?', answer: 'Phase d\'invasion progressive : fièvre / dysphagie / amygdalite avec enduit blanchâtre→grisâtre. Phase d\'état : fièvre 38-38,5°C, tachycardie, asthénie, EG conservé. SF : dysphagie, odynophagie. SP : angine à fausses membranes, ADP sous-angulo-maxillaires, coryza unilatéral, laryngite diphtérique (croup)'),
        Flashcard(id: 'diph_3', question: 'Caractéristiques des fausses membranes diphtériques ?', answer: 'Blancs nacrés, réguliers, adhérents à la muqueuse (ne s\'enlèvent pas sans saignement), cohérents (ne se dissocient pas dans l\'eau), rapidement extensifs vers piliers et luette "doigt de gant"'),
        Flashcard(id: 'diph_4', question: 'Cou proconsulaire ("bull neck") : qu\'est-ce que c\'est ?', answer: 'ADP sous-angulo-maxillaires volumineuses et douloureuses donnant l\'aspect d\'un cou proconsulaire. Signe de la diphtérie'),
        Flashcard(id: 'diph_5', question: 'Angine diphtérique maligne : clinique ?', answer: 'Fièvre 40°C, AEG, syndrome hémorragique, IRA. Fausses membranes épaisses et confluentes sur muqueuse hémorragique. Coryza bilatéral séro-sanglant. ADP cervicales avec périadénite. Manifestations toxiniques à distance : atteinte myocardique et nerveuse'),
        Flashcard(id: 'diph_6', question: 'Complications toxiniques de la diphtérie ?', answer: 'Atteinte myocardique (syndrome malin secondaire de Marfan) : début précoce à J10, troubles conduction/rythme, principale cause de décès. Atteinte nerveuse : paralysie vélo-palatine, paralysie accommodation, paralysie muscles larynx/pharynx, paralysie muscles respiratoires, paralysie membres'),
        Flashcard(id: 'diph_7', question: 'Examens complémentaires de la diphtérie ?', answer: 'Dg clinique (toute angine à fausses membranes = diphtérie jusqu\'à preuve du contraire). Orientation : NFS (hyperleucocytose à PNN), bilan rénal. Certitude : examen direct et culture sur écouvillonnage gorge (colonies noires + halo brunâtre), PCR, test d\'Elek. Guérison : 2 prélèvements négatifs à 8 jrs d\'intervalle'),
        Flashcard(id: 'diph_8', question: 'Traitement curatif de la diphtérie ?', answer: 'Sérothérapie (SAD équin) le plus rapidement possible, en parentérale. Doses : nasale 10.000-20.000 UI / amygdalienne 15.000-25.000 UI / pharyngo-laryngée 20.000-40.000 UI / sévère 40.000-100.000 UI. ATB IV puis relais PO pdt 14 jrs : péni G (érythromycine si allergie)'),
        Flashcard(id: 'diph_9', question: 'Prévention de la diphtérie ?', answer: 'Déclaration, isolement, éviction scolaire 1 mois. Vaccination par anatoxine diphtérique en convalescence (3 doses : J1, J3, J15). Prophylaxie entourage : prélèvement gorge + vérification statut vaccinal + ATBprophylaxie (extencilline ou érythromycine)'),
      ],
    ),
    Course(
      id: 'sbgn',
      name: 'Septicémie à BGN (SBGN)',
      cards: [
        Flashcard(id: 'sbgn_1', question: 'Définition de la SBGN ?', answer: 'Infection générale grave avec décharges massives et répétées de germes et leurs toxines dans le sang à partir d\'un foyer primaire thrombo-phlébitique. Germes : entérobactéries (E. coli, KES, Proteus) ou Pseudomonas aeruginosa'),
        Flashcard(id: 'sbgn_2', question: 'Portes d\'entrée et FDR de la SBGN ?', answer: 'Portes d\'entrée : digestive+++, urinaire+++, génitale, iatrogène. FDR communautaire : obstacle voies drainage, terrain (âge, ID, diabète), environnement, ATB abusifs. FDR nosocomiale : longue hospitalisation, germes résistants, sondage vésical, cathétérisme, intubation'),
        Flashcard(id: 'sbgn_3', question: 'Clinique de la SBGN ?', answer: 'Début brutal : fièvre jusqu\'à 40-41°C (avec périodes hypothermie), frissons généralisés, AEG. Autres : diarrhée, hyperventilation, SPM. Signes des localisations secondaires'),
        Flashcard(id: 'sbgn_4', question: 'Localisations secondaires de la SBGN ?', answer: 'Pleuro-pulmonaire (EP, SDRA), hépatique (HPM cholestatique avec ictère), rénale (micro-abcès), cardiaque (endocardite), neuro-méningée (abcès cérébral, méningite purulente), cutanée (ecthyma gangréneux de Ehlers dans sepsis à pyocyaniques), ostéo-articulaire (spondylodiscite)'),
        Flashcard(id: 'sbgn_5', question: 'Choc septique de la SBGN : deux phases ?', answer: 'Phase hyperkinétique (précoce, compensatrice) : tachycardie, PA différentielle élargie, pouls bondissant, extrémités chaudes. Phase hypokinétique (tardive, irréversible) : TA pincée et basse, pouls petit filant, extrémités froides cyanosées, polypnée, diurèse effondrée'),
        Flashcard(id: 'sbgn_6', question: 'Conséquences du choc septique ?', answer: 'Défaillance multi-viscérale (cardiaque, pulmonaire, rénale, hépatique, cérébrale). CIVD et hémorragies. Hypoxie tissulaire et acidose métabolique par hyperlactatémie'),
        Flashcard(id: 'sbgn_7', question: 'Examens de certitude de la SBGN ?', answer: 'Hémoculture+++ (+ ATBgramme) et prélèvements au niveau porte d\'entrée et localisations secondaires. Orientation : NFS, bilan hémostase, bilan rénal, ionogramme, bilan hépatique, écho abdo, TLT'),
        Flashcard(id: 'sbgn_8', question: 'Traitement de la SBGN ?', answer: 'ATB pdt 2-4-6 sem : amoxicilline (1ère intention) / C3G (2ème intention) + gentamicine (max 7 jrs). Trt porte d\'entrée et localisations secondaires. Trt choc en USI : remplissage, noradrénaline, hémodialyse si IR, ventilation assistée si SDRA, PFC si CIVD'),
      ],
    ),
    Course(
      id: 'fievre_typhoide',
      name: 'Fièvre Typhoïde (FT)',
      cards: [
        Flashcard(id: 'ft_1', question: 'Définition et agent causal de la fièvre typhoïde ?', answer: 'Bactériémies à porte d\'entrée digestive, à point de départ lymphatique mésentérique. Agent : Salmonella enterica (sérovars typhi 80% et paratyphi A, B, C). BGN (bacille d\'Eberth). 3 Ag importants : somatique O, flagellaire H, capsulaire Vi'),
        Flashcard(id: 'ft_2', question: 'Epidémiologie de la fièvre typhoïde ?', answer: 'Réservoir : exclusivement humain (malade, convalescent, porteur sain). Transmission liée au péril fécal : directe (oro-fécale manu-portée, rare) ou indirecte (eau ou aliments contaminés, la plus fréquente). Terrain : tout âge, surtout 5-25 ans'),
        Flashcard(id: 'ft_3', question: 'Phase d\'incubation et premier septénaire de la FT ?', answer: 'Incubation silencieuse 10-15 jrs (3-60 jrs). 1er septénaire : début insidieux avec fièvre progressive 39-40°C en 5-7 jrs, asthénie croissante (annonciatrice du tuphos), frissons, dissociation pouls-T°, syndrome pseudo-grippal, signes nerveux, constipation, épistaxis, langue saburrale, FID sensible et gargouillante, SPM'),
        Flashcard(id: 'ft_4', question: 'Deuxième septénaire (phase d\'état) de la FT ?', answer: 'Fièvre continue en plateau 39-40°C (pas de frissons). SF : tuphos (prostration + inversion rythme nycthéméral), diarrhée ("jus de melon"), méningisme. SP : langue saburrale, abdomen ballonné, SPM souvent présente, taches rosées lenticulaires* et angine de Duguet*, râles bronchiques'),
        Flashcard(id: 'ft_5', question: 'Taches rosées lenticulaires : caractéristiques ?', answer: 'Macules rose pâle, arrondies, non prurigineuses, peu nombreuses, réparties sur thorax, partie haute abdomen et flancs. Pathognomoniques et inconstantes'),
        Flashcard(id: 'ft_6', question: 'Angine de Duguet : caractéristiques ?', answer: 'Ulcérations superficielles indolores, ovalaires à grand axe vertical, siégeant sur les piliers antérieurs du voile du palais. Pathognomonique mais rare'),
        Flashcard(id: 'ft_7', question: 'Complications digestives de la FT ?', answer: 'Hémorragies digestives (ulcération plaques de Peyer, annonciatrices de perforation). Perforations intestinales : sthénique (péritonite aiguë) ou asthénique (ballonnement/sensibilité, AEG, tuphos+). Sd pseudo-perforatif (occlusion fonctionnelle). Aussi : appendicite, cholécystite, abcès hépatique'),
        Flashcard(id: 'ft_8', question: 'Examens de certitude de la FT ?', answer: '1er septénaire : hémoculture+++ (positive 80-90%). Vers J10-J20 : coproculture (positive dans 40%, intérêt triple : dg, dépistage porteurs sains, contrôle). À partir J8 : sérologie de Widal et Felix (Ac anti-O, positivité >1/200). Guérison : 2 coprocultures négatives à 48h d\'intervalle'),
        Flashcard(id: 'ft_9', question: 'Traitement spécifique de la FT ?', answer: 'Cotrimoxazole PO (1ère intention) / Amoxicilline PO (porteur chronique et femme enceinte) / Ofloxacine ou Perfloxacine PO/IV pdt 10 jrs (1er choix pays développés) / Ceftriaxone IV/IM (très efficace). CTC si formes toxiniques sévères (myocardite, encéphalite)'),
        Flashcard(id: 'ft_10', question: 'Prévention de la FT ?', answer: 'Isolement entérique, déclaration, éviction scolaire 20 jrs, éducation sanitaire, +/- vaccination. Collective : source de contamination, dépistage porteurs sains, trt eaux usées, hygiène alimentaire'),
      ],
    ),
    Course(
      id: 'cholera',
      name: 'Choléra',
      cards: [
        Flashcard(id: 'chol_1', question: 'Agent causal et types du choléra ?', answer: 'Vibrio cholerae, BGN (en virgule). 2 sérogroupes : O1 (7 pandémies mondiales) et O139 (éventuelle 8e pandémie). 2 biotypes : classique (6 premières pandémies) et ElTor (7e et dernière pandémie). Pathogénicité liée à une toxine protéique'),
        Flashcard(id: 'chol_2', question: 'Réservoir, transmission et facteurs favorisants du choléra ?', answer: 'Réservoir : hydrique (estuaires, fleuves) et humain. Transmission liée au péril fécal. Maladie très contagieuse et NON immunisante. Facteurs : chaleur et humidité, bas niveau socio-économique, promiscuité, ID, toute condition diminuant l\'acidité gastrique (Biermer, gastrite HP, IPP)'),
        Flashcard(id: 'chol_3', question: 'Phase d\'invasion du choléra ?', answer: 'Entre 5 et 12h, début brutal : asthénie, angoisse, douleur abdo, diarrhée (importante et très contagieuse, fécale puis aqueuse), VMS alimentaires puis bilieux, crampes musculaires'),
        Flashcard(id: 'chol_4', question: 'Phase d\'état du choléra : caractéristiques des selles ?', answer: 'Sécrétoires (pas de glaires, sang ni pus), aqueuses afécales couleur "eau de riz" avec flocons blanchâtres "grains riziformes", sans efforts, sans coliques, sans ténesme, sphincter atone, 50-100 selles/24h, 0,5-1L/selle, 15-20 L/24h dans formes graves'),
        Flashcard(id: 'chol_5', question: 'Signes de DSH dans le choléra ?', answer: 'Fièvre ABSENTE, patient CONSCIENT. DSH mixte : EC (pli cutané, collapsus cardiovasculaire, oligurie) + IC (soif intense, sécheresse muqueuses, énophtalmie). Sphincter atone au TR'),
        Flashcard(id: 'chol_6', question: 'Examens complémentaires du choléra ?', answer: 'Orientation : NFS (hyperleucocytose à PNN modérée), ionogramme (natrémie normale ou diminuée, hypokaliémie, acidose métabolique), bilan rénal (IR), ECG. Certitude : prélèvement selles fraiches du matin en EPAH (eau peptonée alcaline hypersalée), coproculture, sérologie. Guérison : 2 coprocultures négatives à 48h d\'intervalle'),
        Flashcard(id: 'chol_7', question: 'Traitement curatif du choléra ?', answer: 'SRO préférée aux préparations parentérales (sauf choc, DSH sévère, VMS incoercibles). ATB : adulte et enfant >5 ans → tétracycline/doxycycline / enfant <5 ans et femme enceinte → furazolidone ou azithromycine/cotrimoxazole. Si diurèse non reprise à 18h → furosémide / à 20h → hémodialyse'),
        Flashcard(id: 'chol_8', question: 'Prévention du choléra ?', answer: 'Déclaration. Isolement, éviction scolaire, désinfection. Chimioprophylaxie contacts : sulfadoxine ou cotrimoxazole/tiliquinol pdt 5 jrs. Vaccination inutile une fois l\'épidémie déclarée'),
      ],
    ),
    Course(
      id: 'brucellose',
      name: 'Brucellose',
      cards: [
        Flashcard(id: 'bruc_1', question: 'Microbiologie et réservoir de la brucellose ?', answer: 'Brucella (melitensis+++, abortus, suis, canis), BGN, tropisme intracellulaire (macrophages et monocytes). melitensis : ovins/caprins / abortus : bovins / suis : porcins / canis : chiens. Anthropozoonose. Professions à risque : éleveurs, abattoirs, vétérinaires'),
        Flashcard(id: 'bruc_2', question: 'Transmission de la brucellose ?', answer: 'Indirecte : ingestion produits laitiers non pasteurisés contaminés (la plus fréquente) / Directe : contact animaux (professions exposées) ou inhalation (laborantins). Facteurs : professions à risque+++'),
        Flashcard(id: 'bruc_3', question: 'Brucellose aiguë septicémique : clinique ?', answer: 'Incubation 1-2 semaines. Début progressif avec pseudo-grippal. Phase d\'état : fièvre ondulante, sueurs abondantes nocturnes ("odeur de paille mouillée"), arthralgies/myalgies vagues, asthénie (EG conservé). SP : HPM, SPM, ADP, sacro-iléite+++ (bilatérale et en bascule), orchite+++, talalgies'),
        Flashcard(id: 'bruc_4', question: 'Brucellose focalisée : localisations ?', answer: 'Ostéo-articulaires : spondylodiscite (sujet âgé, région lombaire), sacro-iléite (sujet jeune), arthrites. Neuro-méningées : méningite pure (LCS lymphocytaire, hyperalbuminorachie, normo/hypoglycorachie) ou méningo-encéphalite. Autres : hépatite, orchite, endocardite (principale cause mortalité)'),
        Flashcard(id: 'bruc_5', question: 'Brucellose chronique afocale ?', answer: 'Forme active >6 mois, dg difficile. Absence de fièvre, troubles subjectifs (asthénie, algies diffuses, sueurs au moindre effort), positivité IDR à la mélitine, détection prolongée IgG anti-Brucella'),
        Flashcard(id: 'bruc_6', question: 'Examens de certitude de la brucellose ?', answer: 'Culture : hémoculture positive dans 70% si prélèvement en phase aiguë (peut prendre 1 mois). Sérologie de Wright (IgM spécifiques, positivité >1/80-100 UI). Test au Rose Bengale (IgG spécifiques, positivité >25 UI). IDR à la métiline (forme chronique, abandonnée actuellement). PCR'),
        Flashcard(id: 'bruc_7', question: 'Traitement de la brucellose aiguë ?', answer: 'Doxycycline + Gentamicine pdt 6 semaines. Femme enceinte : Rifampicine + Cotrimoxazole + Acide folique. Enfant <8 ans : Cotrimoxazole + Gentamicine / >8 ans : Doxycycline + Gentamicine'),
        Flashcard(id: 'bruc_8', question: 'Traitement de la brucellose focalisée ?', answer: 'Ostéo-articulaire : Doxycycline + Gentamicine puis relais Rifampicine, 3 mois. Neuro-méningée : Cotrimoxazole + Gentamicine + Rifampicine, 3 mois. Endocardite : Doxycycline + Gentamicine + Rifampicine, 3 mois'),
      ],
    ),
    Course(
      id: 'coqueluche',
      name: 'Coqueluche',
      cards: [
        Flashcard(id: 'coq_1', question: 'Agent causal et réservoir de la coqueluche ?', answer: 'Bordetella pertussis (bacille de Bordet et Gengou), BGN. Réservoir strictement humain (toxi-infection). Transmission interhumaine aérienne (contagiosité+++, peu immunisante). Terrain : sujets non vaccinés et enfants <5 ans'),
        Flashcard(id: 'coq_2', question: 'Phase catarrhale (d\'invasion) de la coqueluche ?', answer: 'Incubation silencieuse 7-15 jrs. Phase catarrhale dure 1-2 semaines : syndrome pseudo-grippal avec fébricule, écoulement nasal, toux nocturne rebelle, spasmodique et émétisante. SP : état subfébrile, EG conservé, injection des yeux, quelques râles ronflants ou sibilants'),
        Flashcard(id: 'coq_3', question: 'Phase des quintes (d\'état) de la coqueluche ?', answer: 'Dure 2-3 semaines. SG : T° normale ou fébricule (fièvre franche → surinfection), EG conservé. SF : toux quinteuse formée de 3 éléments : toux spasmodique (5-20 secousses expiratoires) + reprise inspiratoire bruyante "en chant de coq" + expectoration (collante, glaireuse, "blanc d\'œuf"). SP : cyanose, visage bouffi, pétéchies crânio-faciales'),
        Flashcard(id: 'coq_4', question: 'Forme du NRS dans la coqueluche ?', answer: 'Forme commune : toux faible, peu bruyante >15 min (monoliforme), reprise inspiratoire absente, expectorations difficiles. Forme apnéisante : apnée asphyxiante (cyanose, CVS anoxiques fatales) ou syncopale (bradycardie, ACR). Forme maligne : détresse respiratoire majeure, tachycardie extrême, défaillance multi-viscérale'),
        Flashcard(id: 'coq_5', question: 'Complications de la coqueluche ?', answer: 'Respiratoires : asthme, broncho-pneumonie (surinfection), DDB, PNO. Neurologiques : CVS (hyperthermie, anoxie, troubles ioniques), encéphalopathie. Mécaniques : ulcération frein de la langue, hémorragies conjonctivales, épistaxis, prolapsus rectal, hernie ombilicale'),
        Flashcard(id: 'coq_6', question: 'Examens complémentaires de la coqueluche ?', answer: 'Orientation : NFS (hyperleucocytose à prédominance lymphocytaire), TLT (poumon coquelucheux : opacité triangulaire hilo-phrénique). Certitude : aspiration naso-pharyngée avec culture (méthode de choix, 7-10 jrs, positive 90% phase catarrhale), PCR (+ sensible), sérologie (élévation IgG en 2-3 semaines)'),
        Flashcard(id: 'coq_7', question: 'Traitement curatif de la coqueluche ?', answer: '>1 mois : érythromycine/rovamycine pdt 14 jrs / <1 mois : azithromycine pdt 5 jrs / Si intolérance macrolides → cotrimoxazole. CTC pdt 3-5 jrs si quintes asphyxiantes. PAS d\'antitussifs ! ATB efficace seulement en phase catarrhale'),
        Flashcard(id: 'coq_8', question: 'Prévention de la coqueluche ?', answer: 'Déclaration, isolement, éviction scolaire (21 jrs sans trt / 5 jrs si trt). Vaccination : vaccin acellulaire conjugué DTC à M2, M4, M12 et A6 (rappel tous 10 ans). Chimioprophylaxie contacts : trt identique mais 5 jrs (inutile si maladie >21 jrs chez cas de référence)'),
      ],
    ),
    Course(
      id: 'tetanos',
      name: 'Tétanos',
      cards: [
        Flashcard(id: 'tet_1', question: 'Agent causal et réservoir du tétanos ?', answer: 'Clostridium tetani, BGP, toxines tétaniques (maladie toxi-infectieuse). Réservoir : tellurique+++, animal et humain. Transmission : indirecte par effractions cutanéomuqueuses au contact du sol. Maladie ni contagieuse, ni immunisante. Porte d\'entrée : cutanée+++, traumatique+++, obstétrique, ombilicale, iatrogène. FDR : non vaccinés, âge avancé, toxicomanie IV, accouchement septique'),
        Flashcard(id: 'tet_2', question: 'Phase d\'invasion du tétanos ?', answer: 'Incubation silencieuse 10-15 jrs selon inoculum. Phase d\'invasion dure en moy 2 jrs. SG : ABSENCE de fièvre. SP : trismus+++ (contracture douloureuse bilatérale symétrique permanente des masséters gênant ouverture buccale), dysphagie, faciès sardonique, raideur nuque, contracture muscles peauciers'),
        Flashcard(id: 'tet_3', question: 'Phase d\'état du tétanos ?', answer: 'Contractures généralisées douloureuses permanentes invincibles (muscles thoraciques, para-vertébraux → opisthotonos+++, abdominaux). Recrudescence paroxystique : spasmes généralisés spontanés ou déclenchés (bruit, lumière, soins). Syndrome dysautonomique : HTA, tachycardie, fièvre, sueurs (principale cause mortalité). Autres : hyperréflexie, conscience conservée, apyrexie, constipation'),
        Flashcard(id: 'tet_4', question: 'Diagnostic du tétanos et dg diff ?', answer: 'Dg clinique. Culture et PCR (porte d\'entrée). Dg diff trismus : cause locale (accident sagesse, phlegmon amygdalien, fracture mâchoire), neurologique (tronc cérébral, neuroleptiques), sérothérapie, hystérique'),
        Flashcard(id: 'tet_5', question: 'Traitement curatif du tétanos ?', answer: 'Sérothérapie : Ig spécifiques humaines IM (250-500 UI). ATB IV 5-7 jrs : péni G (métronidazole si allergie). Vaccination par anatoxine tétanique (site différent sérothérapie, 2 rappels à 1 mois). Adjuvant : trt porte d\'entrée, myorelaxants (diazépam ou phénobarbital 2-3 sem), trt syndrome dysautonomique (β-bloquants)'),
        Flashcard(id: 'tet_6', question: 'Prévention du tétanos : CAT selon statut vaccinal ?', answer: 'Déclaration obligatoire. Vaccination complète <5 ans : rien / 5-10 ans : rappel / >10 ans + risque modéré : rappel / >10 ans + risque important : rappel + sérothérapie 250 UI. Vaccination incomplète ou absente : vaccin + sérothérapie 250 UI (modéré) ou 500 UI (important)'),
      ],
    ),
    Course(
      id: 'leptospirose',
      name: 'Leptospirose (LIH)',
      cards: [
        Flashcard(id: 'lepto_1', question: 'Agent causal et réservoir de la leptospirose ?', answer: 'Leptospira (biflexa : saprophyte / interrogans : pathogène), spirochète GN. Sérovars : L. icterohaemorrhagiae donne les formes les plus sévères. Réservoir : rongeurs (rats, souris)+++ (anthropozoonose). Transmission : directe (contact animal) ou indirecte+++ (contact eau/sol contaminés par lésions cutanéomuqueuses)'),
        Flashcard(id: 'lepto_2', question: 'Facteurs favorisants et épidémiologie de la leptospirose ?', answer: 'Professions exposées+++ : agriculteurs, abattoirs, égoutiers, éboueurs. Loisirs aquatiques (baignade eau douce, pêche). Incubation silencieuse 6-12 jrs'),
        Flashcard(id: 'lepto_3', question: 'Phase leptospirémique (invasion) de la LIH ?', answer: 'Dure 3-5 jrs, début brutal. SG : syndrome infectieux (fièvre 39°C, frissons, AEG). SF : pseudo-grippal, épistaxis, nausées/VMS. SP : suffusion conjonctivale bilatérale (+ hémorragie à J3-J4), collapsus, éruption cutanée (fugace), herpès naso-labial, vasodilatation cutanée, SPM, HPM, légère raideur nuque, oligurie urines foncées'),
        Flashcard(id: 'lepto_4', question: 'Phase immune (ictérique) de la LIH : 5 syndromes ?', answer: 'Sd infectieux (T° diminue à l\'apparition ictère vers J7, pas de frissons). Sd hémorragique (thrombopénie, vascularite : épistaxis, purpura, hémorragies). Sd rénal (oligurie, hyperuricémie). Sd hépatique (ictère "flamboyant rouge-orangé", pas de prurit, HPM sans SPM). Sd méningé (méningite lymphocytaire aiguë bénigne)'),
        Flashcard(id: 'lepto_5', question: 'Examens de certitude de la leptospirose ?', answer: 'Examen direct : microscopie à fond noir (abandonnée). Culture (plusieurs semaines). Sérologie : ELISA (dépistage, IgM à partir J8, seuil 400 UI) / MAT ou réaction de Martin et Petit (méthode de référence, à partir J10, seuil 1/100-1/400). PCR (dg précoce)'),
        Flashcard(id: 'lepto_6', question: 'Facteurs de mauvais pronostic de la leptospirose ?', answer: 'Ictère, IR, insuffisance respiratoire, hypoTA, troubles du rythme, altération de la conscience, âge avancé'),
        Flashcard(id: 'lepto_7', question: 'Traitement curatif de la leptospirose ?', answer: 'Forme sévère : péni G/amoxicilline/ceftriaxone IV pdt 7-10 jrs. Forme non sévère : doxycycline/amoxicilline PO pdt 7 jrs. Prévention : déclaration, dératisation, doxycycline 1 fois/semaine (chimioprophylaxie), vaccination (professions à risque)'),
      ],
    ),
    Course(
      id: 'rickettsioses',
      name: 'Rickettsioses',
      cards: [
        Flashcard(id: 'rick_1', question: 'Caractéristiques générales des rickettsies ?', answer: 'Petits bacilles à développement intracellulaire obligatoire, prennent mal la coloration de Gram (colorées par Gimenez ou Giemsa)'),
        Flashcard(id: 'rick_2', question: 'FBM : agent, réservoir et transmission ?', answer: 'Rickettsia conorii. Réservoir : chien et sa tique (Rhipicephalus sanguineus). Pays méditerranéens. Transmission par morsure de tique. Saison chaude. Incubation 6-8 jrs. Tique doit rester attachée au moins 20h pour transmettre la maladie'),
        Flashcard(id: 'rick_3', question: 'FBM : phase d\'invasion ?', answer: 'SG : fièvre 39-40°C et frissons. SF : céphalées et algies diffuses. SP : escarre d\'inoculation ou tache noire de Pieri (dans 50-75% des cas) = lésion croûteuse noirâtre entourée d\'un halo inflammatoire, non douloureuse, préférentiellement dans les grands plis et cuir chevelu, ADP satellite indolore'),
        Flashcard(id: 'rick_4', question: 'FBM : phase d\'état (3-5 jrs après) ?', answer: 'SG : fièvre 39-40°C et AEG. SF : céphalées, myalgies. SP : éruption cutanée (signe majeur) à la racine des membres, se généralisant, touchant paume des mains et plante des pieds, épargnant le visage. D\'abord maculeuse → maculopapuleuse → maculo-papulo-nodulaire boutonneuse, pouvant devenir purpurique'),
        Flashcard(id: 'rick_5', question: 'Diagnostic de la FBM ?', answer: 'Essentiellement clinique (toute fièvre éruptive estivale avec escarre après séjour d\'endémie = FBM jusqu\'à preuve du contraire). Sérologie (IFI : >1/128 ou séroconversion, test de référence), Western-Blot, PCR, culture cellulaire'),
        Flashcard(id: 'rick_6', question: 'Typhus épidémique : agent, vecteur, transmission ?', answer: 'Rickettsia prowazeckii. Réservoir exclusivement humain. Vecteur : pediculus humanus corporus (pou du corps). Transmission : contact excréments du pou avec lésions cutanées ou muqueuses. Facteurs : saison froide, manque d\'hygiène, pauvreté'),
        Flashcard(id: 'rick_7', question: 'Typhus épidémique : clinique ?', answer: 'Exanthème maculeuse → maculopapuleuse avec hémorragies pétéchiales laissant espaces de peau saine, débute thorax → abdomen → membres, épargnant paume/plante/visage. Tuphos. Signes NÉGATIFS : pas d\'escarre d\'inoculation, pas d\'ADP. Complications : myocardite, gangrène extrémités. Maladie de Brill-Zinsser : résurgence du typhus (réactivation)'),
        Flashcard(id: 'rick_8', question: 'Typhus murin : agent, réservoir et différences ?', answer: 'Rickettsia typhi. Réservoir : rat et pou vecteur (Xenopsylla cheopis). Saison chaude. Éruption identique au typhus épidémique mais atteint paume/plante et épargne le visage. Signes neurologiques (confusion, épilepsie, ataxie). Signes NÉGATIFS : idem typhus épidémique'),
        Flashcard(id: 'rick_9', question: 'Traitement de toutes les rickettsioses ?', answer: 'Doxycycline pdt 7 jrs (ou phénicolés/fluoroquinolones/macrolides). Prophylaxie : déclaration obligatoire, lutte contre les vecteurs, hygiène'),
      ],
    ),
    Course(
      id: 'fievre_q',
      name: 'Fièvre Q',
      cards: [
        Flashcard(id: 'fq_1', question: 'Agent causal et réservoir de la fièvre Q ?', answer: 'Coxiella burnetii (ne prend pas Gram, mise en évidence par coloration de Gimenez). 2 Ag : Ag phase I (très virulent, infection chronique) / Ag phase II (peu virulent, infection aiguë). Réservoir : ovins, bovins, caprins, animaux de compagnie, certaines tiques'),
        Flashcard(id: 'fq_2', question: 'Transmission et facteurs favorisants de la fièvre Q ?', answer: 'Directe (contact animaux infectés et leurs déjections) ou indirecte (inhalation aérosols contaminés, consommation lait contaminé). Professions à risque+++ : fermier, abattoirs, vétérinaire. Incubation silencieuse moy 3 semaines'),
        Flashcard(id: 'fq_3', question: 'Forme aiguë de la fièvre Q ?', answer: 'Invasion : pseudo-grippal. Phase d\'état : hépatite fébrile, pneumopathie interstitielle fébrile. Autres : forme fébrile isolée, forme associée hépatique et pulmonaire, méningite/encéphalite, myocardite/péricardite, glomérulonéphrite'),
        Flashcard(id: 'fq_4', question: 'Forme chronique de la fièvre Q ?', answer: 'Évolution >6 mois → endocardite. Facteurs favorisants : valvulopathie préexistante, prothèse valvulaire, ID'),
        Flashcard(id: 'fq_5', question: 'Diagnostic de la fièvre Q ?', answer: 'Sérologie+++ (IFI : fièvre Q aiguë → détection Ac antiphase II / fièvre Q chronique → détection Ac antiphase I). PCR. Culture'),
        Flashcard(id: 'fq_6', question: 'Traitement de la fièvre Q ?', answer: 'Forme aiguë : doxycycline pdt 2 semaines. Forme chronique : doxycycline + hydroxychloroquine pdt 18 mois (24 mois si prothèse valvulaire)'),
      ],
    ),
    Course(
      id: 'tiac',
      name: 'TIAC',
      cards: [
        Flashcard(id: 'tiac_1', question: 'Définition d\'une TIAC ?', answer: 'Survenue d\'au moins 2 cas groupés, d\'une symptomatologie similaire (en général digestive, peut être neurologique), dont on peut rapporter la cause à la même origine alimentaire. Déclaration obligatoire'),
        Flashcard(id: 'tiac_2', question: 'Mécanismes des TIAC ?', answer: 'Ingestion de bactéries libérant des toxines (Clostridium perfringens) ou ingestion de toxines libérées dans les aliments avant l\'absorption (Staphylococcus aureus). Pc généralement bénin (mortalité très faible)'),
        Flashcard(id: 'tiac_3', question: 'TIAC à symptomatologie digestive : agents par ordre de fréquence ?', answer: 'Salmonelloses mineures+++ / Staphylococcus aureus++ / Clostridium perfringens+ / Shigellose / Yersiniose / Campylobacter / Listériose'),
        Flashcard(id: 'tiac_4', question: 'TIAC à symptomatologie neurologique : agents ?', answer: 'Botulisme et intoxication histaminique'),
        Flashcard(id: 'tiac_5', question: 'CAT devant une TIAC ?', answer: 'Confirmer le dg (affirmer épidémie + isoler germe). Écarter dg diff. Identifier aliment responsable (liste repas 3 derniers jrs, durée incubation). Enquête bactério (prélèvements alimentaires, portage sujets exposés et personnel cuisine). Suppression aliments suspects. Déclaration obligatoire à la direction de santé'),
        Flashcard(id: 'tiac_6', question: 'Traitement d\'une TIAC ?', answer: 'Réhydratation hydroélectrolytique+++, mesures diététiques, trt anti-infectieux rare (terrains à risque ou diarrhée persistante, β-lactamines/cotrimoxazole/fluoroquinolones pdt 1 sem), +/- anti-diarrhéique'),
      ],
    ),
    Course(
      id: 'rougeole',
      name: 'Rougeole',
      cards: [
        Flashcard(id: 'roug_1', question: 'Agent, réservoir et transmission de la rougeole ?', answer: 'Virus à ARN enveloppé, Paramyxoviridae, genre Morbilivirus. Réservoir : homme malade (pas de porteur sain). Transmission : interhumaine directe aérienne (très contagieuse et immunisante). Porte d\'entrée : naso-pharyngée ou conjonctivale. Contagiosité : fin incubation, toute l\'invasion et début éruption'),
        Flashcard(id: 'roug_2', question: 'Phase d\'invasion (catarrhe oculo-naso-pharyngé) de la rougeole ?', answer: 'Constante, dure 3-4 jrs. SG : fièvre 38-40°C. SF : catarrhe oculaire (conjonctivite), nasal (coryza), pharyngée (toux rauque), +/- signes digestifs. SP : faciès grognon (très évocateur) et signe de Koplik+++ (pathognomonique : éléments blancs bleutés résistants à l\'abaisse-langue, muqueuse jugale en regard des prémolaires, précède exanthème de 24-48h)'),
        Flashcard(id: 'roug_3', question: 'Phase d\'état de la rougeole : caractéristiques de l\'exanthème ?', answer: 'Éruption maculo-papuleuse rouge, non prurigineuse+++, +/- confluente mais laissant des intervalles de peau saine+++, s\'effaçant à la VP, respectant paume/plante. Évolution descendante : J1 visage → J2 cou/épaules/thorax/MS → J3 abdomen/racine cuisses → J4 MI. Une seule poussée 3-5 jrs, disparaît avec desquamation fine à J7'),
        Flashcard(id: 'roug_4', question: 'Complications de la rougeole ?', answer: 'Phase pré-éruptive : laryngite striduleuse, bronchite capillaire (détresse respiratoire mortelle). Phase éruptive : ORL (rhinite, otite, laryngite), broncho-pulmonaires (poumon rougeoleux), neurologiques (CVS hyperthermiques, encéphalite post-éruptive 3-10j, encéphalite aiguë à inclusions 1-6 mois, PESS+++ 9 mois-15 ans, EEG caractéristique, toujours fatale)'),
        Flashcard(id: 'roug_5', question: 'Traitement et prévention de la rougeole ?', answer: 'Trt : symptomatique uniquement (antipyrétique, hydratation). Prévention individuelle : vaccination 2 doses (11 mois et 18 mois), CI chez enfant <9 mois, femme enceinte et ID. Collective : déclaration, isolement jusqu\'à guérison, éviction scolaire 14 jrs'),
      ],
    ),
    Course(
      id: 'oreillons',
      name: 'Oreillons',
      cards: [
        Flashcard(id: 'orei_1', question: 'Agent, réservoir et transmission des oreillons ?', answer: 'Virus à ARN enveloppé, Paramyxoviridae, genre Rubulavirus. Réservoir : homme malade (pas de porteur sain). Transmission : interhumaine directe aérienne (contagieux et immunisant). Contagiosité : 15 jrs (1 sem avant et 1 sem après symptômes). Incubation 15-24 jrs'),
        Flashcard(id: 'orei_2', question: 'Clinique des oreillons ?', answer: 'Tropisme glandulaire et nerveux+++. Parotidite+++ : tuméfaction douloureuse rétromandibu­laire (d\'abord unilatérale → bilatérale 48-72h), comblant sillon parotidien, soulevant lobe oreille, signe de Mourson (œdème orifice canal de Stensen), fièvre 38-38,5°C. Orchite (surtout post-pubaire, souvent unilatérale, risque atrophie testiculaire). Pancréatite. Manifestations neuro-méningées'),
        Flashcard(id: 'orei_3', question: 'Traitement des oreillons ?', answer: 'Symptomatique. Parotidite : antipyrétiques, antalgiques, AINS. Orchite : antalgiques, AINS (+/- CTC faible dose 8-10 jrs), immobilisation bourses, poches de glace, +/- immunothérapie, spermogramme après. Méningite : repos, antalgiques, AINS. Si VMS répétés → réhydratation IV'),
        Flashcard(id: 'orei_4', question: 'Prévention des oreillons ?', answer: 'Déclaration facultative, isolement (éviction scolaire 15 jrs), vaccination (vaccin vivant atténué, monovalent ou trivalent ROR, 2 doses : 11 mois et 18 mois)'),
      ],
    ),
    Course(
      id: 'rubeole',
      name: 'Rubéole',
      cards: [
        Flashcard(id: 'rub_1', question: 'Agent, transmission et contagiosité de la rubéole ?', answer: 'Virus à ARN enveloppé, Togaviridae, genre Rubivirus. Réservoir : strictement humain. Transmission : directe aérienne (rubéole acquise) ou verticale transplacentaire (rubéole congénitale). Contagiosité : 8 jrs avant et après l\'éruption cutanée. Incubation 14-18 jrs'),
        Flashcard(id: 'rub_2', question: 'Clinique de la rubéole acquise ?', answer: 'Invasion brève 1-3 jrs : fièvre modérée (disparaît à J1 éruption), pseudo-grippal, dysphagie, ADP rondes indolores rétro-auriculaires et cervicales post+++. Phase d\'état : exanthème maculo-papuleux rose pâle non prurigineux laissant intervalles de peau saine (confluentes par endroits). Commence visage → descendant <24h. Disparaît à J3-J5. Aussi : ADP multiples, SPM inconstante, coryza, conjonctivite'),
        Flashcard(id: 'rub_3', question: 'Rubéole congénitale : risques selon le trimestre ?', answer: 'Avant 13 SA : avortement spontané + syndrome malformatif de Gregg (cataracte+++, surdité de perception, cardiopathies congénitales, microcéphalie, retard mental). Entre 13 et 18 SA : risque de surdité uniquement. Au-delà de 18 SA : rubéole congénitale évolutive (hypotrophie, purpura, hépatite, méningite, myocardite, pneumopathie)'),
        Flashcard(id: 'rub_4', question: 'CAT devant une éruption suspecte de rubéole chez la femme enceinte ?', answer: 'Sérologie IgG d\'abord. Si positive → IgM : si négative → immunité ancienne / si positive → primo-infection. Si IgG négative → refaire à 15 jrs : si toujours négative → pas de rubéole, vacciner après accouchement / si positive → primo-infection rubéoleuse'),
      ],
    ),
    Course(
      id: 'herpes',
      name: 'Herpès',
      cards: [
        Flashcard(id: 'herp_1', question: 'Virologie et types de l\'herpès ?', answer: 'Virus à ADN icosaédrique enveloppé, Herpesviridae, Alphaherpesviridae, Simplex virus. HSV-1 : au-dessus de la ceinture (bouche, œil, cerveau). HSV-2 : en dessous de la ceinture (app génitaux et méninges). Réservoir : strictement humain (symptomatique ou asymptomatique+++). Facteurs favorisants : fièvre, soleil, menstruations, stress, ID'),
        Flashcard(id: 'herp_2', question: 'Herpès buccal : primo-infection vs récurrence ?', answer: 'PI → gingivostomatite herpétique : multiples vésicules rapidement ulcérées, très douloureuses, muqueuse inflammatoire, ADP sous-maxillaires. Récurrence → herpès labial récurrent : lésions péri-orificielles plutôt qu\'intrabuccales, unilatérales, en bouquet à la jonction cutanéomuqueuse'),
        Flashcard(id: 'herp_3', question: 'Herpès génital : primo-infection vs récurrence ?', answer: 'PI → multiples vésicules rapidement ulcérées très douloureuses (prépuce/gland ou vulve/vagin/col), ADP inguinales. Récurrence → lésions péri-orificielles unilatérales en bouquet (lèvres vulvaires, sillon balano-préputial, fourreau)'),
        Flashcard(id: 'herp_4', question: 'Méningite-encéphalite herpétique : clinique et traitement ?', answer: 'Début brutal explosif. LCS : liquide lymphocytaire + quelques GR. Confirmation : PCR du LCS. Trt : aciclovir IV (10-15 mg/Kg/8h) + anticonvulsivants pdt 15-21 jrs'),
        Flashcard(id: 'herp_5', question: 'Herpès néonatal : définition et gravité ?', answer: 'Résulte d\'infection génitale maternelle lors de l\'accouchement. Forme rare et grave : multisystémique (purpura, hémorragies, hépatite, pneumonie, méningo-encéphalite) ou strictement neurologique'),
        Flashcard(id: 'herp_6', question: 'Traitement curatif de l\'herpès ?', answer: 'PI herpès génital : aciclovir PO (200mg 5x/j) 10 jrs. PI herpès buccal : aciclovir IV (5mg/Kg/8h) relais valaciclovir PO 8-10 jrs. Récurrence sévère : valaciclovir PO 5 jrs. Méningo-encéphalite : aciclovir IV (10-15mg/Kg/8h) + anticonvulsivants 15-21 jrs. ID : aciclovir IV jusqu\'à guérison'),
        Flashcard(id: 'herp_7', question: 'Prévention de l\'herpès néonatal ?', answer: 'Césarienne, trt antiviral préventif (aciclovir) à partir de 36e semaine, désinfection voies génitales avant accouchement. Prévenir récurrences : aciclovir au long cours'),
      ],
    ),
    Course(
      id: 'varicelle',
      name: 'Varicelle',
      cards: [
        Flashcard(id: 'varic_1', question: 'Virologie et transmission de la varicelle ?', answer: 'VZV (HHV3), mêmes caractéristiques que l\'herpès. Tropisme : LT, cellules épithéliales cutanées et ganglions crâniens-rachidiens. Réservoir : strictement humain. Transmission : contact direct (gouttelettes salivaires, liquides vésiculaires, croûtes). Très contagieuse et immunisante. Contagiosité : quelques jrs avant et après éruption'),
        Flashcard(id: 'varic_2', question: 'Exanthème de la varicelle ?', answer: 'Lésions maculo-papuleuses → vésiculeuses "goutte de rosée" → pustules → ombilication → croûtes (à J10). Débute tronc/visage/cuir chevelu, extension centrifuge épargnant paume/plante. Prurit+++. Lésions d\'âges différents+++ (caractéristique, plusieurs poussées). Peuvent laisser des cicatrices'),
        Flashcard(id: 'varic_3', question: 'Complications de la varicelle ?', answer: 'Cutanées : surinfections bactériennes (S. aureus ou S. pyogenes). Neurologiques : ataxie cérébelleuse (3 sem après, bénigne) et encéphalite (rare, surtout adulte). Pulmonaires : pneumonie (adulte et ID, mortalité élevée femme enceinte). Hépatiques : hépatite sub-clinique. Hémorragiques : thrombopénie, sd hémorragique'),
        Flashcard(id: 'varic_4', question: 'Traitement de la varicelle ?', answer: 'Symptomatique : mesures hygiène/antiseptique local, paracétamol (fièvre), antihistaminiques (prurit). CI : aspirine et AINS (risque sd de Reye et vésicules hémorragiques). Curatif réservé aux terrains susceptibles : aciclovir IV (10-15 mg/Kg/8h) pdt 7-10 jrs'),
        Flashcard(id: 'varic_5', question: 'Prévention de la varicelle ?', answer: 'Déclaration facultative, isolement jusqu\'à guérison, éviction scolaire. +/- immunothérapie dans les 96h (femme enceinte séronégative exposée, NRS exposé à risque néonatal, ID). Vaccination non obligatoire'),
      ],
    ),
    Course(
      id: 'zona',
      name: 'Zona',
      cards: [
        Flashcard(id: 'zona_1', question: 'Définition et épidémiologie du zona ?', answer: 'Réactivation d\'une infection latente à VZV. Même virus que la varicelle. Sporadique (ne récidive jamais sauf ID), chez les sujets âgés. Contagiosité faible'),
        Flashcard(id: 'zona_2', question: 'Clinique du zona ?', answer: 'Invasion : douleurs radiculaires, causalgies, syndrome infectieux, ADP satellites. Phase d\'état : exanthème identique à varicelle mais radiculaire unilatérale localisée au dermatome atteint (souvent thoracique ou lombaire). Douleurs à type de brûlures en paroxysmes. Fièvre modérée. ADP axillaires+++'),
        Flashcard(id: 'zona_3', question: 'Formes topographiques du zona crânien ?', answer: 'Ophtalmique (branche ophtalmique de Willis, grave, risque cécité). Ganglion géniculé (nerf facial → syndrome de Ramsay-Hunt : lésions érythémato-vésiculeuses, paralysie faciale périphérique, signes audio-vestibulaires, agueusie, énanthème 2/3 ant de la langue). Branche maxillaire du trijumeau (énanthème intra-buccal)'),
        Flashcard(id: 'zona_4', question: 'Traitement du zona ?', answer: 'Symptomatique : antiseptique local, antalgiques (phase aiguë), carbamazépine/antidépresseurs (algies post-zostériennes), +/- dénervation. Curatif réservé aux ID, adultes >50 ans et zona ophtalmique : aciclovir IV (10 mg/Kg/8h) 10-15 jrs ou valaciclovir PO (1g 3x/j) 7 jrs'),
      ],
    ),
    Course(
      id: 'vih',
      name: 'VIH/SIDA',
      cards: [
        Flashcard(id: 'vih_1', question: 'Virologie du VIH ?', answer: 'Virus à ARN monocaténaire à polarité +, capside complexe, enveloppé, Retroviridae, genre Lentivirus. Plusieurs Ag : enveloppe (gp120 et gp41), matrice (p17 et p18), capside (p24). VIH-1 : mondial / VIH-2 : limité Afrique de l\'Ouest, moins virulent'),
        Flashcard(id: 'vih_2', question: 'Tropisme et transmission du VIH ?', answer: 'Cible : cellule lymphoïde CD4 et CPA. Réservoir : exclusivement humain. Transmission horizontale : rapport sexuel non protégé+++ (vaginal, anal ou oral), exposition au sang infecté. Transmission verticale : in-utéro (T2), en perpartum+++, allaitement'),
        Flashcard(id: 'vih_3', question: 'Stades de l\'infection VIH ?', answer: 'Stade A (primo-infection) : charge virale élevée, CD4 >500 mais diminué. Stade B (infection chronique) : CD4 500-200, charge virale basse. Stade C (SIDA) : CD4 <200, charge virale élevée. IRIS : après trithérapie réussie surtout chez patient tuberculeux'),
        Flashcard(id: 'vih_4', question: 'Manifestations du stade B (infections opportunistes mineures) ?', answer: 'Cutanéomuqueuses : candidose buccale et génitale, leucoplasie chevelue (EBV), angiomatose bacillaire, dermite séborrhéique, Molluscum contagiosum, herpès, zona, dysplasie col utérin. Hématologiques : pancytopénie. Neurologiques : sd de Guillain-Barré, paralysies périphériques. Sd constitutionnel : fièvre + AEG + diarrhée chronique'),
        Flashcard(id: 'vih_5', question: 'Infections opportunistes majeures du stade C ?', answer: 'Respiratoires : pneumocystose (P. jirovecii, CD4<200), TBC (la + fréquente en Algérie), mycobactérioses atypiques (CD4<50). Digestives : candidose œsophagienne (CD4<200), diarrhées chroniques (CMV, cryptosporidiose). SNC : toxoplasmose cérébrale (CD4<200), cryptococcose neuro-méningée (CD4<100), leucoencéphalopathie (CD4<100). Aussi : rétinite à CMV (CD4<50)'),
        Flashcard(id: 'vih_6', question: 'Cancers associés au SIDA (stade C) ?', answer: 'Sarcome de Kaposi (HHV-8), lymphomes non Hodgkiniens (lymphome de Burkitt, lymphome cérébral primitif), cancer du col utérin (HPV)'),
        Flashcard(id: 'vih_7', question: 'Diagnostic biologique du VIH ?', answer: 'Primo-infection : détection Ag p24 par ELISA (positif à J15) ou RT-PCR (positif à J10). Infection chronique/SIDA (enfant >18 mois et adulte) : 2 tests de dépistage (ELISA, test rapide) puis confirmation Western Blot. NRS <18 mois : PCR charge virale (2 tests positifs)'),
        Flashcard(id: 'vih_8', question: 'Traitement curatif du VIH ?', answer: 'Objectifs : CD4 >500/mm3, charge virale <50 copies/ml. Indication : toute personne infectée. Schéma : trithérapie (2 INTI + 1 IP ou 2 INTI + 1 INNTI ou 2 INTI + 1 II). Suivi : charge virale + CD4 + tests résistance'),
        Flashcard(id: 'vih_9', question: 'Traitement des infections opportunistes dans le VIH ?', answer: 'Pneumocystose : cotrimoxazole IV 3 sem. TBC : comme immunocompétent. Toxoplasmose cérébrale : cotrimoxazole IV puis PO 6-8 sem. Cryptococcose neuro-méningée : attaque (amphotéricine B IV 15 jrs) + entretien (fluconazole PO 10 sem)'),
        Flashcard(id: 'vih_10', question: 'Prévention des infections opportunistes dans le VIH ?', answer: 'Pneumocystose et toxoplasmose : cotrimoxazole si CD4<200, arrêt si CD4>200 pdt 3 mois. Cryptococcose neuro-méningée : fluconazole en prophylaxie secondaire jusqu\'à CD4>200 pdt 6 mois. Mycobactéries atypiques : azithromycine ou clarithromycine si CD4<50. Vaccins CI si CD4<200 (BCG, ROR)'),
      ],
    ),
    Course(
      id: 'polio',
      name: 'Poliomyélite',
      cards: [
        Flashcard(id: 'polio_1', question: 'Agent causal et transmission de la poliomyélite ?', answer: 'Virus à ARN non enveloppé, Picornaviridae, genre Enterovirus, espèce Poliovirus. Tropisme nerveux (moelle+++). Réservoir : exclusivement humain. Transmission : directe (aérienne ou oro-fécale) ou indirecte (eau et aliments souillés). Incubation 7-14 jrs'),
        Flashcard(id: 'polio_2', question: 'Phase paralytique de la poliomyélite ?', answer: 'Installation en 3-6 jrs. Paralysie : mode d\'installation brutal et nocturne / Type : périphérique, flasque, avec hypotonie, abolition ROT, amyotrophie précoce / Topographie : distribution anarchique, asymétrique, non systématisée, prédominant aux racines des membres / SANS : troubles pyramidaux, sphinctériens, ni de la sensibilité'),
        Flashcard(id: 'polio_3', question: 'Différence poliomyélite vs Guillain-Barré ?', answer: 'Poliomyélite : début brutal, atteinte proximale et asymétrique, DAC tardive. Guillain-Barré : début progressif, atteinte distale et symétrique, DAC précoce'),
        Flashcard(id: 'polio_4', question: 'Traitement et prévention de la poliomyélite ?', answer: 'Trt : symptomatique uniquement. Prévention : lutte contre péril fécal, vaccination (inactivé ou vivant atténué)'),
      ],
    ),
    Course(
      id: 'paludisme',
      name: 'Paludisme',
      cards: [
        Flashcard(id: 'palu_1', question: 'Espèces de Plasmodium et leur gravité ?', answer: 'P. falciparum : le + fréquent, le + résistant, donne les formes les + graves. P. vivax : le + fréquent en Algérie. P. ovale : évolution souvent bénigne. P. malariae : 1ère espèce découverte. P. knowlesi : parasite des macaques, endémique Malaisie, peut donner forme grave'),
        Flashcard(id: 'palu_2', question: 'Réservoir, transmission et immunité du paludisme ?', answer: 'Réservoir HI → homme / vecteur-HD → anophèle femelle. Transmission : piqure moustique vecteur, ou rarement transfusion, greffe, transplacentaire, toxicomanie IV. Immunité : "prémunition" (semi-immunité acquise temporaire chez exposés continuellement, disparaît après 1-2 ans de non-exposition)'),
        Flashcard(id: 'palu_3', question: 'Accès palustre (forme typique) : clinique ?', answer: 'Frissons (généralisés, 1-2h) + fièvre (élevée 40-41°C, 1-4h) + sueurs (profuses, 1-2h). Cet accès est : quotidien (P. knowlesi), tierce J1/J3/J5 (P. falciparum/vivax/ovale), quarte J1/J4/J7 (P. malariae). SP : langue saburrale, herpès labial, HPM et SPM. Invasion : syndrome infectieux + pseudo-grippal + troubles digestifs + signes d\'hémolyse (pâleur, sub-ictère, SPM)'),
        Flashcard(id: 'palu_4', question: 'Paludisme grave : définition et critères ?', answer: 'Apanage de P. falciparum + critères de gravité OMS : neuropalu (coma fébrile, urgence mortelle en 2-3 jrs sans trt), prostration, détresse respiratoire/OAP, hyperparasitémie, anémie sévère, ictère, IRF, acidose métabolique, hémoglobinurie, choc, hypoglycémie, T° très élevée, VMS répétés'),
        Flashcard(id: 'palu_5', question: 'Examens para-cliniques du paludisme ?', answer: '"Toute fièvre au retour d\'un voyage en zone tropicale est un palu jusqu\'à preuve du contraire". Frottis sanguin et goutte épaisse+++ (coloration MGG : confirme dg, identifie espèce, évalue parasitémie, GE meilleure que FS). TDR (test diagnostic rapide). Contrôle efficacité trt : J3, J7 et J28'),
        Flashcard(id: 'palu_6', question: 'Traitement du paludisme simple ?', answer: 'P. falciparum : ArL (artéméther-luméfantrine) ou quinine + primaquine pdt 3 jrs. P. vivax/ovale : ArL ou chloroquine + primaquine pdt 3 jrs. P. malariae/knowlesi : ArL ou chloroquine'),
        Flashcard(id: 'palu_7', question: 'Traitement du paludisme grave ?', answer: 'Artésunate IV (2,4 mg/kg à H0, H12, H24 puis 1x/j) puis relais ArL. Alternative : Quinine IV (charge 16 mg/kg → entretien 8 mg/kg/8h, max 7 jrs). Surveillance hypoglycémie sous quinine. USI obligatoire'),
        Flashcard(id: 'palu_8', question: 'Chimioprophylaxie du paludisme selon les zones ?', answer: 'Zone A/I (pas de chloroquino-résistance) : prévention piqûres seulement. Zone B/II : piqûres + chloroquine (veille départ, séjour, 4 sem après). Zones C-D/III-IV : piqûres + atovaquone-proguanil (veille départ, séjour, 1 sem après) ou doxycycline ou méfloquine (10-15 jrs avant). PAS de chimioprophylaxie si séjour >6 mois'),
      ],
    ),
    Course(
      id: 'rage',
      name: 'Rage',
      cards: [
        Flashcard(id: 'rage_1', question: 'Agent causal et réservoir de la rage ?', answer: 'Virus neurotrope à ARN enveloppé "bullet shape", Rhabdoviridae, genre Lyssavirus. Réservoir : mammifères sauvages (chiens, loups, renards, chats, chauve-souris) ou domestiques (chiens et chats). Zoonose. En Algérie : chien le + fréquent, secondé par le chat'),
        Flashcard(id: 'rage_2', question: 'Transmission de la rage ?', answer: 'Contact salive animal infecté avec muqueuses ou peau lésée : morsure (mode le + fréquent), griffure (rare), inhalation aérosols (rare). Transmission interhumaine : uniquement lors de greffe d\'organe. FDR : proximité au SNC, zone richement innervée, inoculum'),
        Flashcard(id: 'rage_3', question: 'Clinique de la rage spastique ou furieuse ?', answer: 'Incubation silencieuse 4 jrs - plusieurs années (généralement <3 mois). Invasion : troubles sensitifs subjectifs douleurs/paresthésies au niveau région mordue + troubles du comportement (anxiété, insomnie) + fièvre 38-39°C. Phase d\'état : excitation psychomotrice, dysphagie, soif vive, spasmes pharyngo-laryngés, hydrophobie+++ et aérophobie, troubles neurovégétatifs. Évolution : inévitablement fatale (paralysie cardiorespi après 3-4 jrs de coma)'),
        Flashcard(id: 'rage_4', question: 'CAT devant exposition de grade 2 (morsure sans saignement hors zones à risque) ?', answer: 'Vaccination uniquement. Vaccin sur culture cellulaire (protocole Zagreb) : 4 doses (2D+G à J0, 1 à J7, 1 à J21) en IM au deltoïde (>2 ans) ou face antérolatérale de la cuisse (<2 ans). Vaccin sur tissu nerveux : 7 doses base (J0-J6 SC péri-ombilical) + 4 rappels (J10, J14, J29, J90 ID)'),
        Flashcard(id: 'rage_5', question: 'CAT devant exposition de grade 3 (morsure avec saignement, zones à risque, animal sauvage) ?', answer: 'Vaccination + sérothérapie (sérum antirabique équin, 40 UI/Kg, ne doit pas être <800 UI ni >3000 UI, en 2 injections au site lésion + IM fesse). Test de tolérance préalable (Besredka). Sérothérapie inutile si déjà vacciné depuis >8 jrs. Cas particulier sujet ID : protocole Essen (5 doses J0/J3/J7/J14/J28) + sérothérapie'),
        Flashcard(id: 'rage_6', question: 'CAT vis-à-vis de l\'animal mordeur ?', answer: 'A : animal connu et vivant, vacciné ou non → observation 15 jrs. B : animal d\'élevage → considérer comme enragé, abattre et acheminer la tête. C : animal abattu ou retrouvé mort → acheminer la tête. D : animal en fuite ou sauvage → considérer comme potentiellement enragé'),
      ],
    ),
    Course(
      id: 'pasteurellose',
      name: 'Pasteurellose et Maladie des Griffes de Chat',
      cards: [
        Flashcard(id: 'past_1', question: 'Pasteurellose : agent, transmission et clinique ?', answer: 'Pasteurella multocida (BGN). Réservoir : VAS des chiens, chats et autres mammifères. Transmission : morsure+++ (chats et chiens), contact salive avec plaie ouverte, léchage, griffure. Incubation courte <24h. Clinique : plaie rouge douloureuse œdématiée, écoulement purulent ou séro-sanglant, trainée de lymphangite avec ADP satellite. Complications : abcès, arthrite, bactériémie'),
        Flashcard(id: 'past_2', question: 'Traitement de la pasteurellose ?', answer: 'Amoxicilline-acide clavulanique ou doxycycline pdt 10 jrs'),
        Flashcard(id: 'past_3', question: 'Maladie des griffes de chat : agent et clinique ?', answer: 'Bartonella henselae (BGN). Réservoir : chats et puces des chats. Transmission : griffure+++ ou morsure de chat. Clinique typique : J3-J10 papule/pustule au site inoculation → après qq sem (1-7) ADP inflammatoire satellite ferme et mobile + fébricule 38°C. Angiomatose bacillaire (ID) : prolifération vasculaire cutanée (papules rouge violacé)'),
        Flashcard(id: 'past_4', question: 'Traitement de la maladie des griffes de chat ?', answer: 'Azithromycine ou doxycycline'),
      ],
    ),
  ];
}

const List<AntibioticEntry> antibioticData = [
  AntibioticEntry(
    disease: 'Méningite à Pneumocoque',
    category: 'bacterial',
    agent: 'Streptococcus pneumoniae',
    firstLine: 'C3G IV : Céfotaxime 200-300 mg/kg/j ou Ceftriaxone 70-100 mg/kg/j\n± Vancomycine si signes de gravité ou PSDP',
    alternative: 'Phénicolés (chloramphénicol/thiamphénicol) si allergie β-lactamines\nRifampicine si CI vancomycine',
    duration: '15-21 jours',
    notes: 'Dexaméthasone IV pdt 4 jrs (débuter en même temps que ATB). PL de contrôle à J3 (évolution défavorable) et J15 (fin trt)',
  ),
  AntibioticEntry(
    disease: 'Pneumonie à Pneumocoque (PFLA)',
    category: 'bacterial',
    agent: 'Streptococcus pneumoniae',
    firstLine: 'Ambulatoire PO : Amoxicilline\nHospitalier IV : Ampicilline ou Céfotaxime/Ceftriaxone',
    alternative: 'Érythromycine ou Pristinamycine (ambulatoire) / Lévofloxacine (hospitalier) si allergie β-lactamines',
    duration: '10-15 jours',
    notes: 'Score CRB-65 pour décision d\'hospitalisation. Prophylaxie : Prevenar13 puis Pneumo23',
  ),
  AntibioticEntry(
    disease: 'Méningococcies (MCS)',
    category: 'bacterial',
    agent: 'Neisseria meningitidis',
    firstLine: 'Amoxicilline 200 mg/kg/j IV ou Céfotaxime 200 mg/kg/j IV ou Ceftriaxone 100 mg/kg/j IV',
    alternative: 'Thiamphénicol, Ciprofloxacine ou Rifampicine si allergie β-lactamines',
    duration: '7-10 jours',
    notes: 'Dexaméthasone IV pdt 4 jrs. PL contrôle à J8. Prophylaxie contacts : spiramycine 5 jrs ou rifampicine 2 jrs. MDO',
  ),
  AntibioticEntry(
    disease: 'Septicémie Méningococcique (Purpura Fulminans)',
    category: 'bacterial',
    agent: 'Neisseria meningitidis',
    firstLine: 'Amoxicilline IV le plus tôt possible (avant PL)',
    alternative: 'Céfotaxime ou Ceftriaxone',
    duration: 'Selon évolution',
    notes: 'CTC ABSOLUMENT CI. Hospitalisation en réa. Trt choc : remplissage, PFC, drogues vasoactives, héparinothérapie si CIVD',
  ),
  AntibioticEntry(
    disease: 'Staphylococcie (SASM)',
    category: 'bacterial',
    agent: 'Staphylococcus aureus méticilline-sensible',
    firstLine: 'Oxacilline + Gentamicine IV (toutes les 4-6h)',
    alternative: 'Fosfomycine, Acide fusidique, Rifampicine, Cotrimoxazole, Céfazoline, Pristinamycine, Clindamycine, Ofloxacine',
    duration: 'Sans localisations : 2 sem / Avec localisations : 3-6 sem',
    notes: 'Gentamicine max 7 jrs. Trt staphylococcie maligne de face : CTC + trt porte d\'entrée',
  ),
  AntibioticEntry(
    disease: 'Staphylococcie (SARM)',
    category: 'bacterial',
    agent: 'Staphylococcus aureus méticilline-résistant',
    firstLine: 'Vancomycine + Gentamicine IV',
    alternative: 'Daptomycine, Linézolide',
    duration: 'Sans localisations : 2 sem / Avec localisations : 3-6 sem',
    notes: 'Gentamicine max 7 jrs. Double ATB précoce et synergique à fortes doses',
  ),
  AntibioticEntry(
    disease: 'Angine Streptococcique',
    category: 'bacterial',
    agent: 'Streptococcus pyogenes (groupe A)',
    firstLine: 'Extencilline IM (dose unique) ou Amoxicilline PO',
    alternative: 'Érythromycine PO si allergie β-lactamines',
    duration: '10 jours',
    notes: 'Prévention RAA et GNA. ASLO à contrôler',
  ),
  AntibioticEntry(
    disease: 'Érysipèle',
    category: 'bacterial',
    agent: 'Streptococcus pyogenes (groupe A)',
    firstLine: 'Péni G ou Amoxicilline PO/IV',
    alternative: 'Érythromycine si allergie β-lactamines. AINS et CTC CI',
    duration: '10 jours',
    notes: 'Trt porte d\'entrée. Prévention récidives : extencilline toutes 3-4 sem pdt 1 an si ≥2 épisodes',
  ),
  AntibioticEntry(
    disease: 'Diphtérie',
    category: 'bacterial',
    agent: 'Corynebacterium diphtheriae',
    firstLine: 'Péni G IV → relais Péni V PO. Doses SAD : nasale 10-20.000 UI / amygdalienne 15-25.000 UI / pharyngo-laryngée 20-40.000 UI / sévère 40-100.000 UI',
    alternative: 'Érythromycine si allergie β-lactamines',
    duration: '14 jours',
    notes: 'Sérothérapie URGENTE (test Besredka avant). Déclaration, isolement, éviction scolaire 1 mois. Vaccination par anatoxine en convalescence',
  ),
  AntibioticEntry(
    disease: 'Septicémie à BGN (SBGN)',
    category: 'bacterial',
    agent: 'Entérobactéries, Pseudomonas aeruginosa',
    firstLine: 'Communautaire : Amoxicilline (1ère intention) / C3G (2ème intention) + Gentamicine IV\nNosocomial : Imipénème/Méropénème + Amikacine',
    alternative: 'Fluoroquinolones si allergie β-lactamines / Fosfomycine si CI fluoroquinolones',
    duration: '2-4-6 semaines selon localisations',
    notes: 'Gentamicine max 7 jrs. Trt porte d\'entrée+++. Trt choc en USI si choc septique',
  ),
  AntibioticEntry(
    disease: 'Fièvre Typhoïde (FT)',
    category: 'bacterial',
    agent: 'Salmonella typhi / paratyphi',
    firstLine: 'Cotrimoxazole PO (1ère intention) / Ofloxacine ou Perfloxacine PO/IV 10 jrs (pays développés)',
    alternative: 'Amoxicilline PO (porteur chronique, femme enceinte) / Ceftriaxone IV/IM (très efficace)',
    duration: '10-21 jours selon molécule',
    notes: 'Chloramphénicol/Thiamphénicol pdt 21 jrs (abandonné, hématotoxicité). CTC si formes toxiniques sévères. Déclaration, éviction scolaire 20 jrs',
  ),
  AntibioticEntry(
    disease: 'Choléra',
    category: 'bacterial',
    agent: 'Vibrio cholerae',
    firstLine: 'Adulte et enfant >5 ans : Tétracycline ou Doxycycline\nEnfant <5 ans et femme enceinte : Furazolidone ou Azithromycine/Cotrimoxazole',
    alternative: 'Ciprofloxacine',
    duration: '1-3 jours',
    notes: 'Réhydratation PRIMORDIALE (SRO sauf choc/DSH sévère/VMS incoercibles → ringer lactate). Si diurèse non reprise à 18h → furosémide / à 20h → hémodialyse. Déclaration',
  ),
  AntibioticEntry(
    disease: 'Brucellose Aiguë',
    category: 'bacterial',
    agent: 'Brucella melitensis / abortus',
    firstLine: 'Doxycycline + Gentamicine pdt 6 semaines',
    alternative: 'Femme enceinte : Rifampicine + Cotrimoxazole + Acide folique\nEnfant <8 ans : Cotrimoxazole + Gentamicine\nEnfant >8 ans : Doxycycline + Gentamicine',
    duration: '≥ 6 semaines',
    notes: 'Brucellose focalisée ostéo-articulaire : 3 mois / Neuro-méningée : 3 mois / Endocardite : 3 mois. Au moins 2 ATB à bonne diffusion intracellulaire. MDO',
  ),
  AntibioticEntry(
    disease: 'Coqueluche',
    category: 'bacterial',
    agent: 'Bordetella pertussis',
    firstLine: '>1 mois : Érythromycine/Rovamycine 14 jrs\n<1 mois : Azithromycine 5 jrs',
    alternative: 'Cotrimoxazole si intolérance macrolides',
    duration: '5-14 jours',
    notes: 'ATB efficace seulement en phase catarrhale. PAS d\'antitussifs ! CTC 3-5 jrs si quintes asphyxiantes. Déclaration. Chimioprophylaxie contacts : 5 jrs',
  ),
  AntibioticEntry(
    disease: 'Tétanos',
    category: 'bacterial',
    agent: 'Clostridium tetani',
    firstLine: 'Métronidazole 500 mg × 3/j IV pdt 7-10 jrs\n+ Ig antitétaniques humaines IM (250-500 UI)',
    alternative: 'Péni G si allergie métronidazole',
    duration: '7-10 jours',
    notes: 'Vaccination par anatoxine (site différent). Myorelaxants (diazépam 2-3 sem). β-bloquants si sd dysautonomique. Déclaration obligatoire',
  ),
  AntibioticEntry(
    disease: 'Leptospirose (LIH)',
    category: 'bacterial',
    agent: 'Leptospira interrogans',
    firstLine: 'Forme sévère : Péni G / Amoxicilline / Ceftriaxone IV pdt 7-10 jrs\nForme non sévère : Doxycycline / Amoxicilline PO pdt 7 jrs',
    alternative: 'Selon antibiogramme',
    duration: '7-10 jours',
    notes: 'Chimioprophylaxie : Doxycycline 200 mg/semaine. Déclaration',
  ),
  AntibioticEntry(
    disease: 'Rickettsioses (FBM, Typhus)',
    category: 'bacterial',
    agent: 'Rickettsia conorii / prowazeckii / typhi',
    firstLine: 'Doxycycline pdt 7 jrs',
    alternative: 'Phénicolés, Fluoroquinolones, Macrolides',
    duration: '7 jours',
    notes: 'Résistance aux β-lactamines. Déclaration obligatoire. Lutte contre les vecteurs',
  ),
  AntibioticEntry(
    disease: 'Fièvre Q',
    category: 'bacterial',
    agent: 'Coxiella burnetii',
    firstLine: 'Forme aiguë : Doxycycline pdt 2 semaines\nForme chronique : Doxycycline + Hydroxychloroquine pdt 18 mois',
    alternative: 'Selon forme et terrain',
    duration: '2 sem (aiguë) / 18-24 mois (chronique)',
    notes: 'Prothèse valvulaire : 24 mois. Professions à risque+++',
  ),
  AntibioticEntry(
    disease: 'Pasteurellose',
    category: 'bacterial',
    agent: 'Pasteurella multocida',
    firstLine: 'Amoxicilline-acide clavulanique pdt 10 jrs',
    alternative: 'Doxycycline pdt 10 jrs',
    duration: '10 jours',
    notes: 'Incubation courte <24h. Soins locaux de la plaie',
  ),
  AntibioticEntry(
    disease: 'Maladie des Griffes de Chat',
    category: 'bacterial',
    agent: 'Bartonella henselae',
    firstLine: 'Azithromycine',
    alternative: 'Doxycycline',
    duration: 'Selon évolution',
    notes: 'ADP satellite au site inoculation. Angiomatose bacillaire chez l\'ID',
  ),
  AntibioticEntry(
    disease: 'Paludisme Simple',
    category: 'parasitic',
    agent: 'Plasmodium falciparum / vivax / ovale / malariae',
    firstLine: 'P. falciparum : Artéméther-Luméfantrine (ArL) ou Quinine + Primaquine pdt 3 jrs\nP. vivax/ovale : ArL ou Chloroquine + Primaquine\nP. malariae/knowlesi : ArL ou Chloroquine',
    alternative: 'Femme enceinte 1er T : Quinine + Clindamycine / 2e-3e T : ArL',
    duration: '3-7 jours',
    notes: 'Urgence médicale. MDO. Contrôle efficacité à J3, J7, J28',
  ),
  AntibioticEntry(
    disease: 'Paludisme Grave',
    category: 'parasitic',
    agent: 'Plasmodium falciparum',
    firstLine: 'Artésunate IV : 2,4 mg/kg à H0, H12, H24 puis 1x/j → relais ArL',
    alternative: 'Quinine IV : charge 16 mg/kg → entretien 8 mg/kg/8h (max 7 jrs)',
    duration: 'Selon évolution',
    notes: 'USI obligatoire. Surveillance hypoglycémie sous quinine. Femme enceinte forme grave : Artésunate ou Quinine IV',
  ),
  AntibioticEntry(
    disease: 'Herpès - Méningo-encéphalite',
    category: 'viral',
    agent: 'Herpes Simplex Virus type 1',
    firstLine: 'Aciclovir IV (10-15 mg/Kg/8h) + Anticonvulsivants pdt 15-21 jrs',
    alternative: 'Valaciclovir PO en relais',
    duration: '15-21 jours',
    notes: 'URGENCE ! Simple suspicion suffit à initier le trt. Aciclovir néphrotoxique',
  ),
  AntibioticEntry(
    disease: 'Herpès Génital - Primo-infection',
    category: 'viral',
    agent: 'Herpes Simplex Virus type 2',
    firstLine: 'Aciclovir PO (200 mg 5x/j) pdt 10 jrs',
    alternative: 'Valaciclovir PO',
    duration: '10 jours',
    notes: 'Prévention herpès néonatal : césarienne, aciclovir préventif à partir de 36e semaine',
  ),
  AntibioticEntry(
    disease: 'Varicelle - Formes Graves',
    category: 'viral',
    agent: 'Varicella-Zoster Virus (VZV)',
    firstLine: 'Aciclovir IV (10-15 mg/Kg/8h) pdt 7-10 jrs',
    alternative: 'Valaciclovir PO',
    duration: '7-10 jours',
    notes: 'CI : Aspirine et AINS (risque sd de Reye). Réservé aux terrains susceptibles (adulte, ID, femme enceinte)',
  ),
  AntibioticEntry(
    disease: 'Zona - Formes Graves',
    category: 'viral',
    agent: 'Varicella-Zoster Virus (VZV)',
    firstLine: 'Aciclovir IV (10 mg/Kg/8h) pdt 10-15 jrs\nOu Valaciclovir PO (1g 3x/j) pdt 7 jrs',
    alternative: 'Selon terrain',
    duration: '7-15 jours',
    notes: 'Réservé aux ID, adultes >50 ans et zona ophtalmique. Carbamazépine/antidépresseurs pour algies post-zostériennes',
  ),
];
